Team update type
teamyapp/teamy-backend pull request #106
Opened 2021-12-10 13:52 UTC by CreatCodeBuild

2021-12-10 13:54 UTC, CreatCodeBuild commented on app/api/gql/schema.graphqls
> +type TeamUpdate {
With the amount of actions growing, keeping everything under the `mutation` type is not readable and bad developer experiences.

Let's make the API more object oriented and have Update types for every entities.

The frontend needs to adapt as well.

2021-12-10 13:54 UTC, CreatCodeBuild commented on app/entity/team.go
> +type OrderedSet_ID []entity.ID
Let's not follow the Go naming convention, it's not helpful.

2021-12-10 13:55 UTC, CreatCodeBuild commented on app/entity/team.go
> +type OrderedSet_ID []entity.ID
In 1.18, we will be able to have generic container types.

2021-12-10 13:56 UTC, CreatCodeBuild reviewed
@magicoder10

2021-12-11 08:05 UTC, naturetime10 requested changes

2021-12-11 08:05 UTC, naturetime10 commented on app/api/gql/schema.graphqls
> +	promoteTaskToNeedAttention(Id: ID!): Team!
```suggestion
	promoteTaskToNeedAttention(Id: ID!): TeamUpdate!
```

2021-12-11 08:08 UTC, naturetime10 requested changes

2021-12-11 08:08 UTC, naturetime10 commented on app/entity/team.go
> +
```suggestion
// The follow line doesn't follow Go's naming convention and will be refactored once Go 1.18 is released with Generics support.
```

2021-12-12 01:05 UTC, naturetime10 approved these changes

2021-12-12 01:06 UTC, merged