Add API to query Teams
teamyapp/teamy-backend pull request #111
Opened 2021-12-18 09:34 UTC by naturetime10

2021-12-18 11:29 UTC, CreatCodeBuild requested changes

2021-12-18 11:29 UTC, CreatCodeBuild commented on app/api/gql/schema.graphqls
> +	userUpdate(id: ID!): UserUpdate!
let's not make it verbose.
```
mutation {
  user(id) { ... }
}
```
vs
```
mutation {
  userUpdate(id) { ... }
}
```

2021-12-18 11:29 UTC, CreatCodeBuild commented on app/api/gql/schema.graphqls
> +	teamUpdate(id: ID!): TeamUpdate!
same

2021-12-18 11:29 UTC, CreatCodeBuild commented on app/api/gql/schema.graphqls
> +	team(id: ID!): Team!
let's not have single API at all. Use
```
teams(ids: [ID!]!): [Team!]!
```
For now it can have `ids` only and in the future we can refactor similar to `tasks`

2021-12-18 11:33 UTC, CreatCodeBuild commented on app/api/gql/resolver/team.go
> +	})
What is the access control of this API? Users only able to view teams that they are a member of?

Is that's the case, should it just be
```
me {
  teams
}
```
Currently `me.teams` has no parameters, we can just add parameters to it.

2021-12-18 11:34 UTC, CreatCodeBuild commented on app/api/gql/resolver/team.go
> +	})
But we can keep this one as well. Resolvers can share code.

2021-12-19 01:32 UTC, naturetime10 commented
Discussed offline. Merging now.

2021-12-19 01:32 UTC, merged