Allow all team members to modify the task
teamyapp/teamy-backend pull request #113
Opened 2021-12-21 07:52 UTC by CreatCodeBuild

2021-12-21 07:52 UTC, CreatCodeBuild commented on app/api/gql/resolver/task_mutation.go
> +func (m Mutation) CreateTask(
move without modification

2021-12-21 07:52 UTC, CreatCodeBuild commented on app/api/gql/resolver/task_mutation.go
> +func (m Mutation) DeleteTask(ctx context.Context, args struct {
move without modification

2021-12-21 07:55 UTC, CreatCodeBuild commented on app/entity/task.go
> +	// NumOfUnknowns    *int
We don't use them now. Need to have a concrete design before adding them back.

2021-12-21 07:56 UTC, CreatCodeBuild commented on app/api/gql/resolver/task_mutation.go
> +	userResolver := User{
L115-L150

2021-12-21 08:21 UTC, naturetime10 requested changes

2021-12-21 08:21 UTC, naturetime10 commented on app/api/gql/resolver/task_mutation.go
> +	}
Check team membership/ownership instead?

2021-12-21 08:21 UTC, naturetime10 commented on app/api/gql/resolver/task_mutation.go
> +			}
If user cannot reach the task, is this even possible?

2021-12-21 08:21 UTC, naturetime10 commented on app/api/gql/resolver/task_mutation.go
> +		}
I think we should first check whether the task is owned by an user's team, which is most likely yes. If not, then we check if the task is `created` by the user.

2021-12-21 08:21 UTC, naturetime10 commented on app/api/gql/resolver/task_mutation.go
> +	{ // access control
We need to put access control in it's own function in order to be reused in `DeleteTask`

2021-12-22 03:45 UTC, CreatCodeBuild commented on app/api/gql/resolver/task_mutation.go
> +		}
yes, this is the logic.

2021-12-22 03:46 UTC, CreatCodeBuild commented on app/api/gql/resolver/task_mutation.go
> +			}
not possible through normal GQL operations

2021-12-22 03:47 UTC, CreatCodeBuild commented on app/api/gql/resolver/task_mutation.go
> +	{ // access control
1. Let's experiment with this feature with `UpdateTask` only and see how we like it.
2. Need to refactor to `TaskUpdate` type pattern before further refactor.

2021-12-22 03:48 UTC, CreatCodeBuild reviewed
@magicoder10 please review

2021-12-22 08:37 UTC, naturetime10 requested changes

2021-12-22 08:37 UTC, naturetime10 commented on app/api/gql/resolver/task_mutation.go
> +		}
@CreatCodeBuild I think the current code is doing the opposite.

2021-12-22 08:37 UTC, naturetime10 commented on app/api/gql/resolver/task_mutation.go
> +			}
@CreatCodeBuild Then can we remove this check?

2021-12-22 08:39 UTC, CreatCodeBuild commented on app/api/gql/resolver/task_mutation.go
> +		}
Why?

2021-12-22 08:45 UTC, naturetime10 commented on app/api/gql/resolver/task_mutation.go
> +		}
I think the code is checking whether the task is reachable by user first.

2021-12-23 01:55 UTC, naturetime10 approved these changes

2021-12-23 01:56 UTC, merged