Fill in team icon upload gql API
teamyapp/teamy-backend pull request #223
Opened 2022-08-04 02:32 UTC by duanxianbo

2022-08-04 02:41 UTC, naturetime10 requested changes

2022-08-04 02:41 UTC, naturetime10 commented on core/service/team.go
> +	teamFileUploadSessionDao   dao.TeamFileUploadSession
```suggestion
	cloudClientRegistry        *cloudAPI.ClientRegistry
	taskDao                    dao.Task
	sprintDao                  dao.Sprint
	teamDao                    dao.Team
	teamFileUploadSessionDao   dao.TeamFileUploadSession
```

2022-08-04 02:41 UTC, naturetime10 commented on core/service/team.go
> +
```suggestion
```

2022-08-04 02:41 UTC, naturetime10 commented on core/service/team.go
> +		err = fmt.Errorf("profile upload session is already completed: teamID=%v, fileUploadSessionID=%v",
```suggestion
		err = fmt.Errorf("icon upload session is already completed: teamID=%v, fileUploadSessionID=%v",
```

2022-08-04 02:41 UTC, naturetime10 commented on core/service/team.go
> +
```suggestion
```

2022-08-04 02:41 UTC, naturetime10 commented on core/service/team.go
> +	return fileUploadSessionID, err
```suggestion
	return fileUploadSessionID, t.teamDao.UpdateTeam(team)
```

2022-08-04 02:41 UTC, naturetime10 commented on core/service/team.go
> +	teamFileUploadSessionDao dao.TeamFileUploadSession) Team {
```suggestion
	cloudClientRegistry *cloudAPI.ClientRegistry,
	taskDao dao.Task,
	sprintDao dao.Sprint,
	teamDao dao.Team,
	teamFileUploadSessionDao dao.TeamFileUploadSession,
) Team {
```

2022-08-04 02:41 UTC, naturetime10 commented on core/api/gql/team_mutation.go
> +	return graphql.ID(strconv.FormatUint(uploadSessionID, 10)), nil
```suggestion
	return toGraphQLID(uploadSessionID), nil
```

2022-08-04 13:46 UTC, duanxianbo commented on core/service/team.go
> +	return fileUploadSessionID, err
this should be an tuple of (id, error), right?

2022-08-04 14:32 UTC, naturetime10 requested changes

2022-08-04 14:32 UTC, naturetime10 commented on core/api/gql/team_mutation.go
> +	}
```suggestion
	if err != nil {
	    log.Println(err)
		return "", err
	}
```

2022-08-04 14:32 UTC, naturetime10 commented on core/api/gql/team_mutation.go
> +		return "", err
```suggestion
        log.Println(err)
		return "", err
```

2022-08-04 14:32 UTC, naturetime10 approved these changes

2022-08-05 02:02 UTC, naturetime10 approved these changes

2022-08-05 02:02 UTC, merged