Add activity store
teamyapp/teamy-backend pull request #260
Opened 2022-09-10 01:53 UTC by duanxianbo

2022-09-10 22:57 UTC, naturetime10 requested changes

2022-09-10 22:57 UTC, naturetime10 commented on core/collection/task_syncer.go
> +
```suggestion
```

2022-09-10 22:57 UTC, naturetime10 commented on core/collection/task_syncer.go
> +func (t TaskSyncer) StartDraggingSyncTask(taskID uint64, userID uint64, clientID uint64, owningTeamID uint64) error {
```suggestion
func (t TaskSyncer) StartDraggingSyncTask(taskID uint64, userID uint64, clientID uint64, owningTeamID uint64) {
```

2022-09-10 22:57 UTC, naturetime10 commented on core/collection/task_syncer.go
> +func (t TaskSyncer) StopDraggingSyncTask(taskID uint64, userID uint64, clientID uint64, owningTeamID uint64) error {
```suggestion
func (t TaskSyncer) StopDraggingSyncTask(taskID uint64, userID uint64, clientID uint64, owningTeamID uint64) {
```

2022-09-10 22:57 UTC, naturetime10 commented on core/collection/task_syncer.go
> +			TeamID:   owningTeamID,
```suggestion
```

2022-09-10 22:57 UTC, naturetime10 commented on core/entity/user_status.go
> +	UserStatusDisConnected UserStatus = "DisConnected"
```suggestion
	DisconnectedUserStatus UserStatus = "Disconnected"
```

2022-09-10 22:57 UTC, naturetime10 commented on core/entity/user_status.go
> +	UserStatusInitialized  UserStatus = "Initialized"
```suggestion
	InitializedUserStatus  UserStatus = "Initialized"
```

2022-09-10 22:57 UTC, naturetime10 commented on core/entity/user_status.go
> +	UserStatusConnected    UserStatus = "Connected"
```suggestion
	ConnectedUserStatus   UserStatus = "Connected"
```

2022-09-10 22:57 UTC, naturetime10 commented on core/realtime/activity_store.go
> +
```suggestion
```

2022-09-10 22:57 UTC, naturetime10 commented on core/realtime/activity_store.go
> +
```suggestion
```

2022-09-10 22:57 UTC, naturetime10 commented on core/realtime/activity_store.go
> +	clientActivity.taskAction.dragging = true
I wonder whether we need clientActivity. Are user activity combined with team activity not enough?

2022-09-10 22:57 UTC, naturetime10 commented on core/realtime/client_activity.go
> +		taskAction: &TaskAction{},
```suggestion
```

Let's leave it as nil by default

2022-09-10 22:57 UTC, naturetime10 commented on core/realtime/mutation.go
> +type UserDraggingTaskPayload struct {
```suggestion
type TeamActivityPayload struct {
```

2022-09-11 01:05 UTC, duanxianbo commented on core/realtime/activity_store.go
> +
`ClientDisconnect`

2022-09-18 15:21 UTC, closed without merging