Add activity store for real time drag & drop
teamyapp/teamy-backend pull request #262
Opened 2022-09-12 00:46 UTC by duanxianbo

2022-09-17 18:31 UTC, naturetime10 requested changes

2022-09-17 18:31 UTC, naturetime10 commented on core/api/gql/task_activity.go
> +		deps:         deps,
Are we using `deps`?

2022-09-17 18:31 UTC, naturetime10 commented on core/api/gql/team.go
> +	taskActivityList := make([]TaskActivity, 0)
```suggestion
	gqlTaskActivitys := make([]TaskActivity, 0)
```

2022-09-17 18:31 UTC, naturetime10 commented on core/cache/activity.go
> +func (a Activity) FindAllTaskActivitiesByTeamID(teamID uint64) (map[uint64]*entity.TaskActivity, error) {
```suggestion
func (a Activity) FindAllTaskActivitiesByTeamID(teamID uint64) ([]entity.TaskActivity, error) {
```

2022-09-17 18:31 UTC, naturetime10 commented on core/cache/activity.go
> +
```suggestion
```

2022-09-17 18:31 UTC, naturetime10 commented on core/entity/team_activitty.go
> +package entity
File name should be `team_activity.go` not `team_activitty`

2022-09-17 18:31 UTC, naturetime10 commented on core/entity/task_activity.go
> +	DraggingClientID uint64
```suggestion
	DraggingAction DraggingAction
```

2022-09-17 18:31 UTC, naturetime10 commented on core/entity/task_activity.go
> +type TeamTaskDraggingActivity struct {
```suggestion
type DraggingAction struct {
```

2022-09-17 18:31 UTC, naturetime10 commented on core/entity/task_activity.go
> +	TeamID           uint64
```suggestion
```

2022-09-17 18:31 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	isDragging: Boolean!
```suggestion
	draggingAction: DraggingAction
```

2022-09-17 18:31 UTC, naturetime10 commented on core/api/gql/schema.graphql
```suggestion
type DraggingAction {
    isDragging: Boolean!;
    task: Task;
    dragByUser: User;
    draggingClientId: ID;
}
```

2022-09-17 18:31 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +func (c ClientNotifier) processMutation(message entity.MessageEvent) {
```suggestion
func (c ClientNotifier) processMessage(message entity.MessageEvent) {
```

2022-09-17 18:44 UTC, duanxianbo commented on core/entity/task_activity.go
> +}
```
type TaskActivity struct {
       taskID
       dragTaskActivity {
            IsDragging       bool
	    DragByUserID     uint64
	   DraggingClientID uint64
      }
}
	
}
```

2022-09-17 18:46 UTC, duanxianbo commented on core/entity/task_activity.go
> +}
```suggestion
```

2022-09-17 18:52 UTC, duanxianbo commented on core/realtime/message.go
> +}
MutationMessage

2022-09-17 18:52 UTC, duanxianbo commented on core/realtime/message.go
> +type Metadata struct {
MetadataMessage

2022-09-17 18:57 UTC, duanxianbo commented on core/entity/message_event.go
> +}
move this to realtime package

2022-09-17 19:09 UTC, duanxianbo commented on core/realtime/state_syncer.go
> +}
use clientNotifier to send clientID

2022-09-17 19:10 UTC, duanxianbo commented on core/realtime/state_syncer.go
> +			}
```suggestion

```

2022-09-17 19:24 UTC, duanxianbo commented on core/realtime/client_notifier.go
> +func (c ClientNotifier) processMutation(message entity.MessageEvent) {
- metadata should be sent before mutation
- if mutation is arrived, but metadata has not been sent, buffer the mutation
- metadata has been sent, and client notifier is ready to push mutation
- browser should tell the client notifier by http request that it received and processed inital state from graphql api

2022-09-17 19:31 UTC, duanxianbo commented on core/realtime/client_notifier.go
> +func (c ClientNotifier) processMutation(message entity.MessageEvent) {
- client notifier has an api that handles the browser initial state ready signal 
- client notifier needs an api to send the metadata
- client notifier needs an api to receive the mutation
- client notifier needs to transform the mutation to mutation message before sending it out, this allows us to remove unnecessary information
- client notifier ignores mutations until it received initial state ready signal

2022-09-17 19:45 UTC, duanxianbo commented on core/realtime/state_syncer.go
>  }
need an api to handle client initial state ready

2022-09-18 15:22 UTC, duanxianbo commented on core/api/gql/task_activity.go
> +		deps:         deps,
removed

2022-09-18 15:23 UTC, duanxianbo commented on core/entity/task_activity.go
> +	TeamID           uint64
done

2022-09-18 15:35 UTC, duanxianbo commented on core/entity/team_activitty.go
> +package entity
done

2022-09-19 00:14 UTC, naturetime10 requested changes

2022-09-19 00:14 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	isDragging: Boolean!
```suggestion
	isDragging: Boolean!
	dragByUserId: ID!
	draggingClientId: ID!
```

2022-09-19 00:14 UTC, naturetime10 commented on core/api/gql/team.go
> +	return gqlTaskActivitys, nil
```suggestion
	return collect.Map(taskActivities, func (taskActivity entity.TaskActivity, index int) TaskActivity {
	    return newTaskActivity(*taskActivity)
	}), nil
```

2022-09-19 00:14 UTC, naturetime10 commented on core/api/realtime_state_sync.go
> +			Path:        path.Join(realTimeStateSyncPrefix, "clients", "ready"),
```suggestion
			Path:        path.Join(realTimeStateSyncPrefix, "clients", "{clientID}","initial-state-ready"),
```

2022-09-19 00:14 UTC, naturetime10 commented on core/api/realtime_state_sync.go
> +}
```suggestion
```

2022-09-19 00:14 UTC, naturetime10 commented on core/api/realtime_state_sync.go
> +			Method:      http.MethodPost,
```suggestion
			Method:      http.MethodPut,
```

2022-09-19 00:14 UTC, naturetime10 commented on core/api/realtime_state_sync.go
> +			HandlerFunc: r.ready,
```suggestion
			HandlerFunc: r.clientInitialStateReady,
```

2022-09-19 00:14 UTC, naturetime10 commented on core/api/realtime_state_sync.go
> +	err = r.realTimeStateSyncer.SetClientIsReady(userID, clientID)
```suggestion
	err = r.realTimeStateSyncer.OnInitialStateReady(userID, clientID)
```

2022-09-19 00:14 UTC, naturetime10 commented on core/cache/activity.go
> +
```suggestion
```

2022-09-19 00:14 UTC, naturetime10 commented on core/cache/activity.go
> +func (a Activity) AddTeamActivity(teamID uint64) *entity.TeamActivity {
```suggestion
func (a Activity) InitTeamActivity(teamID uint64) *entity.TeamActivity {
```

2022-09-19 00:14 UTC, naturetime10 commented on core/cache/activity.go
> +func (a Activity) GetOrAddTeamActivity(teamID uint64) *entity.TeamActivity {
```suggestion
func (a Activity) GetOrInitTeamActivity(teamID uint64) *entity.TeamActivity {
```

2022-09-19 00:14 UTC, naturetime10 commented on core/cache/activity.go
> +		return a.AddTeamActivity(teamID)
```suggestion
		return a.InitTeamActivity(teamID)
```

2022-09-19 00:14 UTC, naturetime10 commented on core/cache/activity.go
> +func (a Activity) UpdateTaskActivity(taskID uint64, teamActivity *entity.TeamActivity, taskActivity *entity.TaskActivity) *entity.TaskActivity {
```suggestion
func (a Activity) UpdateTaskActivity(teamID uint64, taskID uint64, taskActivity *entity.TaskActivity) *entity.TaskActivity {
```

2022-09-19 00:14 UTC, naturetime10 commented on core/cache/activity.go
> +func (a Activity) UpdateTaskActivity(taskID uint64, teamActivity *entity.TeamActivity, taskActivity *entity.TaskActivity) *entity.TaskActivity {
We need to make sure we are updating initial state of `Activity`. This current interface allows passing in random `teamActivity` that's not in  `teamActivities`.

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/invitation_syncer.go
> +	)
```suggestion
		Payload: invitation,
		},
	)
```

2022-09-19 00:14 UTC, naturetime10 commented on core/cache/activity.go
> +	return Activity{dataCollector: dataCollector, teamActivities: map[uint64]*entity.TeamActivity{}}
```suggestion
	return Activity{
	    dataCollector: dataCollector, 
	    teamActivities: map[uint64]*entity.TeamActivity{},
	}
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/message_syncer.go
> +	)
```suggestion
		Payload: message,
		})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/message_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/message_syncer.go
> +	)
```suggestion
		Payload: messageID,
		})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/sprint_task_relation_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/sprint_task_relation_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/task_await_for_relation_syncer.go
> +	)
```suggestion
		Payload: relation,
		})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/task_await_for_relation_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/task_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/task_syncer.go
> +	)
```suggestion
		Payload: task,
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/task_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/task_syncer.go
> +
```suggestion
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/task_syncer.go
> +
```suggestion
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/team_member_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/team_member_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/team_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/team_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/user_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +
```suggestion
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +	isReady                     bool
```suggestion
	acceptMutation                     bool
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +	c.isReady = isReady
```suggestion
	c.acceptMutation = true
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +func (c *ClientNotifier) setClientIsReady(isReady bool) {
```suggestion
func (c *ClientNotifier) onInitialStateReady(isReady bool) {
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +	messages                    chan MessageEvent
```suggestion
        clientID uint64
	messages                    chan MessageEvent
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +func (c *ClientNotifier) sendClientID(clientID uint64) {
```suggestion
func (c *ClientNotifier) sentMetadata(clientID uint64) {
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +			ClientID: clientID,
```suggestion
			ClientID: c.clientID,
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +
```suggestion
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +		messages:                    messages,
```suggestion
                 clientID: clientID,
		messages:                    messages,
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/message.go
> +}
```suggestion
type MessageType string

const (
	MutationMessageType MessageType = "Mutation"
	MetadataMessageType MessageType = "Metadata"
)

type Message struct {
	Type    MessageType
	Payload interface{}
}

type MutationType string

const (
	CreateMutationType MutationType = "Create"
	UpdateMutationType MutationType = "Update"
	DeleteMutationType MutationType = "Delete"
)
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/message.go
> +}
Let's put this into a separate file called `mutation.go`

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +func (s *StateSyncer) SetClientIsReady(userID uint64, clientID uint64) error {
```suggestion
func (s *StateSyncer) OnInitialStateReady(userID uint64, clientID uint64) error {
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	}
```suggestion
		})
		return err
	}
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	}
```suggestion
		})
		return err
	}
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	clilentNotifier.setClientIsReady(true)
```suggestion
	clilentNotifier. OnInitialStateReady()
```

2022-09-19 00:14 UTC, naturetime10 commented on core/realtime/team_notifier.go
> +
```suggestion
```

2022-09-19 00:14 UTC, naturetime10 commented on core/service/task.go
> +	task, err := t.taskDao.FindTaskByID(taskID)
```suggestion
	}
	
	task, err := t.taskDao.FindTaskByID(taskID)
```

2022-09-19 00:14 UTC, naturetime10 commented on core/service/task.go
> +	teamActivity := t.activityCache.GetOrAddTeamActivity(task.OwningTeamID)
```suggestion
```

2022-09-19 00:14 UTC, naturetime10 commented on core/service/task.go
> +	t.activityCache.UpdateTaskActivity(taskID, teamActivity, &entity.TaskActivity{
```suggestion
	t.activityCache.UpdateTaskActivity(task.OwningTeamID, taskID, &entity.TaskActivity{
```

2022-09-19 00:14 UTC, naturetime10 commented on core/service/task.go
> +			DraggingClientID: clientID,
```suggestion
			IsDragging:       true,
			DragByUserID:     userID,
			DraggingClientID: clientID,
```

2022-09-19 00:14 UTC, naturetime10 commented on core/collection/task_syncer.go
> +func (t TaskSyncer) StartDraggingSyncTask(taskID uint64, userID uint64, clientID uint64, owningTeamID uint64) error {
```suggestion
func (t TaskSyncer) UpdateTaskActivity(taskID uint64) error {
```

2022-09-19 00:14 UTC, naturetime10 commented on core/entity/task_activity.go
> +}
Move into `cache` package.

2022-09-19 00:14 UTC, naturetime10 commented on core/entity/task_activity.go
> +type DragTaskActivity struct {
Move into `cache` package.

2022-09-19 00:14 UTC, naturetime10 commented on core/entity/team_activity.go
> +type TeamActivity struct {
Move into `cache` package.

2022-09-19 00:14 UTC, naturetime10 commented on core/service/task.go
> +	t.activityCache.UpdateTaskActivity(taskID, teamActivity, &entity.TaskActivity{
Move into `taskSyncer`

2022-09-19 00:14 UTC, naturetime10 commented on core/service/task.go
> +		}})
Move into taskSyncer

2022-09-19 00:14 UTC, naturetime10 commented on core/service/task.go
> +	return t.taskSyncer.StopDraggingSyncTask(taskID, userID, clientID, task.OwningTeamID)
UpdateTaskActivity

2022-09-19 00:14 UTC, naturetime10 commented on core/service/task.go
> +	return t.taskSyncer.StartDraggingSyncTask(taskID, userID, clientID, task.OwningTeamID)
UpdateTaskActivity

2022-09-19 00:24 UTC, duanxianbo commented on core/entity/task_activity.go
> +}
but this is also needed in the gql?

2022-09-19 00:24 UTC, duanxianbo commented on core/entity/task_activity.go
> +type DragTaskActivity struct {
but this is also needed in the gql?

2022-09-19 00:27 UTC, naturetime10 commented on core/entity/task_activity.go
> +}
@duanxianbo I changed my mind. We can keep in `entity`.

2022-09-19 00:27 UTC, naturetime10 commented on core/entity/task_activity.go
> +type DragTaskActivity struct {
We can keep in entity.

2022-09-19 00:33 UTC, duanxianbo commented on core/service/task.go
> +		}})
you mean put those cache manipulation into taskSyncer?  I think taskSyncer is for realtime?

2022-09-19 01:31 UTC, duanxianbo commented on core/realtime/message.go
> +}
done

2022-09-19 01:40 UTC, naturetime10 requested changes

2022-09-19 01:40 UTC, naturetime10 commented on core/api/realtime_state_sync.go
> +
```suggestion
```

2022-09-19 01:40 UTC, naturetime10 commented on core/cache/activity.go
> +
```suggestion
```
```suggestion

```

2022-09-19 01:40 UTC, naturetime10 commented on core/cache/activity.go
> +func (a Activity) FindAllTaskActivitiesByTeamID(teamID uint64) (map[uint64]*entity.TaskActivity, error) {
```suggestion
func (a Activity) FindAllTaskActivitiesByTeamID(teamID uint64) map[uint64]*entity.TaskActivity {
```

2022-09-19 01:40 UTC, naturetime10 commented on core/cache/activity.go
> +	return teamActivity.TaskActivities, nil
```suggestion
	return teamActivity.TaskActivities
```

2022-09-19 01:40 UTC, naturetime10 commented on core/cache/activity.go
> +
```suggestion
```

2022-09-19 01:40 UTC, naturetime10 commented on core/collection/invitation_syncer.go
> +	)
```suggestion
	})
```

2022-09-19 01:40 UTC, naturetime10 commented on core/realtime/message.go
> +}
Let's move this into `mutation.go`

2022-09-19 01:40 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	clientNotifier.sentMetadata(s.nextClientID)
```suggestion
	clientNotifier.sentMetadata()
```

2022-09-19 01:40 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +func (c *ClientNotifier) sentMetadata(clientID uint64) {
```suggestion
func (c *ClientNotifier) sentMetadata() {
```

2022-09-20 05:37 UTC, naturetime10 approved these changes

2022-09-20 05:37 UTC, naturetime10 commented on core/realtime/mutation.go
> +}
We should move this after `type Mutation struct`

2022-09-20 05:38 UTC, merged