Refactor client + task activity
teamyapp/teamy-backend pull request #271
Opened 2022-09-28 01:24 UTC by duanxianbo

2022-09-28 01:33 UTC, naturetime10 requested changes

2022-09-28 01:33 UTC, naturetime10 commented on core/api/gql/client.go
> +
```suggestion
```

2022-09-28 01:33 UTC, naturetime10 commented on core/api/gql/client.go
> +func (c Client) ID(ct context.Context) graphql.ID {
```suggestion
func (c Client) ID() graphql.ID {
```

2022-09-28 01:33 UTC, naturetime10 commented on core/api/gql/client.go
> +		c.deps.dataCollector.Logger.Log(obs.Error, obs.Props{obs.CauseProp: err})
```suggestion
		c.deps.dataCollector.Logger.LogWithContext(obs.Error, obs.Props{obs.CauseProp: err})
```

2022-09-28 01:33 UTC, naturetime10 commented on core/api/gql/client.go
> +		c.deps.dataCollector.Logger.Log(obs.Error, obs.Props{obs.CauseProp: err})
Use `LogWithContext` to include request ID

2022-09-28 01:33 UTC, naturetime10 commented on core/api/gql/client.go
> +	user, err := c.deps.userDao.FindUserByID(ct, c.client.UserID)
We are moving away from `userDao` to `userService` so that GraphQL & gRPC can share logic. Please use `FindUserByID` from `service.User` instead.

2022-09-28 01:33 UTC, naturetime10 commented on core/service/task.go
> +				},
```suggestion
				Client: entity.Client{},
```

Not needed if task is not dragging.

2022-09-28 02:44 UTC, duanxianbo commented on core/service/task.go
> +				},
trying to apply this, but get a problem, we are setting empty client with no userid in the activity cache too, and then next time when getting activities from the gql, the resolver will still try to resolve an empty user from a client

2022-09-29 01:57 UTC, duanxianbo commented on core/api/gql/client.go
> +	user, err := c.deps.userDao.FindUserByID(ct, c.client.UserID)
done

2022-09-29 01:58 UTC, duanxianbo commented on core/service/task.go
> +				},
done

2022-09-29 05:16 UTC, naturetime10 approved these changes

2022-09-30 05:31 UTC, naturetime10 requested changes

2022-09-30 05:31 UTC, naturetime10 commented on core/collection/task_syncer.go
> +	task entity.Task,
owningTeamID

2022-09-30 05:31 UTC, naturetime10 commented on core/collection/task_syncer.go
> +	task entity.Task,
We should keep input requirements as minimal as possible so that this API can be reused as many places as possible.

2022-09-30 05:31 UTC, naturetime10 commented on core/collection/task_syncer.go
> +	task entity.Task,
We can get taskID from taskActivity

2022-09-30 15:17 UTC, duanxianbo commented on core/collection/task_syncer.go
> +	task entity.Task,
right, actually teamID and taskID can be retrieved from taskActivity now

2022-10-01 00:52 UTC, naturetime10 approved these changes

2022-10-01 02:51 UTC, merged