Move graphQL task logic to service package
teamyapp/teamy-backend pull request #304
Opened 2022-11-23 08:02 UTC by yijia-cc

2022-11-24 01:28 UTC, duanxianbo approved these changes

2022-11-24 20:18 UTC, naturetime10 requested changes

2022-11-24 20:18 UTC, naturetime10 commented on core/service/task.go
>  	"time"
Format imports

2022-11-24 20:18 UTC, naturetime10 commented on core/service/task.go
> +		err = t.authorizer.assignParentResource(ct, authorization.TaskResourceType, task.ID, authorization.TeamResourceType, task.OwningTeamID)
```suggestion
		err = t.authorizer.assignParentResource(ct, authorization.TaskResourceType, task.ID, authorization.TeamResourceType, teamID)
```

2022-11-24 20:18 UTC, naturetime10 commented on core/service/task.go
> +				Message: fmt.Sprintf("Unauthorize: %v", query),
```suggestion
				Message: fmt.Sprintf("Unauthorized: %v", query),
```

2022-11-24 20:18 UTC, naturetime10 commented
We need to check whether the user is allowed to create task.

2022-11-27 01:18 UTC, naturetime10 approved these changes

2022-11-27 01:19 UTC, merged