Copy tasks to next sprint
teamyapp/teamy-backend pull request #308
Opened 2022-12-04 17:13 UTC by duanxianbo

2022-12-04 23:02 UTC, naturetime10 requested changes

2022-12-04 23:02 UTC, naturetime10 commented on core/api/gql/sprint_mutation.go
> +	}
We can do collect.Map

2022-12-04 23:02 UTC, naturetime10 commented on core/dep/wire.go
> +func newSprintService(
Why do we need this function?

2022-12-04 23:02 UTC, naturetime10 commented on core/service/sprint.go
> +
```suggestion
```

2022-12-04 23:02 UTC, naturetime10 commented on core/service/sprint.go
> +	cloneTaskInput := CreateTaskInput{
```suggestion
	clonedTask := CreateTaskInput{
```

2022-12-04 23:02 UTC, naturetime10 commented on core/service/task.go
> +	IsPlanned     *bool
```suggestion
	IsPlanned     bool
```

2022-12-04 23:02 UTC, naturetime10 commented on core/service/task.go
> +		IsPlanned:     &isPlanned,
```suggestion
		IsPlanned:     taskInput.isPlanned,
```

2022-12-04 23:02 UTC, naturetime10 commented on core/service/task.go
> +	}
Is this function needed? Can we just invoke `createTask`?

2022-12-04 23:02 UTC, naturetime10 commented on core/service/task.go
> +		IsPlanned:        *taskInput.IsPlanned,
```suggestion
		IsPlanned:        taskInput.IsPlanned,
```

2022-12-04 23:02 UTC, naturetime10 commented on core/service/sprint.go
> +	task, err = s.taskService.CloneTask(ct, task.OwningTeamID, cloneTaskInput)
```suggestion
	task, err = s.taskService.createTask(ct, task.OwningTeamID, clonedTask)
```

2022-12-04 23:02 UTC, naturetime10 commented on core/service/sprint.go
> +	}
Not needed. Directly return task from line 328.

2022-12-04 23:02 UTC, naturetime10 commented on core/service/task.go
> +	}
```suggestion
```

2022-12-04 23:03 UTC, naturetime10 requested changes

2022-12-04 23:03 UTC, naturetime10 commented on core/service/sprint.go
> +	res := make([]entity.Task, 0)
Need to check permission

2022-12-05 01:46 UTC, duanxianbo commented on core/dep/wire.go
> +func newSprintService(
because now sprint service need the task service

2022-12-05 01:58 UTC, naturetime10 commented on core/dep/wire.go
> +func newSprintService(
@duanxianbo Task service can be automatically filled in using wire. This is the reason we use wire.

2022-12-05 02:01 UTC, duanxianbo commented on core/dep/wire.go
> +func newSprintService(
that is wired, because it can not build if I do not add that funciton with task service as last param

2022-12-05 02:07 UTC, duanxianbo commented on core/service/task.go
> +		IsPlanned:     &isPlanned,
are we always passing isPlanned in to task.Create?

2022-12-05 02:09 UTC, duanxianbo commented on core/service/task.go
> +	}
as we said, the payload for creating a task is different, ex: for create a task, we take current userId as the taskCreatorId, BUT when cloning the task, we just task what it is on the original task

2022-12-05 02:10 UTC, naturetime10 commented on core/service/task.go
> +		IsPlanned:     &isPlanned,
Yes. If leave untouched, will be set to `false` by default.

2022-12-05 02:11 UTC, naturetime10 commented on core/service/task.go
> +	}
I recommend we don't do optional parameter and pass in `entity.Task` to the helper method instead.

2022-12-05 02:14 UTC, duanxianbo commented on core/service/task.go
> +		IsPlanned:     &isPlanned,
but when there is no isPlanned in taskInput, it raises an error?

2022-12-05 02:16 UTC, duanxianbo commented on core/service/task.go
> +	}
are you suggesting removing CloningTask? ah, maybe we should refactor how we call CreateTask elsewhere?

2022-12-06 02:59 UTC, duanxianbo commented on core/dep/wire.go
> +func newSprintService(
fixed

2022-12-06 03:00 UTC, duanxianbo commented on core/service/sprint.go
> +	res := make([]entity.Task, 0)
use create permission here for now, should replace by clone permission

2022-12-06 03:02 UTC, duanxianbo commented on core/service/sprint.go
> +	}
what task do you want to return?

2022-12-06 03:05 UTC, duanxianbo commented on core/api/gql/sprint_mutation.go
> +	}
done

2022-12-07 02:13 UTC, naturetime10 requested changes

2022-12-07 02:13 UTC, naturetime10 commented on core/service/task.go
> +		IsPlanned:     &isPlanned,
I think create task input should not accept `isPlanned` field.

2022-12-07 02:13 UTC, naturetime10 commented on core/service/task.go
> +	return t.createTask(ct, teamID, createTaskInput)
We should pass in a task here instead.

2022-12-07 02:13 UTC, naturetime10 commented on core/dep/wire.go
> +		service.NewAuthorizer,
Can we put Authorizer in `serviceSet`? Many services will use it in the future.

2022-12-07 02:13 UTC, naturetime10 commented on core/dep/wire.go
> +		service.NewAuthorizer,
```suggestion
```

2022-12-07 02:13 UTC, naturetime10 commented on core/dep/wire.go
> +		service.NewAuthorizer,
```suggestion
```

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +		err := errors.New("user id not found")
```suggestion
		err := errors.New("Unauthorized")
```

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +	}
Move inside `if feature.EnableAuthorization {` because `userID` is only used there.

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +		if !ok {
```suggestion
		if err != nil {
```

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +		}
```suggestion
		}
		
```

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +		query := authorization.NewCreateTaskQuery(userID, sprint.OwningTeamID)
Can we create Clone task authorization query in this PR?

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +		query := authorization.NewCreateTaskQuery(userID, sprint.OwningTeamID)
@yijia-cc Can you help @duanxianbo with this?

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +	task, err = s.taskService.createTask(ct, task.OwningTeamID, cloneTask)
```suggestion
	createdTask, err = s.taskService.createTask(ct, task.OwningTeamID, cloneTask)
```

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +	}
Just return `createdTask` to avoid the extra network I/O & query to DB

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +	}
```suggestion
	s.AddTaskToSprint()
```

2022-12-07 02:13 UTC, naturetime10 commented on core/service/sprint.go
> +
```suggestion
```

2022-12-07 02:13 UTC, naturetime10 commented on core/service/task.go
> +	OwningTeamID uint64
```suggestion
```

2022-12-07 02:13 UTC, naturetime10 commented on core/service/task.go
> +	OwningTeamID  uint64
```suggestion
```

2022-12-07 02:32 UTC, duanxianbo commented on core/service/task.go
> +	OwningTeamID uint64
why  we are removing this?

2022-12-07 02:33 UTC, duanxianbo commented on core/service/task.go
> +	OwningTeamID  uint64
why are we removing this?

2022-12-07 02:34 UTC, naturetime10 commented on core/service/task.go
> +	OwningTeamID  uint64
We are passing in owning team ID from all places using it already.

2022-12-07 02:34 UTC, naturetime10 commented on core/service/task.go
> +	OwningTeamID uint64
We are passing in owning team ID from all places using it already.

2022-12-07 02:51 UTC, duanxianbo commented on core/dep/wire.go
> +		service.NewAuthorizer,
done

2022-12-07 02:51 UTC, duanxianbo commented on core/service/sprint.go
> +	}
removed

2022-12-07 02:52 UTC, duanxianbo commented on core/service/task.go
> +	return t.createTask(ct, teamID, createTaskInput)
I am not sure, do we have a task entity inside the helper function createTask?

2022-12-07 11:51 UTC, naturetime10 commented on core/service/task.go
> +	return t.createTask(ct, teamID, createTaskInput)
@duanxianbo  My previous comment was outdated.

2022-12-08 02:12 UTC, naturetime10 approved these changes

2022-12-08 02:27 UTC, merged