Add userGroups and permission when creating new team
teamyapp/teamy-backend pull request #310
Opened 2022-12-05 03:05 UTC by yijia-cc

Add userGroups and permission when creating new team

Refactor UpdateTeam to move authorization to service package

2022-12-11 00:53 UTC, naturetime10 requested changes

2022-12-11 00:53 UTC, naturetime10 commented on core/api/gql/team_mutation.go
> +	team, err := m.deps.teamService.UpdateTeam(ct, teamID, args.Input.Name, ownerUserID)
should pass in UpdateTeamInput instead of `args.Input.Name, ownerUserID` so that we can add more field without extra code changes in the future.

2022-12-11 00:53 UTC, naturetime10 commented on core/api/gql/team_mutation.go
> +	team, err := m.deps.teamService.CreateTeam(ct, args.Team.Name)
should pass in CreateTeamInput instead of `args.Input.Name` so that we can add more field without extra code changes in the future.

2022-12-11 00:53 UTC, naturetime10 commented on core/dep/wire.go
> +		teamSyncer,
```suggestion
		teamSyncer,
		sprintService,
```

2022-12-11 00:53 UTC, naturetime10 commented on core/service/authorizer.go
> +	"fmt"
Remove empty line and format code.

2022-12-11 00:53 UTC, naturetime10 commented on core/service/team.go
> +
```suggestion
```

Format code.

2022-12-11 00:53 UTC, naturetime10 commented on core/service/team.go
> +	userID, ok := ctx.UserIDFromContext(ct)
Check and make sure user has permission to createTeam

2022-12-11 00:53 UTC, naturetime10 commented on go.mod
> +//replace github.com/teamyapp/cloud => ../../cloud
```suggestion
//replace github.com/teamyapp/cloud => ../cloud
```

2022-12-11 00:53 UTC, naturetime10 commented on core/service/team.go
> +		query := authorization.NewUpdateTeamSettingsQuery(userID, teamID)
```suggestion
		query := authorization.NewUpdateTeamQuery(userID, teamID)
```

2022-12-11 00:53 UTC, naturetime10 commented on core/service/team.go
> +		teamAdminUserGroupName := fmt.Sprintf("TeamAdmin%d", team.ID)
```suggestion
		teamAdminUserGroupName := fmt.Sprintf("Team%d/Admin", team.ID)
```

2022-12-11 00:53 UTC, naturetime10 commented on core/service/team.go
> +		teamAdminDescription := fmt.Sprintf("Admin user(s) for %s", teamAdminUserGroupName)
```suggestion
		teamAdminDescription := fmt.Sprintf("Admins for team %s", teamAdminUserGroupName)
```

2022-12-11 00:53 UTC, naturetime10 commented on core/service/authorizer.go
> +
```suggestion
```

2022-12-11 00:53 UTC, naturetime10 commented on core/authorization/operation.go
> +type Operation string
```suggestion
type ResourceOperation struct {
    resourceType ResourceType
    operation string
}
```

2022-12-11 00:53 UTC, naturetime10 commented on core/service/team.go
> +	userID, ok := ctx.UserIDFromContext(ct)
Let's prefix all APIs in services with authorization enabled as `SecureXXX`

2022-12-11 07:08 UTC, yijia-cc commented on core/service/team.go
> +	userID, ok := ctx.UserIDFromContext(ct)
Discussed offline, all users should be authorized to create teams and add comment to the code. Will keep the API name as it is.

2022-12-11 07:21 UTC, yijia-cc commented on core/service/team.go
> +		query := authorization.NewUpdateTeamSettingsQuery(userID, teamID)
Will keep this unchanged, because it's for updating team settings.

2022-12-11 08:43 UTC, naturetime10 requested changes

2022-12-11 08:43 UTC, naturetime10 commented on core/api/gql/team_mutation.go
> +		IconURL     *string
```suggestion
```

2022-12-11 08:43 UTC, naturetime10 commented on core/api/gql/team_mutation.go
> +		IconURL:     args.Input.IconURL,
```suggestion
```

2022-12-11 08:43 UTC, naturetime10 commented on core/authorization/resource_operation.go
> +	ResourceType ResourceType
```suggestion
        ResourceType ResourceType
	Operation    string
```

2022-12-11 08:43 UTC, naturetime10 commented on core/authorization/resource_operation.go
> +		ResourceType: TeamResourceType,
Let's swap the location of ResourceType and Operation for better human readability.

2022-12-11 08:43 UTC, naturetime10 commented on core/authorization/resource_operation.go
> +	// Operations for Sprint
Use a separate var for each resource type for readability.

2022-12-11 08:43 UTC, naturetime10 commented on core/service/authorizer.go
> +
```suggestion
```

2022-12-11 08:43 UTC, naturetime10 commented on core/service/team.go
> +
```suggestion
```

2022-12-11 08:43 UTC, naturetime10 commented on core/service/authorizer.go
> +func (a Authorizer) createUserGroupAndAssignPermissions(
Is this API needed?

2022-12-11 08:43 UTC, naturetime10 commented on core/service/authorizer.go
> +func (a Authorizer) assignUserGroupPermissions(
Is this API needed?

2022-12-11 23:37 UTC, yijia-cc commented on core/service/authorizer.go
> +func (a Authorizer) createUserGroupAndAssignPermissions(
When create a user group, assigning permission to the group creator should always be needed, so it's better to bind the group creation and permission assignment together.

2022-12-11 23:38 UTC, yijia-cc commented on core/service/authorizer.go
> +func (a Authorizer) createUserGroupAndAssignPermissions(
But the API signature can be changed because the resourceID might be different. I changed to use a struct which groups ResourceType, Operation and ResourceID together.

2022-12-11 23:39 UTC, yijia-cc commented on core/service/authorizer.go
> +func (a Authorizer) assignUserGroupPermissions(
It will be needed for assigning a list of permissions in a batch. I changed the signature to use a struct which groups ResourceType, Operation and ResourceID together.

2022-12-12 01:58 UTC, naturetime10 approved these changes

2022-12-12 01:58 UTC, naturetime10 commented on core/service/team.go
> +
```suggestion
```

2022-12-12 02:08 UTC, merged