Set up realtime event transactions
teamyapp/teamy-backend pull request #311
Opened 2022-12-11 16:23 UTC by duanxianbo

2022-12-12 02:01 UTC, naturetime10 requested changes

2022-12-12 02:01 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +func (c *ClientNotifier) processMutations(ct context.Context, mutations []Mutation) {
```suggestion
func (c *ClientNotifier) processTransaction(ct context.Context, transaction []Transaction) {
```

2022-12-21 06:58 UTC, naturetime10 requested changes

2022-12-21 06:58 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +}
Is this still needed?

2022-12-21 06:58 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +
```suggestion
```

2022-12-21 06:58 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +		}
Let use `if mutation.CollectionType == TeamMemberCollectionType` with switch case on `mutation.MutationType` inside.

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	transaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, teamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, teamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	err = m.deps.invitationSyncer.CreateAndSyncInvitation(ct, *transaction, invitation)
```suggestion
	err = m.deps.invitationSyncer.CreateAndSyncInvitation(ct, transaction, invitation)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	err = m.deps.invitationSyncer.UpdateAndSyncInvitation(ct, *transaction, invitation)
```suggestion
	err = m.deps.invitationSyncer.UpdateAndSyncInvitation(ct, transaction, invitation)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	err = m.deps.invitationSyncer.DeleteAndSyncInvitation(ct, *transaction, invitationID)
```suggestion
	err = m.deps.invitationSyncer.DeleteAndSyncInvitation(ct, transaction, invitationID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	err = m.deps.stateSyncer.ProcessTransaction(ct, transaction)
```suggestion
	err = m.deps.stateSyncer.ProcessTransaction(ct, realTimeTransaction)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	transaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, invitation.TeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, invitation.TeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	err = m.deps.stateSyncer.ProcessTransaction(ct, transaction)
```suggestion
	err = m.deps.stateSyncer.ProcessTransaction(ct, realTimeTransaction)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	err = m.deps.invitationSyncer.UpdateAndSyncInvitation(ct, *transaction, invitation)
```suggestion
	err = m.deps.invitationSyncer.UpdateAndSyncInvitation(ct, transaction, invitation)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	transaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, invitation.TeamID)
It seems that `NewTransaction` has many dependencies. I wonder whether we can move it onto `m.deps.stateSyncer` instead to cleaner API.

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	err = m.deps.invitationSyncer.UpdateAndSyncInvitation(ct, *transaction, invitation)
```suggestion
	err = m.deps.invitationSyncer.UpdateAndSyncInvitation(ct, transaction, invitation)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	transaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, invitation.TeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, invitation.TeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/message_mutation.go
> +	transaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/message_mutation.go
> +	err = m.deps.messageSyncer.CreateAndSyncMessage(ct, *transaction, message)
```suggestion
	err = m.deps.messageSyncer.CreateAndSyncMessage(ct, transaction, message)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/message_mutation.go
> +	err = m.deps.messageSyncer.UpdateAndSyncMessage(ct, *transaction, message)
```suggestion
	err = m.deps.messageSyncer.UpdateAndSyncMessage(ct, transaction, message)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/message_mutation.go
> +	transaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/message_mutation.go
> +	transaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/message_mutation.go
> +	err = m.deps.messageSyncer.DeleteAndSyncMessage(ct, *transaction, messageID)
```suggestion
	err = m.deps.messageSyncer.DeleteAndSyncMessage(ct, transaction, messageID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/user_mutation.go
> +	err = m.deps.userDao.UpdateUser(ct, user)
I think this is the issue you were talking about. I am thinking of introducing `UserTransaction` and `TeamTransaction` to deal with this.

2022-12-21 06:58 UTC, naturetime10 commented on core/api/gql/user_mutation.go
> +	}
This issue could be solved using `UserTransactions`. Maybe we can have a type on transaction to indicate whether it's per user, per team or per client. Need further discussion.

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/invitation_syncer.go
> +func (i InvitationSyncer) CreateAndSyncInvitation(ct context.Context, tx realtime.Transaction, invitation entity.Invitation) error {
```suggestion
func (i InvitationSyncer) CreateAndSyncInvitation(ct context.Context, tx *realtime.Transaction, invitation entity.Invitation) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/invitation_syncer.go
> +func (i InvitationSyncer) UpdateAndSyncInvitation(ct context.Context, tx realtime.Transaction, invitation entity.Invitation) error {
```suggestion
func (i InvitationSyncer) UpdateAndSyncInvitation(ct context.Context, tx *realtime.Transaction, invitation entity.Invitation) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/invitation_syncer.go
> +func (i InvitationSyncer) DeleteAndSyncInvitation(ct context.Context, tx realtime.Transaction, invitationID uint64) error {
```suggestion
func (i InvitationSyncer) DeleteAndSyncInvitation(ct context.Context, tx *realtime.Transaction, invitationID uint64) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/message_syncer.go
> +func (m MessageSyncer) CreateAndSyncMessage(ct context.Context, tx realtime.Transaction, message entity.Message) error {
```suggestion
func (m MessageSyncer) CreateAndSyncMessage(ct context.Context, tx *realtime.Transaction, message entity.Message) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/message_syncer.go
> +func (m MessageSyncer) UpdateAndSyncMessage(ct context.Context, tx realtime.Transaction, message entity.Message) error {
```suggestion
func (m MessageSyncer) UpdateAndSyncMessage(ct context.Context, tx *realtime.Transaction, message entity.Message) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/message_syncer.go
> +func (m MessageSyncer) DeleteAndSyncMessage(ct context.Context, tx realtime.Transaction, messageID uint64) error {
```suggestion
func (m MessageSyncer) DeleteAndSyncMessage(ct context.Context, tx *realtime.Transaction, messageID uint64) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/spint_participant_syncer.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/spint_participant_syncer.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/spint_participant_syncer.go
> +func (s SprintParticipantSyncer) DeleteAndSyncSprintParticipant(ct context.Context, tx realtime.Transaction, sprintID uint64, userID uint64) error {
```suggestion
func (s SprintParticipantSyncer) DeleteAndSyncSprintParticipant(
ct context.Context, 
tx *realtime.Transaction, 
sprintID uint64, 
userID uint64,
) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/sprint_task_relation_syncer.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/task_await_for_relation_syncer.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/task_await_for_relation_syncer.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/task_await_for_relation_syncer.go
> +	awaitForTaskID uint64) error {
```suggestion
	awaitForTaskID uint64,
	) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/task_syncer.go
> +func (t TaskSyncer) CreateAndSyncTask(ct context.Context, tx realtime.Transaction, task entity.Task) error {
```suggestion
func (t TaskSyncer) CreateAndSyncTask(ct context.Context, tx *realtime.Transaction, task entity.Task) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/task_syncer.go
> +func (t TaskSyncer) UpdateAndSyncTask(ct context.Context, tx realtime.Transaction, task entity.Task) error {
```suggestion
func (t TaskSyncer) UpdateAndSyncTask(ct context.Context, tx *realtime.Transaction, task entity.Task) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/task_syncer.go
> +func (t TaskSyncer) DeleteAndSyncTask(ct context.Context, tx realtime.Transaction, taskID uint64) error {
```suggestion
func (t TaskSyncer) DeleteAndSyncTask(ct context.Context, tx *realtime.Transaction, taskID uint64) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/task_syncer.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/team_member_syncer.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/team_member_syncer.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/team_member_syncer.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/team_syncer.go
> +func (t TeamSyncer) CreateAndSyncTeam(ct context.Context, tx realtime.Transaction, team entity.Team) error {
```suggestion
func (t TeamSyncer) CreateAndSyncTeam(ct context.Context, tx *realtime.Transaction, team entity.Team) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/collection/team_syncer.go
> +func (t TeamSyncer) UpdateAndSyncTeam(ct context.Context, tx realtime.Transaction, team entity.Team) error {
```suggestion
func (t TeamSyncer) UpdateAndSyncTeam(ct context.Context, tx *realtime.Transaction, team entity.Team) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +	transaction := realtime.NewTransaction(s.stateSyncer, s.dataCollector, teamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(s.stateSyncer, s.dataCollector, teamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +		err = s.sprintParticipantSyncer.CreateAndSyncSprintParticipant(ct, *transaction, participant)
```suggestion
		err = s.sprintParticipantSyncer.CreateAndSyncSprintParticipant(ct, transaction, participant)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
>  	return sp, nil
```suggestion
	}
	
	return sp, nil
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +		err = s.sprintParticipantSyncer.DeleteAndSyncSprintParticipant(ct, *transaction, sprintID, participantUserID)
```suggestion
		err = s.sprintParticipantSyncer.DeleteAndSyncSprintParticipant(ct, transaction, sprintID, participantUserID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +	transaction := realtime.NewTransaction(s.stateSyncer, s.dataCollector, sprint.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(s.stateSyncer, s.dataCollector, sprint.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +	err = s.sprintTaskRelationSyncer.CreateAndSyncSprintTaskRelation(ct, *transaction, relation)
```suggestion
	err = s.sprintTaskRelationSyncer.CreateAndSyncSprintTaskRelation(ct, transaction, relation)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +		err = s.taskSyncer.UpdateAndSyncTask(ct, *transaction, task)
```suggestion
		err = s.taskSyncer.UpdateAndSyncTask(ct, transaction, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +	err = s.tryReduceBandwidth(ct, *transaction, sprintID, task)
```suggestion
	err = s.tryReduceBandwidth(ct, transaction, sprintID, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +	err = s.tryReduceBandwidth(ct, *transaction, toSprintID, task)
```suggestion
	err = s.tryReduceBandwidth(ct, transaction, toSprintID, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +	err = s.tryIncreaseBandwidth(ct, *transaction, fromSprintID, task)
```suggestion
	err = s.tryIncreaseBandwidth(ct, transaction, fromSprintID, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +	transaction := realtime.NewTransaction(s.stateSyncer, s.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(s.stateSyncer, s.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +	err = s.sprintTaskRelationSyncer.DeleteAndSyncSprintTaskRelation(ct, *transaction, sprintID, taskID)
```suggestion
	err = s.sprintTaskRelationSyncer.DeleteAndSyncSprintTaskRelation(ct, transaction, sprintID, taskID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +		err := s.taskSyncer.UpdateAndSyncTask(ct, *transaction, task)
```suggestion
		err := s.taskSyncer.UpdateAndSyncTask(ct, transaction, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +	err = s.tryIncreaseBandwidth(ct, *transaction, sprintID, task)
```suggestion
	err = s.tryIncreaseBandwidth(ct, transaction, sprintID, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +func (s Sprint) tryReduceBandwidth(ct context.Context, tx realtime.Transaction, sprintID uint64, task entity.Task) error {
```suggestion
func (s Sprint) tryReduceBandwidth(ct context.Context, tx *realtime.Transaction, sprintID uint64, task entity.Task) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/sprint.go
> +func (s Sprint) tryIncreaseBandwidth(ct context.Context, tx realtime.Transaction, sprintID uint64, task entity.Task) error {
```suggestion
func (s Sprint) tryIncreaseBandwidth(ct context.Context, tx *realtime.Transaction, sprintID uint64, task entity.Task) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, teamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, teamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.taskSyncer.CreateAndSyncTask(ct, *transaction, task)
```suggestion
	err = t.taskSyncer.CreateAndSyncTask(ct, transaction, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.taskSyncer.UpdateAndSyncTask(ct, *transaction, task)
```suggestion
	err = t.taskSyncer.UpdateAndSyncTask(ct, transaction, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.updateUnusedBandWidth(ct, *transaction, taskID, oldEffort, input.Effort, oldOwnerID, input.OwnerUserID)
```suggestion
	err = t.updateUnusedBandWidth(ct, transaction, taskID, oldEffort, input.Effort, oldOwnerID, input.OwnerUserID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	tx realtime.Transaction,
```suggestion
	tx *realtime.Transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +func (t Task) tryIncreaseBandwidth(ct context.Context, tx realtime.Transaction, taskID uint64, oldOwnerID *uint64, oldEffort *time.Duration) error {
```suggestion
func (t Task) tryIncreaseBandwidth(
  ct context.Context, 
  tx *realtime.Transaction, 
  taskID uint64, 
  oldOwnerID *uint64, 
  oldEffort *time.Duration,
  ) error {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.taskSyncer.DeleteAndSyncTask(ct, *transaction, taskID)
```suggestion
	err = t.taskSyncer.DeleteAndSyncTask(ct, transaction, taskID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.tryIncreaseBandwidth(ct, *transaction, taskID, task.OwnerUserID, task.Effort)
```suggestion
	err = t.tryIncreaseBandwidth(ct, transaction, taskID, task.OwnerUserID, task.Effort)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +func (t Task) moveTaskToUpcoming(ct context.Context, tx realtime.Transaction, taskID uint64, autoPauseTask bool) (entity.Task, error) {
```suggestion
func (t Task) moveTaskToUpcoming(ct context.Context, tx *realtime.Transaction, taskID uint64, autoPauseTask bool) (entity.Task, error) {
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.taskSyncer.UpdateAndSyncTask(ct, *transaction, task)
```suggestion
	err = t.taskSyncer.UpdateAndSyncTask(ct, transaction, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +
```suggestion
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +		err = t.taskSyncer.UpdateAndSyncTask(ct, *transaction, inProgressTask)
```suggestion
		err = t.taskSyncer.UpdateAndSyncTask(ct, transaction, inProgressTask)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.taskSyncer.UpdateAndSyncTask(ct, *transaction, task)
```suggestion
	err = t.taskSyncer.UpdateAndSyncTask(ct, transaction, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.taskSyncer.UpdateAndSyncTask(ct, *transaction, task)
```suggestion
	err = t.taskSyncer.UpdateAndSyncTask(ct, transaction, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +			_, err = t.moveTaskToUpcoming(ct, *transaction, awaitingTaskID, false)
```suggestion
			_, err = t.moveTaskToUpcoming(ct, transaction, awaitingTaskID, false)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.taskAwaitForRelationSyncer.CreateAndSyncRelation(ct, *transaction, entity.TaskAwaitForRelation{
```suggestion
	err = t.taskAwaitForRelationSyncer.CreateAndSyncRelation(ct, transaction, entity.TaskAwaitForRelation{
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.taskSyncer.UpdateAndSyncTask(ct, *transaction, task)
```suggestion
	err = t.taskSyncer.UpdateAndSyncTask(ct, transaction, task)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	err = t.taskAwaitForRelationSyncer.DeleteAndSyncRelation(ct, *transaction, taskID, awaitForTaskId)
```suggestion
	err = t.taskAwaitForRelationSyncer.DeleteAndSyncRelation(ct, transaction, taskID, awaitForTaskId)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +		task, err = t.moveTaskToUpcoming(ct, *transaction, taskID, false)
```suggestion
		task, err = t.moveTaskToUpcoming(ct, transaction, taskID, false)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +		*transaction,
```suggestion
		transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, task.OwningTeamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +		*transaction,
```suggestion
		transaction,
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/task.go
> +	return nil
```suggestion
	}
	
	return nil
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	err = t.teamSyncer.CreateAndSyncTeam(ct, *transaction, team)
```suggestion
	err = t.teamSyncer.CreateAndSyncTeam(ct, transaction, team)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, team.ID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, team.ID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	err = t.teamMemberSyncer.CreateAndSyncTeamMember(ct, *transaction, teamMember)
```suggestion

	err = t.teamMemberSyncer.CreateAndSyncTeamMember(ct, transaction, teamMember)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, team.ID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, team.ID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, teamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, teamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	err := t.teamMemberSyncer.CreateAndSyncTeamMember(ct, *transaction, teamMember)
```suggestion
	err := t.teamMemberSyncer.CreateAndSyncTeamMember(ct, transaction, teamMember)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +		err = t.sprintParticipantSyncer.CreateAndSyncSprintParticipant(ct, *transaction, participant)
```suggestion
		err = t.sprintParticipantSyncer.CreateAndSyncSprintParticipant(ct, transaction, participant)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, teamID)
```suggestion

	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, teamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	err = t.teamMemberSyncer.DeleteAndSyncTeamMember(ct, *transaction, teamID, memberUserID)
```suggestion
	err = t.teamMemberSyncer.DeleteAndSyncTeamMember(ct, transaction, teamID, memberUserID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +		err = t.sprintParticipantSyncer.DeleteAndSyncSprintParticipant(ct, *transaction, sprint.ID, memberUserID)
```suggestion
		err = t.sprintParticipantSyncer.DeleteAndSyncSprintParticipant(ct, transaction, sprint.ID, memberUserID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	transaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, teamID)
```suggestion
	realTimeTransaction := realtime.NewTransaction(t.stateSyncer, t.dataCollector, teamID)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +	err = t.teamMemberSyncer.UpdateAndSyncTeamMember(ct, *transaction, teamMember)
```suggestion
	err = t.teamMemberSyncer.UpdateAndSyncTeamMember(ct, transaction, teamMember)
```

2022-12-21 06:58 UTC, naturetime10 commented on core/service/team.go
> +			err = t.sprintParticipantSyncer.UpdateAndSyncSprintParticipant(ct, *transaction, participant)
```suggestion
			err = t.sprintParticipantSyncer.UpdateAndSyncSprintParticipant(ct, transaction, participant)
```

2022-12-25 03:30 UTC, duanxianbo commented on core/realtime/state_syncer.go
> +}
moved it to transaction.AddMutation

2022-12-26 01:33 UTC, naturetime10 requested changes

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_invitation_mutation.go
> +package mutation
Can we move this package under `core` directly? It's more than just real time sync.

2022-12-26 01:33 UTC, naturetime10 commented on core/collection/user_syncer.go
>  package collection
Should this file be removed completely?

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_invitation_mutation.go
> +	stateSyncer   *realtime.StateSyncer
Let's put `stateSyncer`, `dataCollector` and `invitationDao` at the top.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/transaction.go
> +	dataCollector  obs.DataCollector
Let's put `dataCollector` at the top.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/transaction.go
> +	dataCollector          obs.DataCollector
Let's put `stateSyncer` and `dataCollector` at the top.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/transaction.go
> +func (c *Transaction) logMutation(ct context.Context, mutation Mutation) {
It seems that we only using this helper in 1 place and we don't need to define this extra helper. Also, when possible, We should try to avoid using `json.Marshal(mutation)` during logging because it's going to consume extra CPU without real benefits.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/transaction.go
> +
```suggestion
```

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/transaction.go
> +				clientTransactions[clientID] = NewClientTransaction(t.stateSyncer.NextClientTransactionID(), clientNotifier.dataCollector, clientNotifier)
Can we define a variable for `stateSyncer.NextClientTransactionID()` for shorter code at line 108.

2022-12-26 01:33 UTC, naturetime10 commented on core/service/sprint.go
> +	stateSyncer           *realtime.StateSyncer
Let's put `stateSyncer` before authorizer to separate share dependencies and per business logic group dependencies.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +	transactionMessage := TransactionMessage{
I rethought about this. Can we put `
mutationMessages := collect.Map(clientTransaction.mutations, func(mutation Mutation, _ int) MutationMessage {
		return mutation.ToMessage()
	})

	transactionMessage := TransactionMessage{
` inside `ClientTransaction` struct's `toMessage` method?

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_invitation_mutation.go
> +	dataCollector obs.DataCollector) *CreateInvitationMutation {
Let's put dependencies before specialize input parameter (teamID, invitation).

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_team_member_muation.go
> +	return nil
Let's first create team member before subscribing to the team. Based on the current implementation, we don't know whether the team member has been successfully created when subscribing.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_invitation_mutation.go
> +	teamID        uint64
```suggestion
```
Use the team ID on invitation instead.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_invitation_mutation.go
> +	teamID uint64,
```suggestion
```

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_message_mutation.go
> +	teamID        uint64
```suggestion
```

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_message_mutation.go
> +		teamID:        teamID,
```suggestion
```

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_message_mutation.go
> +	teamID uint64,
```suggestion
```

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_message_mutation.go
> +	teamID        uint64
Query task which is related to the message based on thread ID. Then find all owning teams. For all those teams, find client notifiers and dedup.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_sprint_participant_mutation.go
> +	return c.stateSyncer.GetClientNotifiersByTeamID(ct, c.teamID)
Query the sprint for the participant. Then get the team ID from the sprint for client notifiers.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_sprint_task_relation_mutation.go
> +	err := c.sprintTaskRelationDao.CreateSprintTaskRelation(ct, c.sprintTaskRelation)
Query the sprint for the based on the relation. Then get the team ID from the sprint for client notifiers.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_task_await_for_relation_mutation.go
> +	return c.stateSyncer.GetClientNotifiersByTeamID(ct, c.teamID)
Use the team ID from the task and the team ID from the task which is waiting for this task.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/create_task_mutation.go
> +	return c.stateSyncer.GetClientNotifiersByTeamID(ct, c.teamID)
Use the team ID from the task.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/delete_message_mutation.go
> +	return d.stateSyncer.GetClientNotifiersByTeamID(ct, d.teamID)
Message(ThreadID)->Task(ThreadID,TeamID)

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/delete_sprint_participant_mutation.go
> +	return d.stateSyncer.GetClientNotifiersByTeamID(ct, d.teamID)
SprintParticipant(SprintID)->Sprint(TeamID)

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/delete_sprint_task_relation_mutation.go
> +	return d.stateSyncer.GetClientNotifiersByTeamID(ct, d.teamID)
Relation(SprintID) ->Sprint(TeamID)

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/delete_task_await_for_relation_mutation.go
> +	return d.stateSyncer.GetClientNotifiersByTeamID(ct, d.teamID)
Relation(wait for TaskID, waiting TaskID) -> Task (TeamID)

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/delete_task_mutation.go
> +	return d.stateSyncer.GetClientNotifiersByTeamID(ct, d.teamID)
TaskID -> Task(TeamID)

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_invitation_mutation.go
> +	return u.stateSyncer.GetClientNotifiersByTeamID(ct, u.teamID)
Invitation(TeamID)

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_message_mutation.go
> +	return u.stateSyncer.GetClientNotifiersByTeamID(ct, u.teamID)
Message(ThreadID) -> Task(ThreadID,TeamID)

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_sprint_participant_mutation.go
> +	return u.stateSyncer.GetClientNotifiersByTeamID(ct, u.teamID)
SprintParticipant(SprintID) -> Sprint(TeamID)

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_task_activity_mutation.go
> +	return u.stateSyncer.GetClientNotifiersByTeamID(ct, u.teamID)
Use TeamID from taskActivity.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_task_mutation.go
> +	return u.stateSyncer.GetClientNotifiersByTeamID(ct, u.teamID)
TeamID from task

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_team_member_muation.go
> +	return u.stateSyncer.GetClientNotifiersByTeamID(ct, u.teamID)
TeamID from teamMember

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_team_mutation.go
> +	return u.stateSyncer.GetClientNotifiersByTeamID(ct, u.teamID)
TeamID from team

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_user_mutation.go
> +		clientNotifiers = append(clientNotifiers, teamClientNotifiers...)
```suggestion
		}
		
		clientNotifiers = append(clientNotifiers, teamClientNotifiers...)
```

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_user_mutation.go
> +	}
Get Client Notifier by user ID also.

2022-12-26 01:33 UTC, naturetime10 commented on core/realtime/mutation/update_user_mutation.go
> +	clientNotifiers := make([]*realtime.ClientNotifier, 0)
Dedup client notifiers because an user can be in multiple teams.

2022-12-26 15:19 UTC, duanxianbo commented on core/collection/user_syncer.go
>  package collection
it is removed

2022-12-27 00:51 UTC, duanxianbo commented on core/realtime/transaction.go
> +func (c *Transaction) logMutation(ct context.Context, mutation Mutation) {
what is the best way to do here? we still need to log all the fileds in mutation?

2022-12-27 13:35 UTC, duanxianbo commented on core/realtime/mutation/create_task_await_for_relation_mutation.go
> +	return c.stateSyncer.GetClientNotifiersByTeamID(ct, c.teamID)
we could get just one of them, right?

2022-12-27 13:40 UTC, duanxianbo commented on core/api/gql/invitation_mutation.go
> +	transaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector, invitation.TeamID)
now it has only two

2022-12-28 10:05 UTC, naturetime10 requested changes

2022-12-28 10:05 UTC, naturetime10 commented on core/api/gql/deps.go
> +		taskAwaitForRelationDao: taskAwaitForRelationDao,
```suggestion
		taskAwaitForRelationDao: taskAwaitForRelationDao,
		activityCache:           activityCache,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +	dataCollector  obs.DataCollector
```suggestion
	dataCollector  obs.DataCollector
	id             uint64
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +	c.clientNotifier.notifyTransaction(ct, *c)
```suggestion
	c.clientNotifier.notifyTransaction(ct, c)
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +
```suggestion
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +	stateSyncer            *StateSyncer
```suggestion
        dataCollector          obs.DataCollector
	stateSyncer            *StateSyncer
	id                     uint64
	mutations              []Mutation
	processedMutationIndex int
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +
```suggestion
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +		stateSyncer:            stateSyncer,
```suggestion
                 dataCollector:          dataCollector,
		stateSyncer:            stateSyncer,
		id:                     stateSyncer.NextTransactionID(),
		mutations:              make([]Mutation, 0),
		processedMutationIndex: 0,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +func NewTransaction(stateSyncer *StateSyncer, dataCollector obs.DataCollector) *Transaction {
```suggestion
func NewTransaction(dataCollector obs.DataCollector, stateSyncer *StateSyncer) *Transaction {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +func NewClientTransaction(id uint64, dataCollector obs.DataCollector, clientNotifier *ClientNotifier) *ClientTransaction {
```suggestion
func newClientTransaction(dataCollector obs.DataCollector, clientNotifier *ClientNotifier, id uint64) *ClientTransaction {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +		clientNotifier: clientNotifier,
```suggestion
		dataCollector:  dataCollector,
		clientNotifier: clientNotifier,
		id:             id,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +		clientNotifier: clientNotifier,
```suggestion
		dataCollector:  dataCollector,
		clientNotifier: clientNotifier,
		id:             id,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/client_notifier.go
> +func (c *ClientNotifier) notifyTransaction(ct context.Context, clientTransaction ClientTransaction) {
```suggestion
func (c *ClientNotifier) notifyTransaction(ct context.Context, clientTransaction *ClientTransaction) {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	mutationID := s.nextMutationID
Should be protected by mutex to prevent data race.

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	transactionID := s.nextTransactionID
Should be protected by mutex to prevent data race.

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	clientTransactionID := s.nextClientTransactionID
Should be protected by mutex to prevent data race.

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +		return []*ClientNotifier{}, err
```suggestion
		return nil, err
```

2022-12-28 10:05 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	clientNotifiers := make([]*ClientNotifier, 0)
Add a comment: There can be only 1 user client for a given team on a given device.

2022-12-28 10:05 UTC, naturetime10 commented on core/collection/user_syncer.go
>  package collection
Didn't see the file is removed in this PR. Can you push the latest changes?

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_invitation_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
	dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	invitationDao dao.Invitation
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_invitation_mutation.go
> +	dataCollector obs.DataCollector,
```suggestion
	dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	invitationDao dao.Invitation,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_invitation_mutation.go
> +	invitation entity.Invitation) *CreateInvitationMutation {
```suggestion
	invitation entity.Invitation,
) *CreateInvitationMutation {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_invitation_mutation.go
> +		dataCollector: dataCollector,
```suggestion
		dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		invitationDao: invitationDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_message_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
	dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	messageDao    dao.Message
	taskDao       dao.Task
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_message_mutation.go
> +		dataCollector: dataCollector,
```suggestion
		dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		messageDao:    messageDao,
		taskDao:       taskDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_sprint_participant_mutation.go
> +	dataCollector        obs.DataCollector
```suggestion
	dataCollector        obs.DataCollector
	stateSyncer          *realtime.StateSyncer
	sprintParticipantDao dao.SprintParticipant
	sprintDao            dao.Sprint
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_sprint_participant_mutation.go
> +	sprintParticipant entity.SprintParticipant) *CreateSprintParticipantMutation {
```suggestion
func NewCreateSprintParticipantMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	sprintParticipantDao dao.SprintParticipant,
	sprintDao dao.Sprint,
	sprintParticipant entity.SprintParticipant,
) *CreateSprintParticipantMutation {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_sprint_participant_mutation.go
> +		dataCollector:        dataCollector,
```suggestion
		dataCollector:        dataCollector,
		stateSyncer:          stateSyncer,
		sprintParticipantDao: sprintParticipantDao,
		sprintDao:            sprintDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_sprint_task_relation_mutation.go
> +	dataCollector         obs.DataCollector
```suggestion
	dataCollector         obs.DataCollector
	stateSyncer           *realtime.StateSyncer
	sprintTaskRelationDao dao.SprintTaskRelation
	sprintDao             dao.Sprint
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_sprint_task_relation_mutation.go
> +	}
```suggestion
func NewCreateSprintTaskRelationMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	sprintTaskRelationDao dao.SprintTaskRelation,
	sprintDao dao.Sprint,
	sprintTaskRelation entity.SprintTaskRelation,
) *CreateSprintTaskRelationMutation {
	return &CreateSprintTaskRelationMutation{
		stateSyncer:           stateSyncer,
		sprintTaskRelationDao: sprintTaskRelationDao,
		sprintDao:             sprintDao,
		dataCollector:         dataCollector,
		id:                    stateSyncer.NextMutationID(),
		sprintTaskRelation:    sprintTaskRelation,
	}
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_task_await_for_relation_mutation.go
> +	dataCollector           obs.DataCollector
```suggestion
	dataCollector           obs.DataCollector
	stateSyncer             *realtime.StateSyncer
	taskAwaitForRelationDao dao.TaskAwaitForRelation
	taskDao                 dao.Task
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_task_await_for_relation_mutation.go
> +	}
```suggestion
func NewCreateTaskAwaitForRelationMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	taskAwaitForRelationDao dao.TaskAwaitForRelation,
	taskDao dao.Task,
	taskAwaitForRelation entity.TaskAwaitForRelation,
) *CreateTaskAwaitForRelationMutation {
	return &CreateTaskAwaitForRelationMutation{
	        dataCollector:           dataCollector,
		stateSyncer:             stateSyncer,
		taskAwaitForRelationDao: taskAwaitForRelationDao,
		taskDao:                 taskDao,	
		id:                      stateSyncer.NextMutationID(),
		taskAwaitForRelation:    taskAwaitForRelation,
	}
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_task_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
	dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	taskDao       dao.Task
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_task_mutation.go
> +	task entity.Task) *CreateTaskMutation {
```suggestion
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	taskDao dao.Task,
	task entity.Task,
) *CreateTaskMutation {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_task_mutation.go
> +		dataCollector: dataCollector,
```suggestion
                dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		taskDao:       taskDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_task_mutation.go
> +		dataCollector: dataCollector,
```suggestion
                dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		taskDao:       taskDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_team_member_muation.go
> +	dataCollector obs.DataCollector
```suggestion
	dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	teamMemberDao dao.TeamMember
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_team_member_muation.go
> +		teamMember:    teamMember,
```suggestion
func NewCreateTeamMemberMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	teamMemberDao dao.TeamMember,
	teamMember entity.TeamMember,
) *CreateTeamMemberMutation {
	return &CreateTeamMemberMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		teamMemberDao: teamMemberDao,
		id:            stateSyncer.NextMutationID(),
		teamMember:    teamMember,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_team_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
	dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	teamDao       dao.Team
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/create_team_mutation.go
> +		dataCollector: dataCollector,
```suggestion
func NewCreateTeamMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	teamDao dao.Team,
	team entity.Team,
) *CreateTeamMutation {
	return &CreateTeamMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		teamDao:       teamDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_invitation_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
	dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	invitationDao dao.Invitation
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_invitation_mutation.go
> +	invitation entity.Invitation) *DeleteInvitationMutation {
```suggestion
func NewDeleteInvitationMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	invitationDao dao.Invitation,
	invitation entity.Invitation,
) *DeleteInvitationMutation {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_invitation_mutation.go
> +	invitation entity.Invitation) *DeleteInvitationMutation {
```suggestion
func NewDeleteInvitationMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	invitationDao dao.Invitation,
	invitation entity.Invitation,
) *DeleteInvitationMutation {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_invitation_mutation.go
> +		dataCollector: dataCollector,
```suggestion
	return &DeleteInvitationMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		invitationDao: invitationDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_invitation_mutation.go
> +		dataCollector: dataCollector,
```suggestion
	return &DeleteInvitationMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		invitationDao: invitationDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_message_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
        dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	message       entity.Message
	messageDao    dao.Message
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_message_mutation.go
> +	message entity.Message) *DeleteMessageMutation {
```suggestion
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	messageDao dao.Message,
	taskDao dao.Task,
	message entity.Message,
) *DeleteMessageMutation {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_message_mutation.go
> +	message entity.Message) *DeleteMessageMutation {
```suggestion
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	messageDao dao.Message,
	taskDao dao.Task,
	message entity.Message,
) *DeleteMessageMutation {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_message_mutation.go
> +		dataCollector: dataCollector,
```suggestion
		dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		messageDao:    messageDao,
		taskDao:       taskDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_message_mutation.go
> +		dataCollector: dataCollector,
```suggestion
		dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		messageDao:    messageDao,
		taskDao:       taskDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_sprint_participant_mutation.go
> +	dataCollector        obs.DataCollector
```suggestion
	dataCollector        obs.DataCollector
	stateSyncer          *realtime.StateSyncer
	sprintParticipantDao dao.SprintParticipant
	sprintDao            dao.Sprint
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_sprint_participant_mutation.go
> +		dataCollector:        dataCollector,
```suggestion
func NewDeleteSprintParticipantMutation(
	dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	sprintParticipantDao dao.SprintParticipant,
	sprintDao dao.Sprint,
	userID uint64,
	sprintID uint64,
) *DeleteSprintParticipantMutation {
	return &DeleteSprintParticipantMutation{
		dataCollector:        dataCollector,
		stateSyncer:          stateSyncer,
		sprintParticipantDao: sprintParticipantDao,
		sprintDao:            sprintDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_sprint_task_relation_mutation.go
> +	dataCollector         obs.DataCollector
```suggestion
	dataCollector         obs.DataCollector
	stateSyncer           *realtime.StateSyncer
	sprintTaskRelationDao dao.SprintTaskRelation
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_sprint_task_relation_mutation.go
> +	task entity.Task) *DeleteSprintTaskRelationMutation {
```suggestion
func NewDeleteSprintTaskRelationMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	sprintTaskRelationDao dao.SprintTaskRelation,
	sprintID uint64,
	task entity.Task,
) *DeleteSprintTaskRelationMutation {
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_sprint_task_relation_mutation.go
> +		dataCollector:         dataCollector,
```suggestion
                dataCollector:         dataCollector,
		stateSyncer:           stateSyncer,
		sprintTaskRelationDao: sprintTaskRelationDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_task_await_for_relation_mutation.go
> +	dataCollector           obs.DataCollector
```suggestion
        dataCollector           obs.DataCollector
	stateSyncer             *realtime.StateSyncer
	taskAwaitForRelationDao dao.TaskAwaitForRelation
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_task_await_for_relation_mutation.go
> +		dataCollector:           dataCollector,
```suggestion
func NewDeleteTaskAwaitForRelationMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	taskAwaitForRelationDao dao.TaskAwaitForRelation,
	awaitingTask entity.Task,
	awaitForTaskID uint64,
) *DeleteTaskAwaitForRelationMutation {
	return &DeleteTaskAwaitForRelationMutation{
	        dataCollector:           dataCollector,
		stateSyncer:             stateSyncer,
		taskAwaitForRelationDao: taskAwaitForRelationDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_task_await_for_relation_mutation.go
> +		dataCollector:           dataCollector,
```suggestion
func NewDeleteTaskAwaitForRelationMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	taskAwaitForRelationDao dao.TaskAwaitForRelation,
	awaitingTask entity.Task,
	awaitForTaskID uint64,
) *DeleteTaskAwaitForRelationMutation {
	return &DeleteTaskAwaitForRelationMutation{
	        dataCollector:           dataCollector,
		stateSyncer:             stateSyncer,
		taskAwaitForRelationDao: taskAwaitForRelationDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_task_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
        dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	taskDao       dao.Task
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_task_mutation.go
> +		dataCollector: dataCollector,
```suggestion
func NewDeleteTaskMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	taskDao dao.Task,
	task entity.Task,
) *DeleteTaskMutation {
	return &DeleteTaskMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		taskDao:       taskDao,	
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_team_member_muation.go
> +	dataCollector obs.DataCollector
```suggestion
        dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	teamMemberDao dao.TeamMember
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_team_member_muation.go
> +	teamNotifier.UnregisterUserNotifier(d.userID)
The user won't be notified for being removed out of the team. I think we need to add a `CleanUp` method to mutation and unsubscribe from the team in this method. This method will be invoked after all `GetClientNotifiers` methods are invoked in the transaction.

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/delete_team_member_muation.go
> +		dataCollector: dataCollector,
```suggestion
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	teamMemberDao dao.TeamMember,
	teamID uint64,
	userID uint64,
) *DeleteTeamMemberMutation {
	return &DeleteTeamMemberMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		teamMemberDao: teamMemberDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_invitation_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
	dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	invitationDao dao.Invitation
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_invitation_mutation.go
> +		dataCollector: dataCollector,
```suggestion
func NewUpdateInvitationMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	invitationDao dao.Invitation,
	invitation entity.Invitation,
) *UpdateInvitationMutation {
	return &UpdateInvitationMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		invitationDao: invitationDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_message_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
        dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	messageDao    dao.Message
	taskDao       dao.Task
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_message_mutation.go
> +		dataCollector: dataCollector,
```suggestion
func NewUpdateMessageMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	messageDao dao.Message,
	taskDao dao.Task,
	message entity.Message,
) *UpdateMessageMutation {
	return &UpdateMessageMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		messageDao:    messageDao,
		taskDao:       taskDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_sprint_participant_mutation.go
> +	dataCollector        obs.DataCollector
```suggestion
        dataCollector        obs.DataCollector
	stateSyncer          *realtime.StateSyncer
	sprintParticipantDao dao.SprintParticipant
	sprintDao            dao.Sprint
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_sprint_participant_mutation.go
> +		dataCollector:        dataCollector,
```suggestion
func NewUpdateSprintParticipantMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	sprintParticipantDao dao.SprintParticipant,
	sprintDao dao.Sprint,
	sprintParticipant entity.SprintParticipant,
) *UpdateSprintParticipantMutation {
	return &UpdateSprintParticipantMutation{
	        dataCollector:        dataCollector,
		stateSyncer:          stateSyncer,
		sprintParticipantDao: sprintParticipantDao,
		sprintDao:            sprintDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_task_activity_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
        dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	activityCache cache.Activity
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_task_activity_mutation.go
> +		dataCollector: dataCollector,
```suggestion
func NewUpdateTaskActivityMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	activityCache cache.Activity,
	taskActivity entity.TaskActivity,
) *UpdateTaskActivityMutation {
	return &UpdateTaskActivityMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		activityCache: activityCache,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_task_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
        dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	taskDao       dao.Task
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_task_mutation.go
> +		dataCollector: dataCollector,
```suggestion
func NewUpdateTaskMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	taskDao dao.Task,
	task entity.Task,
) *UpdateTaskMutation {
	return &UpdateTaskMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		taskDao:       taskDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_team_member_muation.go
> +	dataCollector obs.DataCollector
```suggestion
        dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	teamMemberDao dao.TeamMember
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_team_member_muation.go
> +		dataCollector: dataCollector,
```suggestion
func NewUpdateTeamMemberMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	teamMemberDao dao.TeamMember,
	teamMember entity.TeamMember,
) *UpdateTeamMemberMutation {
	return &UpdateTeamMemberMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		teamMemberDao: teamMemberDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_team_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
        dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	teamDao       dao.Team
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_team_mutation.go
> +		dataCollector: dataCollector,
```suggestion
func NewUpdateTeamMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	teamDao dao.Team,
	team entity.Team,
) *UpdateTeamMutation {
	return &UpdateTeamMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		teamDao:       teamDao,	
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_user_mutation.go
> +	dataCollector obs.DataCollector
```suggestion
        dataCollector obs.DataCollector
	stateSyncer   *realtime.StateSyncer
	teamMemberDao dao.TeamMember
	userDao       dao.User
```

2022-12-28 10:05 UTC, naturetime10 commented on core/mutation/update_user_mutation.go
> +		dataCollector: dataCollector,
```suggestion
func NewUpdateUserMutation(
        dataCollector obs.DataCollector,
	stateSyncer *realtime.StateSyncer,
	teamMemberDao dao.TeamMember,
	userDao dao.User,
	user entity.User,
) *UpdateUserMutation {
	return &UpdateUserMutation{
	        dataCollector: dataCollector,
		stateSyncer:   stateSyncer,
		teamMemberDao: teamMemberDao,
		userDao:       userDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/service/sprint.go
> +
```suggestion
```

2022-12-28 10:05 UTC, naturetime10 commented on core/service/sprint.go
> +			s.dataCollector,
```suggestion
			s.dataCollector,
			s.stateSyncer,
			s.sprintParticipantDao,
			s.sprintDao,
```

2022-12-28 10:05 UTC, naturetime10 commented on core/service/sprint.go
>  	return sp, nil
```suggestion
	if err != nil {
		s.dataCollector.Logger.LogWithContext(ct, obs.Error, obs.Props{obs.CauseProp: err})
		return entity.Sprint{}, err
	}
	
	return sp, nil
```

2022-12-28 10:05 UTC, naturetime10 commented on core/service/sprint.go
> +	err = realTimeTransaction.Commit(ct)
```suggestion
	}
	
	err = realTimeTransaction.Commit(ct)
```

2022-12-28 10:05 UTC, naturetime10 commented on core/service/sprint.go
> +	err = realTimeTransaction.Commit(ct)
Create and use delete sprint mutation at line 254 so that the sprint can disappear from the team.

2022-12-28 10:05 UTC, naturetime10 commented on core/service/sprint.go
> +	realTimeTransaction := realtime.NewTransaction(s.stateSyncer, s.dataCollector)
```suggestion

	realTimeTransaction := realtime.NewTransaction(s.stateSyncer, s.dataCollector)
```

2022-12-28 10:05 UTC, naturetime10 commented on core/service/team.go
> +	stateSyncer                *realtime.StateSyncer
Let's put `stateSyncer` after authorizer and before the DAOs

2022-12-28 10:05 UTC, naturetime10 commented on core/service/team.go
> +	stateSyncer *realtime.StateSyncer,
Let's put `stateSyncer` after `authorizer`.

2022-12-28 10:05 UTC, naturetime10 commented on core/service/team.go
> +		stateSyncer:                stateSyncer,
Let's put `stateSyncer` after `authorizer`.

2022-12-28 10:05 UTC, naturetime10 commented on core/api/gql/user_mutation.go
> +	err = realTimeTransaction.Commit(ct)
Can we add a TODO to move business logic to user service?

2022-12-28 10:05 UTC, naturetime10 commented on core/api/gql/message_mutation.go
> +	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector)
Can we add a TODO to move business logic to message service?

2022-12-28 10:05 UTC, naturetime10 commented on core/api/gql/message_mutation.go
> +	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector)
Can we add a TODO to move business logic to message service?

2022-12-28 10:05 UTC, naturetime10 commented on core/api/gql/message_mutation.go
> +	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector)
Can we add a TODO to move business logic to message service?

2022-12-28 10:05 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector)
Can we add a TODO to move business logic to invitation service?

2022-12-28 10:05 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector)
Can we add a TODO to move business logic to invitation service?

2022-12-28 10:05 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector)
Can we add a TODO to move business logic to invitation service?

2022-12-28 10:05 UTC, naturetime10 commented on core/api/gql/invitation_mutation.go
> +	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector)
Can we add a TODO to move business logic to invitation service?

2022-12-28 10:05 UTC, naturetime10 commented on core/dep/wire.go
> +	stateSyncer *realtime.StateSyncer,
Can we move `stateSyncer` after `authorizer`?

2022-12-28 10:05 UTC, naturetime10 commented on core/dep/wire.go
> +		stateSyncer)
Can we move `stateSyncer` after `authorizer`?

2022-12-30 01:36 UTC, duanxianbo commented on core/realtime/state_syncer.go
> +	mutationID := s.nextMutationID
should we also add a mutex for clientID?

2022-12-30 01:57 UTC, duanxianbo commented on core/api/gql/invitation_mutation.go
> +	realTimeTransaction := realtime.NewTransaction(m.deps.stateSyncer, m.deps.dataCollector)
rebased master and moved it to transaction service

2022-12-30 02:44 UTC, duanxianbo commented on core/mutation/delete_team_member_muation.go
> +	teamNotifier.UnregisterUserNotifier(d.userID)
I am not sure I understand this comment

2022-12-30 02:44 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	mutationID := s.nextMutationID
@duanxianbo We should

2022-12-30 02:46 UTC, duanxianbo commented on core/realtime/state_syncer.go
> +	mutationID := s.nextMutationID
done

2022-12-30 09:05 UTC, naturetime10 requested changes

2022-12-30 09:05 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	clientNotifier := newClientNotifier(s.dataCollector, conn, nextClientID)
```suggestion
	s.clientIDMut.Unlock()
	
	clientNotifier := newClientNotifier(s.dataCollector, conn, nextClientID)
```

2022-12-30 09:05 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +
```suggestion
```

2022-12-30 09:05 UTC, naturetime10 commented on core/realtime/transaction.go
> +			if !ok {
```suggestion
			if !ok {
			    clientTransactionID := t.stateSyncer.NextClientTransactionID()
```

2022-12-30 09:05 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +func (s *StateSyncer) GetClientNotifiersByUserID(ct context.Context, userID uint64) ([]*ClientNotifier, error) {
```suggestion
func (s *StateSyncer) GetAllClientNotifiersByUserID(ct context.Context, userID uint64) ([]*ClientNotifier, error) {
```

2022-12-30 09:05 UTC, naturetime10 commented on core/mutation/create_message_mutation.go
> +	message entity.Message) *CreateMessageMutation {
```suggestion
	message entity.Message,
) *CreateMessageMutation {
```

2022-12-30 09:05 UTC, naturetime10 commented on core/mutation/delete_team_member_muation.go
> +	teamNotifier.UnregisterUserNotifier(d.userID)
We are invoking `Execute` before invoking `GetClientNotifiers`. If we unregistered the user notifier before invoking `GetClientNotifiers`, we won't get any user notifiers or client notifiers for this team. Hence, delete notification won't be sent to the client. Instead, we should not `UnregisterUserNotifier` in Execute. We should add a `CleanUp` function which is invoked after invoking `GetClientNotifiers` so that the delete notification can still be sent to client, removing the user out of the team across multiple user clients.

2022-12-30 09:05 UTC, naturetime10 commented on core/service/invitation.go
> +
```suggestion
```

2022-12-30 09:05 UTC, naturetime10 commented on core/service/task.go
> +	stateSyncer             *realtime.StateSyncer
```suggestion
	dataCollector           obs.DataCollector
	cloudClientRegistry     *cloudAPI.ClientRegistry
	authorizer              Authorizer
	stateSyncer             *realtime.StateSyncer
	activityCache           cache.Activity
	taskDao                 dao.Task
	sprintDao               dao.Sprint
	threadDao               dao.Thread
	taskAwaitForRelationDao dao.TaskAwaitForRelation
	sprintParticipantDao    dao.SprintParticipant
	sprintTaskRelationDao   dao.SprintTaskRelation
	threadService           Thread
```

2022-12-30 09:05 UTC, naturetime10 commented on core/service/task.go
> +
```suggestion
```

2022-12-30 09:05 UTC, naturetime10 commented on core/service/task.go
> +	}
```suggestion
	}
	
```

2022-12-30 09:05 UTC, naturetime10 commented on core/service/task.go
> +
```suggestion
```

2022-12-30 09:05 UTC, naturetime10 commented on core/service/task.go
> +
```suggestion
```

2022-12-30 09:05 UTC, naturetime10 commented on core/service/task.go
> +	}
```suggestion
```

2022-12-30 09:05 UTC, naturetime10 commented on core/service/task.go
> +	return nil
```suggestion
	}
	
	return nil
```

2022-12-30 09:05 UTC, naturetime10 commented on core/service/task.go
> +	stateSyncer *realtime.StateSyncer,
Put `stateSyncer *realtime.StateSyncer` after `authorizer Authorizer`

2022-12-30 09:05 UTC, naturetime10 commented on core/service/task.go
> +		stateSyncer:             stateSyncer,
```suggestion
		authorizer:              authorizer,
		stateSyncer:             stateSyncer,
		activityCache:           activityCache,
		taskDao:                 taskDao,
		threadDao:               threadDao,
		taskAwaitForRelationDao: taskAwaitForRelationDao,
		sprintParticipantDao:    sprintParticipantDao,
		sprintTaskRelationDao:   sprintTaskRelationDao,
		threadService:           threadService,
```

2022-12-30 09:05 UTC, naturetime10 commented on core/api/gql/deps.go
> +	stateSyncer             *realtime.StateSyncer
```suggestion
	cloudClientRegistry     *api.ClientRegistry
	stateSyncer             *realtime.StateSyncer
	userDao                 dao.User
	teamDao                 dao.Team
	taskDao                 dao.Task
	teamMemberDao           dao.TeamMember
	invitationDao           dao.Invitation
	messageDao              dao.Message
	activityCache           cache.Activity
	taskAwaitForRelationDao dao.TaskAwaitForRelation
	taskService             service.Task
	teamService             service.Team
	sprintService           service.Sprint
	invitationService       service.Invitation
	userService             service.User
```

2022-12-30 09:05 UTC, naturetime10 commented on core/api/gql/deps.go
> +	stateSyncer *realtime.StateSyncer,
Put `stateSyncer` after `cloudClientRegistry *api.ClientRegistry,`

2022-12-30 09:05 UTC, naturetime10 commented on core/api/gql/deps.go
> +		stateSyncer:             stateSyncer,
```suggestion
		cloudClientRegistry:     cloudClientRegistry,
		stateSyncer:             stateSyncer,
		userDao:                 userDao,
		teamDao:                 teamDao,
		taskDao:                 taskDao,
		teamMemberDao:           teamMemberDao,
		invitationDao:           invitationDao,
		messageDao:              messageDao,
		taskAwaitForRelationDao: taskAwaitForRelationDao,
		activityCache:           activityCache,
		taskService:             taskService,
		teamService:             teamService,
		sprintService:           sprintService,
		userService:             userService,
		invitationService:       invitationService,
```

2022-12-31 02:27 UTC, naturetime10 approved these changes

2022-12-31 02:27 UTC, naturetime10 approved these changes

2022-12-31 02:29 UTC, merged