Add task link
teamyapp/teamy-backend pull request #323
Opened 2023-01-22 15:14 UTC by duanxianbo

2023-01-22 20:48 UTC, naturetime10 requested changes

2023-01-22 20:48 UTC, naturetime10 commented on apps/github/app.go
> +		Title:  "github",
Can this be the title of pull request?

2023-01-22 20:48 UTC, naturetime10 commented on apps/github/app.go
> +		TaskId: createTaskRes.TaskId,
Can we put `TaskId` before `Title`?

2023-01-22 20:48 UTC, naturetime10 commented on apps/github/pull_request.go
> +	Url                string           `json:"url"`
I think URL is important. Can we move it before `State`?

2023-01-22 20:48 UTC, naturetime10 commented on core/api/gql/task.go
> +func (t Task) TaskLinks(ct context.Context) ([]TaskLink, error) {
```suggestion
func (t Task) Links(ct context.Context) ([]TaskLink, error) {
```

2023-01-22 20:48 UTC, naturetime10 commented on core/api/gql/task.go
> +	taskLinks, err := t.deps.taskLinkService.FindTaskLinksByTaskID(ct, t.task.ID)
```suggestion
	links, err := t.deps.taskLinkService.FindLinksByTaskID(ct, t.task.ID)
```

2023-01-22 20:48 UTC, naturetime10 commented on core/api/proto/task_link.proto
> +
```suggestion
```

2023-01-22 20:48 UTC, naturetime10 commented on core/api/proto/task_link.proto
> +	uint64 taskLinkId = 1;
```suggestion
	uint64 linkId = 1;
```

2023-01-22 20:48 UTC, naturetime10 commented on core/dao/task_link.go
> +	FindTaskLinksByTaskID(ct context.Context, taskID uint64) ([]entity.TaskLink, error)
```suggestion
	FindLinksByTaskID(ct context.Context, taskID uint64) ([]entity.TaskLink, error)
```

2023-01-22 20:48 UTC, naturetime10 commented on core/service/task_link.go
> +	genTaskLinkIDReq := &proto.GenerateUniqueNumberRequest{SequenceName: "taskLinkID"}
Check create link permission under task?

2023-01-22 20:48 UTC, naturetime10 commented on migrations/20230116185606_create_task_links_table.sql
> +    id   VARCHAR(50) NOT NULL,
Does VARCHAR actually work? I thought task link is BIGINT and should be primary key.

2023-01-22 20:48 UTC, naturetime10 commented on migrations/20230116185606_create_task_links_table.sql
> +    title TEXT NOT NULL,
Can we use VARCHAR with length of 200 instead of text?

```
The VAR in VARCHAR means that you can set the max size to anything between 1 and 65,535. TEXT fields have a fixed max size of 65,535 characters. A VARCHAR can be part of an index whereas a TEXT field requires you to specify a prefix length, which can be part of an index.
```

2023-01-22 20:48 UTC, naturetime10 commented on migrations/20230116185606_create_task_links_table.sql
> +	url VARCHAR(200) NOT NULL,
Max length of URL is `2048` characters.

2023-01-22 20:48 UTC, naturetime10 commented on migrations/20230116185606_create_task_links_table.sql
> +    icon_url TEXT,
Max length of URL is 2048 characters.

2023-01-22 20:48 UTC, naturetime10 commented on migrations/20230116185606_create_task_links_table.sql
> +-- +migrate Up
Can we format this SQL file?

2023-01-22 21:08 UTC, naturetime10 requested changes

2023-01-22 21:08 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +type ErrTeamNotFound struct {
Can we rebase master so that this change won't show up in PR?

2023-01-23 02:33 UTC, duanxianbo commented on migrations/20230116185606_create_task_links_table.sql
> +    id   VARCHAR(50) NOT NULL,
it works, but you are right, it should be primary key and BIGINT

2023-01-23 02:39 UTC, naturetime10 requested changes

2023-01-23 02:39 UTC, naturetime10 commented on core/authorization/query.go
> +		Operation:    "CreateTaskLink",
```suggestion
		Operation:    "CreateLink",
```

2023-01-23 02:39 UTC, naturetime10 commented on core/service/task_link.go
> +	IconUrl *string
```suggestion
	URL     string
	IconURL *string
```

2023-01-23 02:39 UTC, naturetime10 commented on core/entity/task_link.go
> +	IconUrl   *string
```suggestion
	URL       string
	IconURL   *string
```

2023-01-23 02:39 UTC, naturetime10 commented on core/service/task_link.go
> +	taskLinkDao dao.TaskLink) TaskLink {
```suggestion
	taskLinkDao dao.TaskLink,
) TaskLink {
```

2023-01-23 02:40 UTC, naturetime10 approved these changes

2023-01-23 02:41 UTC, naturetime10 requested changes
This also need to updated: https://github.com/teamyapp/teamy-backend/blob/master/authorization.yml

2023-01-25 02:52 UTC, naturetime10 approved these changes

2023-01-25 02:53 UTC, merged