Update DB schema and  GraphQL APIs for 3rd party app
teamyapp/teamy-backend pull request #337
Opened 2023-01-31 04:58 UTC by Junoth

All the update follows design doc except default value of active_version_number. I think we can follow the original design to mark that field as NULL if there is no active version instead of setting 0 as default value.

https://docs.google.com/document/d/1LPBU4WjMJrpX075Bp4yJqQSjyY75x1VOWXfE2oYtEnI/edit?usp=sharing

2023-01-31 07:29 UTC, naturetime10 requested changes

2023-01-31 07:29 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	changeLog: String!
Can we rename this to `changes`? `Changelog` contains a curated, chronologically ordered list of notable changes for `each version` of a project.

2023-01-31 07:29 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	changeLog: String
Can we rename this to `changes`? `Changelog` contains a curated, chronologically ordered list of notable changes for `each version` of a project.

2023-01-31 07:29 UTC, naturetime10 commented on migrations/20230130200400_update_app_tables.sql
> +
Let's do exact reverse of migration up to ensure we can also undo the changes correct.

2023-01-31 07:29 UTC, naturetime10 commented on migrations/20230130200400_update_app_tables.sql
> +    ADD change_log TEXT,
```suggestion
    ADD changes TEXT,
```

2023-01-31 07:29 UTC, naturetime10 commented on migrations/20230130200400_update_app_tables.sql
> +	DROP COLUMN change_log,
```suggestion
	DROP COLUMN changes,
```

2023-01-31 07:53 UTC, naturetime10 requested changes

2023-01-31 07:53 UTC, naturetime10 commented on migrations/20230130200400_update_app_tables.sql
> +
```suggestion
```

2023-02-01 03:51 UTC, Junoth commented on core/api/gql/schema.graphql
> +	changeLog: String!
sure. I'll update this

2023-02-01 05:52 UTC, naturetime10 approved these changes

2023-02-01 05:54 UTC, naturetime10 commented on core/api/gql/team.go
> +func (t Team) AppTeamInstallations() ([]AppTeamInstallation, error) {
```suggestion
func (t Team) AppInstallations() ([]AppTeamInstallation, error) {
```

2023-02-01 05:54 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	appTeamInstallations: [AppTeamInstallation!]!
```suggestion
	appInstallations: [AppTeamInstallation!]!
```

2023-02-01 06:06 UTC, naturetime10 approved these changes

2023-02-01 06:13 UTC, merged