Support mentioning task in pull request description
teamyapp/teamy-backend pull request #343
Opened 2023-02-04 21:24 UTC by duanxianbo

2023-03-16 08:20 UTC, naturetime10 requested changes
Partial comments

2023-03-16 08:20 UTC, naturetime10 commented on migrations/20230315214133_create_apps_github_request_internal_task_relation_table.sql
> +	pull_request_node_id VARCHAR(20) NOT NULL REFERENCES apps_github_pull_request (github_pull_request_node_id) ON UPDATE CASCADE ON DELETE CASCADE,
```suggestion
	pull_request_node_id VARCHAR(20) NOT NULL 
	    REFERENCES apps_github_pull_request (github_pull_request_node_id) 
	    ON UPDATE CASCADE 
	    ON DELETE CASCADE,
```

2023-03-16 08:20 UTC, naturetime10 commented on migrations/20230315214133_create_apps_github_request_internal_task_relation_table.sql
> +DROP internal_task_id;
```suggestion
    DROP internal_task_id;
```

2023-03-16 08:20 UTC, naturetime10 commented on migrations/20230315214133_create_apps_github_request_internal_task_relation_table.sql
> +ADD internal_task_id BIGINT;
```suggestion
    ADD internal_task_id BIGINT;
```

2023-03-16 08:20 UTC, naturetime10 commented on migrations/20230315214133_create_apps_github_request_internal_task_relation_table.sql
> +
```suggestion
```

2023-03-16 08:20 UTC, naturetime10 commented on core/service/task_link.go
> +	deleteTaskLinkMutation := mutation.NewDeleteTaskLinkMutation(t.dataCollector, t.stateSyncer, t.taskLinkDao, t.taskDao, taskLink)
Let's put `FindTaskLinkByID` and `DeleteTaskLinkMutation` into a single transaction with this helper: https://github.com/teamyapp/teamy-backend/blob/master/core/service/task.go#L251-L291

2023-03-16 08:20 UTC, naturetime10 commented on core/mutation/delete_task_link_mutation.go
> +}
We are migrating codebase to use transaction. Let's implement v2 APIs instead:  https://github.com/teamyapp/teamy-backend/blob/master/core/mutation/create_task_mutation.go#L32-L56, https://github.com/teamyapp/teamy-backend/blob/master/core/mutation/create_task_mutation.go#L76-L78, https://github.com/teamyapp/teamy-backend/blob/master/core/mutation/create_task_mutation.go#L93-L108

2023-03-16 08:20 UTC, naturetime10 commented on core/dao/task_link.go
>  	FindLinksByTaskID(ct context.Context, taskID uint64) ([]entity.TaskLink, *errs.Error)
```suggestion
	FindTaskLinkByID(ct context.Context, taskLinkID uint64) (entity.TaskLink, *errs.Error)
	FindLinksByTaskID(ct context.Context, taskID uint64) ([]entity.TaskLink, *errs.Error)
	CreateTaskLink(ct context.Context, taskLinkEntity entity.TaskLink) *errs.Error
	DeleteTaskLink(ct context.Context, taskLinkID uint64) *errs.Error
```

2023-03-16 08:20 UTC, naturetime10 commented on core/dao/sqldb/task_link.go
Let's create V2 Dao for task link and use that instead: https://github.com/teamyapp/teamy-backend/blob/master/core/daov2/sqldb/task.go

2023-03-16 08:20 UTC, naturetime10 commented on core/api/task_link_rpc.go
> +func (t TaskLinkRPC) DeleteTaskLink(ct context.Context, in *proto.DeleteTaskLinkRequest) (*emptypb.Empty, error) {
Can we move this API below `CreateTaskLink`?

2023-03-16 08:20 UTC, naturetime10 commented on core/api/proto/task_link.proto
> +
```suggestion
```

2023-03-16 08:20 UTC, naturetime10 commented on core/api/proto/task_link.proto
> +	uint64 id = 1;
```suggestion
	uint64 linkId = 1;
```

2023-03-16 08:20 UTC, naturetime10 commented on core/api/proto/task_link.proto
> +import "google/protobuf/empty.proto";
```suggestion

import "google/protobuf/empty.proto";
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +
```suggestion
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +func (g *GraphQLAPI) mutate(
Can we put `mutate` after `query`?

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +	Title      string         `json:"title"`
```suggestion
	Number     int            `json:"number"`
	URL        string         `json:"url"`
	Repository RepositoryNode `json:"repository"`
	Title      string         `json:"title"`
	Body       string         `json:"body"`
	Author     userNode       `json:"author"`
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +type userNode struct {
```suggestion
type UserNode struct {
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +			updatePullRequest(input: $update) {
```suggestion
			updatePullRequest(input: $input) {
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +		Mutation: `mutation ($update: UpdatePullRequestInput!) {
```suggestion
		Mutation: `mutation ($input: UpdatePullRequestInput!) {
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +			"update": pullRequestUpdate,
```suggestion
			"input": pullRequestInput,
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +func (g GraphQLAPI) UpdatePullRequest(ct context.Context, installation *Installation, pullRequestUpdate UpdatePullRequestInput) (PullRequestNode, *errs.Error) {
```suggestion
func (g GraphQLAPI) UpdatePullRequest(ct context.Context, installation *Installation, pullRequestInput UpdatePullRequestInput) (PullRequestNode, *errs.Error) {
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/app_api.go
> +)
```suggestion
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/app_api.go
> +	r, err := regexp.Compile(`\(task:([\d]+)\)`)
Let's move this into a variable above AppAPI definition and invoke `regexp.MustCompile`. This regex can be compiled at startup to reduce latency.

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/app_api.go
> +				a.dataCollector.Logger.LogWithContext(ct, telemetry.Warning, telemetry.Props{
```suggestion
				a.dataCollector.Logger.WarningWithContext(ct,
```

2023-03-16 08:20 UTC, naturetime10 commented on apps/github/app_api.go
> +					telemetry.CauseProp: internalErr,
```suggestion
					internalErr.String()
```

2023-03-17 02:15 UTC, naturetime10 requested changes

2023-03-17 02:15 UTC, naturetime10 commented on apps/dao/github_pull_request_internal_task_relation.go
> +	CreatePullRequestInternalTaskRelation(ct context.Context, pullRequestInternalTaskRelation entity.GithubPullRequestInternalTaskRelation) *errs.Error
```suggestion
	CreatePullRequestInternalTaskRelation(ct context.Context, pullRequestInternalTaskRelation entity.GithubPullRequestInternalTaskRelation) *errs.Error
	DeletePullRequestInternalTaskRelationByNodeIDAndTaskID(ct context.Context, nodeID string, internalTaskID uint64) *errs.Error
```

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +		if evt.Sender.Type != "Bot" {
Can we define Sender Type as enum in entity package?

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +		} else if prEvt.PullRequest.ClosedAt != nil {
Is this check needed?

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +		for _, prTaskRelation := range prTaskRelations {
Should we delete automatically created task?

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +func (a AppAPI) tryGetValidMentionedTasks(ct context.Context, body *string) (map[uint64]*proto.TaskMsg, *errs.Error) {
```suggestion
func (a AppAPI) tryGetValidMentionedTasks(ct context.Context, body string) (map[uint64]entity.Task, *errs.Error) {
```

Let's convert `proto.TaskMsg` to internal `Task` model before consuming it in the rest of the logic.

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +		}
Can we do deleteTask outside this  function or maybe rename this method to communicate we are cleaning up automatically created tasks.

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +		}
Can this be done before line 812?

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +
```suggestion
```

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +
```suggestion
```

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +
```suggestion
```

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +
```suggestion
```

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +
```suggestion
```

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +				*pr.URL,
Does `prEvt` have URL?

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +	pullRequestNodeID string) (*uint64, *errs.Error) {
```suggestion
	pullRequestNodeID string,
) (*uint64, *errs.Error) {
```

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/app_api.go
> +	ct context.Context,
We may want to break down this method and add a small helper function to simplify the logic in this func.

2023-03-17 02:15 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +		Variables: map[string]interface{}{
Can we do something like this?
```
struct {
			Input UpdatePullRequestInput `json:"input"`
		}{
			Input: pullRequestInput,
		}
```

2023-03-17 02:15 UTC, naturetime10 commented on migrations/20230315214133_create_apps_github_request_internal_task_relation_table.sql
> +	pull_request_node_id VARCHAR(20) NOT NULL
Can we format SQL at local? Github seems have problem aligning code.

2023-03-17 02:15 UTC, naturetime10 commented on migrations/20230315214133_create_apps_github_request_internal_task_relation_table.sql
> +ON apps_github_pull_request_internal_task_relation(internal_task_id);
```suggestion
    ON apps_github_pull_request_internal_task_relation(internal_task_id);
```

2023-03-17 02:33 UTC, duanxianbo commented on apps/github/app_api.go
> +		for _, prTaskRelation := range prTaskRelations {
we are deleting automatically created task in `removePullRequestTaskRelation`

2023-03-17 02:33 UTC, duanxianbo commented on apps/github/app_api.go
> +		}
maybe RemovePullRequestTaskRelationWithTaskOrTaskLink

2023-03-17 02:33 UTC, duanxianbo commented on apps/github/client/gql_api.go
> +		Variables: map[string]interface{}{
I tried that and we can not , we can do that in query with nodeid, because nodeid is a simple string

2023-03-18 01:13 UTC, duanxianbo commented on apps/github/app_api.go
> +func (a AppAPI) tryGetValidMentionedTasks(ct context.Context, body *string) (map[uint64]*proto.TaskMsg, *errs.Error) {
open this again, why we are doing this?

2023-03-18 01:22 UTC, duanxianbo commented on apps/github/app_api.go
> +		} else if prEvt.PullRequest.ClosedAt != nil {
no

2023-03-18 01:22 UTC, duanxianbo commented on apps/github/app_api.go
> +				*pr.URL,
yes

2023-03-19 08:15 UTC, naturetime10 requested changes
Few small clean up then we are ready to check in!

2023-03-19 08:15 UTC, naturetime10 commented on apps/github/app_api.go
> +var taskIdsRegexpTester = regexp.MustCompile(`\(task:([\d]+)\)`)
```suggestion
var taskIDPattern = regexp.MustCompile(`\(task:([\d]+)\)`)
```

2023-03-19 08:15 UTC, naturetime10 commented on core/service/task_link.go
> +
```suggestion
```

2023-03-19 08:15 UTC, naturetime10 commented on core/service/task_link.go
> +
```suggestion
```

2023-03-19 08:15 UTC, naturetime10 commented on core/mutation/delete_task_link_mutation.go
> +		return err
```suggestion
		d.dataCollector.Logger.ErrorWithContext(ct, err)
		return err
```

2023-03-19 08:15 UTC, naturetime10 commented on core/mutation/create_task_link_mutation.go
> +
```suggestion
```

2023-03-19 08:15 UTC, naturetime10 commented on core/daov2/sqldb/task_link.go
> +
```suggestion
```

2023-03-19 08:15 UTC, naturetime10 commented on core/daov2/sqldb/task_link.go
> +		return internalErr
```suggestion
		return errs.NewError(errs.Unknown, err.Error())
```

2023-03-19 08:15 UTC, naturetime10 commented on core/daov2/sqldb/task_link.go
> +		return internalErr
```suggestion
		return errs.NewError(errs.Unknown, err.Error())
```

2023-03-19 08:15 UTC, naturetime10 commented on core/daov2/sqldb/task_link.go
> +		return entity.TaskLink{}, internalErr
```suggestion
		return entity.TaskLink{}, errs.NewError(errs.NotFound, fmt.Sprintf("taskLink not found: id=%v", taskLinkID))
```

2023-03-19 08:15 UTC, naturetime10 commented on core/daov2/sqldb/task_link.go
> +		return taskLink, internalErr
```suggestion
		return taskLink, errs.NewError(errs.Unknown, err.Error())
```

2023-03-19 08:15 UTC, naturetime10 commented on core/daov2/sqldb/task_link.go
> +		return nil, internalErr
```suggestion
		return nil, errs.NewError(errs.Unknown, err.Error())
```

2023-03-19 08:15 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +		Variables: map[string]interface{}{
@duanxianbo Can we have a debugging session on this?

2023-03-19 08:15 UTC, naturetime10 commented on apps/github/app_api.go
> +			err := a.RemovePullRequestTaskRelationWithTaskOrTaskLink(ct, prTaskRelation)
```suggestion
			err := a.RemovePullRequestTaskRelationAndCleanup(ct, prTaskRelation)
```

2023-03-19 08:15 UTC, naturetime10 commented on apps/github/app_api.go
> +func (a AppAPI) moveTaskToCurrentProgress(ct context.Context, taskID uint64, teamID uint64) *errs.Error {
```suggestion
func (a AppAPI) moveTaskToInProgress(ct context.Context, taskID uint64, teamID uint64) *errs.Error {
```

2023-03-19 08:15 UTC, naturetime10 commented on apps/github/app_api.go
> +			return internalErr
```suggestion
			internalErr := errs.FromGRPCErr(rpcErr)
			a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
			return internalErr
```

2023-03-19 21:42 UTC, naturetime10 approved these changes

2023-03-19 22:57 UTC, merged