Implement app APIs
teamyapp/teamy-backend pull request #344
Opened 2023-02-05 01:55 UTC by Junoth

Tested in Imsonia
<img width="1682" alt="Screen Shot 2023-02-04 at 5 53 00 PM" src="https://user-images.githubusercontent.com/36186063/216797554-ad7a29fd-8751-4b19-aff9-37d2aa95da44.png">
<img width="1681" alt="Screen Shot 2023-02-04 at 5 52 38 PM" src="https://user-images.githubusercontent.com/36186063/216797557-05f9bcf8-75cd-41d5-b945-e1e16929ad7a.png">
<img width="1680" alt="Screen Shot 2023-02-04 at 5 51 50 PM" src="https://user-images.githubusercontent.com/36186063/216797560-4c0520b5-6c94-4925-b098-6b6b5b1d7dfa.png">
<img width="1685" alt="Screen Shot 2023-02-04 at 5 52 16 PM" src="https://user-images.githubusercontent.com/36186063/216797558-77062e0f-1d90-4252-87ec-9fe318e5ee5e.png">
<img width="1685" alt="Screen Shot 2023-02-04 at 5 51 27 PM" src="https://user-images.githubusercontent.com/36186063/216797569-c4a72333-aa09-462d-bee1-2dbadcdb9d74.png">
<img width="1680" alt="Screen Shot 2023-02-04 at 5 51 02 PM" src="https://user-images.githubusercontent.com/36186063/216797572-25a76da0-bd2e-4209-b367-8b8cd508ab34.png">

2023-02-05 11:43 UTC, naturetime10 requested changes

2023-02-05 11:43 UTC, naturetime10 commented on core/api/gql/app_version.go
> +	return a.appVersion.IconUrl
```suggestion
	return a.appVersion.IconURL
```

2023-02-05 11:43 UTC, naturetime10 commented on core/api/gql/app_version.go
> +	return a.appVersion.UiExtensionEntrypointPath
```suggestion
	return a.appVersion.UIExtensionEntrypointPath
```

2023-02-05 11:43 UTC, naturetime10 commented on core/api/gql/app_version.go
> +	return a.appVersion.HasUiExtension
```suggestion
	return a.appVersion.HasUIExtension
```

2023-02-05 11:43 UTC, naturetime10 commented on core/api/gql/app_version.go
> +	for _, teamId := range teamIDs {
```suggestion
	for _, teamID := range teamIDs {
```

2023-02-05 11:43 UTC, naturetime10 commented on core/api/gql/app_version.go
> +		team, err := a.deps.teamService.FindTeamByID(ct, teamId)
```suggestion
		team, err := a.deps.teamService.FindTeamByID(ct, teamID)
```

2023-02-05 11:43 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		IconUrl:                   args.Input.IconUrl,
```suggestion
		IconURL:                   args.Input.IconURL,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		HasUiExtension:            args.Input.HasUIExtension,
```suggestion
		HasUIExtension:            args.Input.HasUIExtension,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		UiExtensionEntryPointPath: args.Input.UIExtensionEntrypointPath,
```suggestion
		UIExtensionEntryPointPath: args.Input.UIExtensionEntrypointPath,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/authorization/query.go
> +		Operation:    "ManageApp",
```suggestion
		Operation:    "CreateAppVersion",
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_team_installation.go
> +		AND enabled_version_number = $2;
```suggestion
		WHERE app_id = $1 AND enabled_version_number = $2;
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +			&appVersion.IconUrl,
```suggestion
			&appVersion.IconURL,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +			&appVersion.HasUiExtension,
```suggestion
			&appVersion.HasUIExtension,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +			&appVersion.UiExtensionEntrypointPath,
```suggestion
			&appVersion.UIExtensionEntrypointPath,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +func (a AppVersion) CreateAppVersion(ct context.Context, appVersion entity.AppVersion) (int32, error) {
Let's calculate version number at service layer because it's considered as business logic. We can add an API on `AppVersion` to get the max version for an app and use it in service layer instead of coupling `max version` and `create` logic in this single API call.

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +func (a AppVersion) CreateAppVersion(ct context.Context, appVersion entity.AppVersion) (int32, error) {
This will also delegate transaction to the service layer. With our upcoming changes, we will introduce transaction for all DB operations. We can design transaction together if you are interested in.

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +		appVersion.HasUiExtension,
```suggestion
		appVersion.HasUIExtension,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +		appVersion.IconUrl,
```suggestion
		appVersion.IconURL,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +	}
Let's separate them and delegate individual operation at service layer.

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +    	`,
Let's separate them and delegate individual operation at service layer.

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +		appVersion.UiExtensionEntrypointPath,
```suggestion
		appVersion.UIExtensionEntrypointPath,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +func (a AppVersion) CreateAppVersion(ct context.Context, appVersion entity.AppVersion) (int32, error) {
1 DAO is for 1 DB table only.

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +	}
Let's separate them to different DAO API and delegate individual operation at service layer.

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +			&appVersion.IconUrl,
```suggestion
			&appVersion.IconURL,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +			&appVersion.HasUiExtension,
```suggestion
			&appVersion.HasUIExtension,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +			&appVersion.UiExtensionEntrypointPath,
```suggestion
			&appVersion.UIExtensionEntrypointPath,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +		appVersion.IconUrl,
```suggestion
		appVersion.IconURL,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +		appVersion.HasUiExtension,
```suggestion
		appVersion.HasUIExtension,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +		appVersion.UiExtensionEntrypointPath,
```suggestion
		appVersion.UIExtensionEntrypointPath,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/entity/app_version.go
> +	IconUrl                   *string
```suggestion
	IconURL                   *string
```

2023-02-05 11:43 UTC, naturetime10 commented on core/entity/app_version.go
> +	HasUiExtension            bool
```suggestion
	HasUIExtension            bool
```

2023-02-05 11:43 UTC, naturetime10 commented on core/entity/app_version.go
> +	UiExtensionEntrypointPath *string
```suggestion
	UIExtensionEntrypointPath *string
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +	IconUrl                   *string
```suggestion
	IconURL                   *string
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +	HasUiExtension            bool
```suggestion
	HasUIExtension            bool
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +	UiExtensionEntryPointPath *string
```suggestion
	UIExtensionEntryPointPath *string
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion

```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +		HasUiExtension: false,
```suggestion
		HasUIExtension: false,
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +		CreatedAt:      time.Now(),
```suggestion
		CreatedAt:      time.Now().UTC(),
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +	}
```suggestion
	}
	
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +func (a App) FindAppVersionByAppId(ct context.Context, appID uint64) ([]entity.AppVersion, error) {
```suggestion
func (a App) FindAppVersionByAppID(ct context.Context, appID uint64) ([]entity.AppVersion, error) {
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +func (a App) FindAppVersionByAppIdAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) (entity.AppVersion, error) {
```suggestion
func (a App) FindAppVersionByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) (entity.AppVersion, error) {
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +	}
```suggestion
	if input.IconUrl != nil {
		av.IconUrl = input.IconUrl
	}
	
	if input.Changes != nil {
		av.Changes = input.Changes
	}
	
	if input.UiExtensionEntryPointPath != nil {
		av.UiExtensionEntrypointPath = input.UiExtensionEntryPointPath
	}
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +	now := time.Now()
```suggestion
	now := time.Now().UTC()
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +		query := authorization.NewDeleteAppTeamInstallationQuery(userID, appID)
Does this API have anything to do with `DeleteAppTeamInstallation`?

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +	return av, nil
Need to register resource to make sure it's owned the app creator.

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +		query := authorization.NewUpdateAppTeamInstallationQuery(userID, appID)
This should be `NewUpdateAppVersionQuery` providing `userID, appID, and version number`.

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +		query := authorization.NewDeleteAppTeamInstallationQuery(userID, appID)
This should be `NewDeleteAppVersionQuery` providing `userID, appID, and version number`.

2023-02-05 11:43 UTC, naturetime10 commented on core/service/app.go
> +		query := authorization.NewDeleteAppTeamInstallationQuery(userID, appID)
Does this API have anything to do with `DeleteAppTeamInstallation`?

2023-02-06 02:36 UTC, yijia-cc requested changes

2023-02-06 02:36 UTC, yijia-cc commented on core/dao/sqldb/app_version.go
> +	   	changes
```suggestion
	    has_ui_extension,
	    ui_extension_entrypoint_path,
	    is_public,
	    created_at,
	    updated_at,
	    changes
```

2023-02-06 02:36 UTC, yijia-cc commented on core/dao/sqldb/app_version.go
> +	   	changes
```suggestion
	    has_ui_extension,
	    ui_extension_entrypoint_path,
	    is_public,
	    created_at,
	    updated_at,
	    changes
```

2023-02-06 02:36 UTC, yijia-cc commented on core/dao/sqldb/app_version.go
> +func (a AppVersion) CreateAppVersion(ct context.Context, appVersion entity.AppVersion) (int32, error) {
> Let's calculate version number at service layer because it's considered as business logic. We can add an API on `AppVersion` to get the max version for an app and use it in service layer instead of coupling `max version` and `create` logic in this single API call.

+1, can we denormalize max version so that we don't have to do max(version_number) each query?

2023-02-06 02:36 UTC, yijia-cc commented on core/dao/sqldb/app_version.go
> +func (a AppVersion) CreateAppVersion(ct context.Context, appVersion entity.AppVersion) (int32, error) {
> This will also delegate transaction to the service layer. With our upcoming changes, we will introduce transaction for all DB operations. We can design transaction together if you are interested in.

+1 If we move transaction to service, we will have the flexibility to combine multiple db operations in the same transaction.

2023-02-06 02:36 UTC, yijia-cc commented on core/service/app.go
> +	return av, nil
> Need to register resource to make sure it's owned the app creator.

We can refer this API: https://github.com/teamyapp/teamy-backend/blob/master/core/service/team.go#L154

2023-02-06 02:36 UTC, yijia-cc commented on core/service/app.go
> +	if feature.EnableAuthorization {
I wonder do we want to call `CreateAppVersion` API when it's first time to create an app? I recall there's another API called `CreateApp` for the first time creation?

I think check permission here is fine. Just want to mention that people are supposed not to have the permission in database if it's their first time to create an app, we should assume all people are authorized to `CreateApp`. If people are creating another version of the app, then we need to check their permission to `CreateAppVersion`.

2023-02-06 02:36 UTC, yijia-cc commented on core/service/app.go
> +		query := authorization.NewUpdateAppTeamInstallationQuery(userID, appID)
I saw there are some inconsistency as in permission queries. In `CreateAppVersion` we query for `NewCreateAppVersionQuery`, but in `UpdateAppVersion`,  we query for `NewUpdateAppTeamInstallationQuery`, is it intentional? Same thing happened to `DeleteAppVersion`.

Could you also add some details what's `UpdateAppTeamInstallation`? Is it to update the app settings?

2023-02-08 02:47 UTC, Junoth commented on core/service/app.go
> +		query := authorization.NewUpdateAppTeamInstallationQuery(userID, appID)
Those inconsistencies are unintended. I've updated to use different queries

2023-02-08 02:47 UTC, Junoth commented on core/service/app.go
> +	return av, nil
I plan to register the resource when user creates the app. which will be implemented in next PR

2023-02-08 02:47 UTC, Junoth commented on core/service/app.go
> +	if feature.EnableAuthorization {
I plan to register app resource when user tries to create app which will be implemented in next PR.

2023-02-08 02:47 UTC, Junoth commented on core/dao/sqldb/app_version.go
> +func (a AppVersion) CreateAppVersion(ct context.Context, appVersion entity.AppVersion) (int32, error) {
After discuss, we'll do the cascading clean-up in service layer. The next task I'll work on after implementing APP api is to design and implement transaction library. After that finish, we'll protect those operations with transaction.

can we denormalize max version so that we don't have to do max(version_number) each query?
I think we can do that in the future. This create app should not be called very frequently and that get max version number query will covered by index, which should be efficient.

2023-02-09 02:55 UTC, naturetime10 commented on core/service/app.go
> +	return av, nil
@Junoth  We also need to register permission when creating new version.

2023-02-09 02:59 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +func (a AppVersion) CreateAppVersion(ct context.Context, appVersion entity.AppVersion) (int32, error) {
Discussed offline. `Denormalizing` maxVersion is not needed because of good `B+ tree` query performance .

2023-02-09 08:24 UTC, naturetime10 requested changes

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version.go
> +func (a AppVersion) VisibleToTeams(ct context.Context) []Team {
```suggestion
func (a AppVersion) VisibleToTeams(ct context.Context) ([]Team, error) {
```

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version.go
> +		return nil
```suggestion
		return nil, err
```

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version.go
> +		teams = append(teams, team)
I think we should put this whole piece of logic in `appService` and find team through `teamDao` in `appService` so that this piece of logic and reused and tested together.

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		return AppVersion{}, argErr
```suggestion
        internalErr := &errs.Error {
            Code: errs.InvalidArgument,
            EmbedErr: argErr,
        }
		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
		return AppVersion{}, errs.ToResolverErr(internalErr)
```

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		return AppVersion{}, argErr
```suggestion
		internalErr := &errs.Error {
            Code: errs.InvalidArgument,
            EmbedErr: argErr,
        }
		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
		return AppVersion{}, errs.ToResolverErr(internalErr)
```

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		return AppVersion{}, argErr
```suggestion
		internalErr := &errs.Error {
            Code: errs.InvalidArgument,
            EmbedErr: argErr,
        }
		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
		return AppVersion{}, errs.ToResolverErr(internalErr)
```

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		return AppVersion{}, argErr
```suggestion
		internalErr := &errs.Error {
            Code: errs.InvalidArgument,
            EmbedErr: argErr,
        }
		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
		return AppVersion{}, errs.ToResolverErr(internalErr)
```

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		return AppVersion{}, argErr
```suggestion
		internalErr := &errs.Error {
            Code: errs.InvalidArgument,
            EmbedErr: argErr,
        }
		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
		return AppVersion{}, errs.ToResolverErr(internalErr)
```

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +	}
Let's combine them into a single API in `appService`.

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		return AppVersion{}, argErr
```suggestion
		internalErr := &errs.Error {
            Code: errs.InvalidArgument,
            EmbedErr: argErr,
        }
		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
		return AppVersion{}, errs.ToResolverErr(internalErr)
```

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +		return AppVersion{}, argErr
```suggestion
		internalErr := &errs.Error {
            Code: errs.InvalidArgument,
            EmbedErr: argErr,
        }
		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
		return AppVersion{}, errs.ToResolverErr(internalErr)
```

2023-02-09 08:24 UTC, naturetime10 commented on core/api/gql/app_version_mutation.go
> +	}
Let's combine them into a single API in `appService`.

2023-02-09 08:24 UTC, naturetime10 commented on core/authorization/query.go
> +func NewUpdateAppVersionQuery(userID uint64, appID uint64) Query {
Well, since we didn't assign ID to app version, this become a bit difficult. Originally what we pass in should be `appVersionID`. We can discuss how to solve this problem.

2023-02-09 08:24 UTC, naturetime10 commented on core/authorization/query.go
> +func NewDeleteAppVersionQuery(userID uint64, appID uint64) Query {
Since we didn't assign ID to app version, this become a bit difficult. Originally what we pass in should be `appVersionID`. We can discuss how to solve this problem.

2023-02-09 08:24 UTC, naturetime10 commented on core/authorization/query.go
> +	return Query{
Since we didn't assign ID to app version, this become a bit difficult. Originally what we pass in should be `appVersionID`. We can discuss how to solve this problem.

2023-02-09 08:24 UTC, naturetime10 commented on core/authorization/query.go
> +	return Query{
Since we didn't assign ID to app version, this become a bit difficult. Originally what we pass in should be `appVersionID`. We can discuss how to solve this problem.

2023-02-09 08:24 UTC, naturetime10 commented on core/dao/app_version_visible_team.go
> +	DeleteAppVersionVisibleTeamByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) *errs.Error
Is it possible to delete a single team without `teamID`?

2023-02-09 08:24 UTC, naturetime10 commented on core/dao/sqldb/app_team_installation.go
> +func (a AppTeamInstallation) DeleteAppTeamInstallationByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) *errs.Error {
```suggestion
func (a AppTeamInstallation) DeleteAppTeamInstallationsByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) *errs.Error {
```

2023-02-09 08:24 UTC, naturetime10 commented on core/dao/app_version_visible_team.go
> +	DeleteAppVersionVisibleTeamByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) *errs.Error
```suggestion
	DeleteAppVersionVisibleTeamsByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) *errs.Error
```

2023-02-09 08:24 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +	appVersions := make([]entity.AppVersion, 0)
```suggestion
        var internalErr *errs.Error
	appVersions := make([]entity.AppVersion, 0)
```

2023-02-09 08:24 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +		return 0, nil
```suggestion
		internalErr := &errs.Error{
			Code:    errs.NotFound,
			Message: fmt.Sprintf("max VersionNumber not found: appID=%v", appID),
		}
		i.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
		return 0, internalErr
```

Let's handle default version number in `appService` instead.

2023-02-09 08:24 UTC, naturetime10 commented on core/dao/app_team_installation.go
> +	DeleteAppTeamInstallationByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) *errs.Error
```suggestion
	DeleteAppTeamInstallationsByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) *errs.Error
```

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +			Code:    errs.NotFound,
```suggestion
			Code:    errs.Unauthenticated,
```

We are now changing from `errs.NotFound` to `errs.Unauthenticated`

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +	versionNum, err := a.appVersionDao.FindMaxVersionNumber(ct, appID)
```suggestion
	maxVersion, err := a.appVersionDao.FindMaxVersionNumber(ct, appID)
```

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +	}
Check not found error code and set maxVersion to `0`.

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +	av.VersionNumber = versionNum + 1
```suggestion
	}
	
	av.VersionNumber = maxVersion + 1
```

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +				Code:    errs.NotFound,
```suggestion
				Code:    errs. Unauthenticated,
```

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +	}
```suggestion
	av.IconURL = input.IconURL
	av.Changes = input.Changes
	av.UIExtensionEntrypointPath = input.UIExtensionEntryPointPath
```

We do override to allow user to set the value to nil.

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +				Code:    errs.NotFound,
```suggestion
				Code:    errs.Unauthenticated,
```

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +	// TODO(yumiao): Below operations should be atomic by wrapping in one txn. We'll implement that after adding our
```suggestion
	// TODO(yuhang): below operations should be atomic by wrapping in one txn. We'll implement that after adding our
```

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +				Code:    errs.NotFound,
```suggestion
				Code:    errs.Unauthenticated,
```

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +				Code:    errs.NotFound,
```suggestion
				Code:    errs.Unauthenticated,
```

2023-02-09 08:24 UTC, naturetime10 commented on core/service/app.go
> +	err = a.appVersionVisibleTeamDao.DeleteAppVersionVisibleTeam(ct, appID, versionNumber, teamID)
I wonder what should we do if the team ready installed this app version?

2023-02-09 08:48 UTC, naturetime10 requested changes

2023-02-09 08:48 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +		}
```suggestion
		if err != nil {
			newInternalErr := &errs.Error{
				Code:     errs.Unknown,
				EmbedErr: err,
			}

			if internalErr == nil {
				internalErr = newInternalErr
			}

			t.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: newInternalErr})
			continue
		}
```

2023-02-09 08:48 UTC, naturetime10 commented on core/dao/sqldb/app_version_visible_team.go
> +			continue
```suggestion
			newInternalErr := &errs.Error{
				Code:     errs.Unknown,
				EmbedErr: err,
			}

			if internalErr == nil {
				internalErr = newInternalErr
			}

			t.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: newInternalErr})
			continue
```

2023-02-09 08:48 UTC, naturetime10 commented on core/dao/sqldb/app_version_visible_team.go
> +	appVersionVisibleTeams := make([]entity.AppVersionVisibleTeam, 0)
```suggestion
        var internalErr *errs.Error
	appVersionVisibleTeams := make([]entity.AppVersionVisibleTeam, 0)
```

2023-02-09 08:48 UTC, naturetime10 commented on core/dao/sqldb/app_version_visible_team.go
> +		}
```suggestion
		if err != nil {
			newInternalErr := &errs.Error{
				Code:     errs.Unknown,
				EmbedErr: err,
			}

			if internalErr == nil {
				internalErr = newInternalErr
			}

			t.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: newInternalErr})
			continue
		}
```

2023-02-09 08:48 UTC, naturetime10 commented on core/dao/sqldb/app_version_visible_team.go
> +	appVersionVisibleTeams := make([]entity.AppVersionVisibleTeam, 0)
```suggestion
        var internalErr *errs.Error
	appVersionVisibleTeams := make([]entity.AppVersionVisibleTeam, 0)
```

2023-02-10 03:26 UTC, Junoth commented on core/api/gql/app_version.go
> +		teams = append(teams, team)
I'll move this to appService

2023-02-10 03:27 UTC, Junoth commented on core/api/gql/app_version_mutation.go
> +	}
Will do that

2023-02-10 03:27 UTC, Junoth commented on core/api/gql/app_version_mutation.go
> +	}
will do that

2023-02-10 03:30 UTC, Junoth commented on core/dao/app_version_visible_team.go
> +	DeleteAppVersionVisibleTeamByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) *errs.Error
I don't get this question. Do you mean delete all visibleTeam records of a time?

2023-02-10 03:32 UTC, Junoth commented on core/service/app.go
> +	}
will do that

2023-02-10 03:32 UTC, naturetime10 commented on core/api/gql/app_version.go
> +func (a AppVersion) VisibleToTeams(ct context.Context) []Team {
Return error

2023-02-10 03:34 UTC, Junoth commented on core/service/app.go
> +	err = a.appVersionVisibleTeamDao.DeleteAppVersionVisibleTeam(ct, appID, versionNumber, teamID)
That's a good question. I didn't consider about that. I think we should remove the installation as well

2023-02-10 05:02 UTC, naturetime10 approved these changes

2023-02-10 05:02 UTC, naturetime10 commented on core/service/app.go
> +	return teams, nil
```suggestion
	}
	
	return teams, nil
```

2023-02-10 05:05 UTC, naturetime10 requested changes

2023-02-10 05:05 UTC, naturetime10 commented on core/dao/app_version_visible_team.go
> +	DeleteAppVersionVisibleTeamByAppIDAndVersionNumber(ct context.Context, appID uint64, versionNumber int32) *errs.Error
@Junoth Yes. You should name it `DeleteAppVersionVisibleTeamsByAppIDAndVersionNumber` instead.

2023-02-10 05:29 UTC, naturetime10 approved these changes

2023-02-10 05:42 UTC, yijia-cc approved these changes

2023-02-10 05:43 UTC, merged