Implement app APIs
teamyapp/teamy-backend pull request #359
Opened 2023-02-12 23:48 UTC by Junoth

Tested in Imsonia
<img width="1683" alt="Screen Shot 2023-02-12 at 3 42 51 PM" src="https://user-images.githubusercontent.com/36186063/218344487-9c7a2c6d-9e8d-4fa4-b18f-cd2804dc85d8.png">
<img width="1682" alt="Screen Shot 2023-02-12 at 3 41 37 PM" src="https://user-images.githubusercontent.com/36186063/218344494-6b91e0ee-23a2-4c62-9926-02e3aced3969.png">
<img width="1683" alt="Screen Shot 2023-02-12 at 3 40 54 PM" src="https://user-images.githubusercontent.com/36186063/218344501-eeb0bdd0-885e-4eab-af2f-7809cebbe61b.png">
<img width="1679" alt="Screen Shot 2023-02-12 at 3 24 04 PM" src="https://user-images.githubusercontent.com/36186063/218344504-a9129e36-73f4-4de2-9f03-d27d9bce81bb.png">
<img width="1687" alt="Screen Shot 2023-02-12 at 3 23 37 PM" src="https://user-images.githubusercontent.com/36186063/218344519-d0d7d869-b2a2-4d19-bf90-94e356cbcd7d.png">

2023-02-15 05:59 UTC, naturetime10 requested changes

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
> +		a.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.deps.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
> +		a.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.deps.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
> +		a.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.deps.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
> +		a.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.deps.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app_mutation.go
> +		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		m.deps.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app_mutation.go
> +		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		m.deps.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app_mutation.go
> +		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		m.deps.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app_mutation.go
> +		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		m.deps.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app_mutation.go
> +		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		m.deps.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app_mutation.go
> +		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		m.deps.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app_mutation.go
> +		m.deps.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		m.deps.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: newInternalErr})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, newInternalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +				a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
				a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +							a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
							a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +				a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
				a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +						a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
						a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, internalErr)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
> +	appVersions, err := a.deps.appService.FindAppVersionByAppId(ct, a.app.ID)
```suggestion
	appVersions, err := a.deps.appService.FindAppVersionsByAppID(ct, a.app.ID)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
>  func (a App) AppName() string {
```suggestion
func (a App) Name() string {
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
>  func (a App) AppName() string {
Can we change this GraphQL to name? The `App` prefix in `AppName` seems not needed because this GraphQL type (and Go struct) is already called `App`.

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
> +	return a.app.AppName
```suggestion
	return a.app.Name
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
> +	appVersions, err := a.deps.appService.FindAppVersionByAppId(ct, a.app.ID)
`versions` instead of `version`.

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app.go
> +	appTeamInstallations, err := a.deps.appService.FindAppTeamInstallationsByAppId(ct, a.app.ID)
```suggestion
	appTeamInstallations, err := a.deps.appService.FindAppTeamInstallationsByAppID(ct, a.app.ID)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app_team_installation.go
> +	app, err := a.deps.appService.FindAppByAppId(ct, a.appTeamInstallation.AppID)
```suggestion
	app, err := a.deps.appService.FindAppByAppID(ct, a.appTeamInstallation.AppID)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/api/gql/app_version.go
> +	app, err := a.deps.appService.FindAppByAppId(ct, a.appVersion.AppID)
```suggestion
	app, err := a.deps.appService.FindAppByAppID(ct, a.appVersion.AppID)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/authorization/query.go
> +		Operation:    "UpdateApp",
```suggestion
		Operation:    "Update",
```

2023-02-15 05:59 UTC, naturetime10 commented on core/authorization/query.go
> +		Operation:    "DeleteApp",
```suggestion
		Operation:    "Delete",
```

2023-02-15 05:59 UTC, naturetime10 commented on core/authorization/query.go
> +		Operation:    "RefreshAppSecret",
```suggestion
		Operation:    "RefreshSecret",
```

2023-02-15 05:59 UTC, naturetime10 commented on core/authorization/resource_type_operation.go
> +		Operation:    "ReadApp",
```suggestion
		Operation:    "Read",
```

2023-02-15 05:59 UTC, naturetime10 commented on core/authorization/resource_type_operation.go
> +		Operation:    "UpdateApp",
```suggestion
		Operation:    "Update",
```

2023-02-15 05:59 UTC, naturetime10 commented on core/authorization/resource_type_operation.go
> +		Operation:    "RefreshAppSecret",
```suggestion
		Operation:    "RefreshSecret",
```

2023-02-15 05:59 UTC, naturetime10 commented on core/authorization/resource_type_operation.go
> +		Operation:    "DeleteApp",
```suggestion
		Operation:    "Delete",
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/app.go
> +	FindApps(ct context.Context) ([]entity.App, *errs.Error)
```suggestion
	FindAllApps(ct context.Context) ([]entity.App, *errs.Error)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/app.go
> +	FindAppByAppID(ct context.Context, appID uint64) (entity.App, *errs.Error)
```suggestion
	FindAppByID(ct context.Context, appID uint64) (entity.App, *errs.Error)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +func (a App) FindAppByAppID(ct context.Context, appID uint64) (entity.App, *errs.Error) {
```suggestion
func (a App) FindAppByID(ct context.Context, appID uint64) (entity.App, *errs.Error) {
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +	    apisecret,
```suggestion
	    api_secret,
```
Can we rename this column to `api_secret` instead?

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +func (a App) FindApps(ct context.Context) ([]entity.App, *errs.Error) {
```suggestion
func (a App) FindAllApps(ct context.Context) ([]entity.App, *errs.Error) {
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +	    apisecret,
```suggestion
	    api_secret,
```

2023-02-15 05:59 UTC, naturetime10 commented on core/entity/app.go
> +	AppName             string
```suggestion
        Name             string
        Description         string
	APISecret           string
	ActiveVersionNumber *int32
	InstallationCount   uint64
	CreatorUserID       uint64
	CreatedAt           time.Time
	UpdatedAt           *time.Time
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +	    app_name
```suggestion
	    id,
	    name,
	    description,
	    api_secret,
	    active_version_number,
	    installation_count,
	    creator_user_id,
	    created_at,
	    updated_at
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +			&app.AppName,
```suggestion
			&app.Name,
                         &app.Description,
			&app.ID,
			&app.APISecret,
			&app.ActiveVersionNumber,
			&app.InstallationCount,
			&app.CreatorUserID,
			&app.CreatedAt,
			&app.UpdatedAt,
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +	    app_name
```suggestion
	    id,
	    name,
	    description,
	    api_secret,
	    active_version_number,
	    installation_count,
	    creator_user_id,
	    created_at,
	    updated_at
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +			&app.AppName,
```suggestion
			&app.ID,
			&app.Name,
			&app.Description,
			&app.APISecret,
			&app.ActiveVersionNumber,
			&app.InstallationCount,
			&app.CreatorUserID,
			&app.CreatedAt,
			&app.UpdatedAt,
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +	 	app_name
```suggestion
	 	id,
	 	name
	 	description,
	 	api_secret,
	 	active_version_number,
	 	installation_count,
	 	creator_user_id,
	 	created_at,
	 	updated_at
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		app.AppName,
```suggestion
		app.ID,
		app.Name,
		app.Description,
		app.APISecret,
		app.ActiveVersionNumber,
		app.InstallationCount,
		app.CreatorUserID,
		app.CreatedAt,
		app.UpdatedAt,
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		    app_name = $8
```suggestion
		    app_name = $1,
		    description = $2,
		    api_secret = $3,
		    active_version_number = $4,
		    installation_count = $5,
		    creator_user_id = $6,
		    created_at = $7,
		    updated_at = $8,
```

2023-02-15 05:59 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		app.ID,
```suggestion
		app.ID,
		app.Name,
		app.Description,
		app.APISecret,
		app.ActiveVersionNumber,
		app.InstallationCount,
		app.CreatorUserID,
		app.CreatedAt,
		app.UpdatedAt,
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +	Description         *string
- [ ] ```suggestion

	Name            string
	Description         string
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +func (a App) FindAppByAppId(ct context.Context, appID uint64) (entity.App, *errs.Error) {
```suggestion
func (a App) FindAppByAppID(ct context.Context, appID uint64) (entity.App, *errs.Error) {
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		apps = append(apps, app)
```suggestion
		}
		
		apps = append(apps, app)
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +						return false
```suggestion
						}
						
						return false
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +	if filter != nil && filter.AppID != nil {
Both filter conditions (AppID & TeamID) require `filter != nil`. We can put it inside a single `if`?

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			}
@```suggestion
```

Teams should be able to access beta app whose activeVersionNumber has not been set.

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			}
There are multiple conditions: if `ActiveVersionNumber != nil`, check `public` of `activeVersion`. If `ActiveVersionNumber == nil` check all versions whether any of them is visible to the team. If `ActiveVersionNumber != nil`,  check all versions starting from active version.

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		CreatedAt:         time.Now(),
```suggestion
		CreatedAt:         time.Now().UTC(),
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		//		assign AppAdmin permissions to app creator
```suggestion
		//		assign AppAdmin permissions to `AppAdmin` group
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +			userID,
I think we don't need to put app owner into this group.

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		_, err = a.authorizer.createUserGroupAndAssignPermissions(ct,
We will need to add 2 more columns to app table to remember `groupID` for admin group and member group so that the app creator can assign new people to the group.

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +	}
```suggestion
	if input.AppName != nil {
		app.AppName = *input.AppName
	}
	
	if input.Description != nil {
		app.Description = *input.Description
	}
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		if *app.ActiveVersionNumber > *input.ActiveVersionNumber {
`*app.ActiveVersionNumber` will lead to `nil` pointer dereference and crash our service based on line 303: `&& app.ActiveVersionNumber == nil`

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +		if *app.ActiveVersionNumber < *input.ActiveVersionNumber {
`*app.ActiveVersionNumber` will lead to `nil` pointer dereference and crash our service based on line 303: `&& app.ActiveVersionNumber == nil`

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +				if appInstallation.EnabledVersionNumber < *input.ActiveVersionNumber {
Is this check needed?

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +	now := time.Now().UTC()
```suggestion
	}
	
	now := time.Now().UTC()
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +	if input.ActiveVersionNumber != nil && app.ActiveVersionNumber == nil {
Can we split rollback and rollforward logic into their own helper methods and give them meaning function name to improve readability?

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +	if app.ActiveVersionNumber != nil && *app.ActiveVersionNumber == versionNumber {
```suggestion
	}
	
	if app.ActiveVersionNumber != nil && *app.ActiveVersionNumber == versionNumber {
```

2023-02-15 05:59 UTC, naturetime10 commented on core/service/app.go
> +				"Delete active version is invalid: stateID=%v", appID),
```suggestion
				"Cannot delete active version: appID=%v", appID),
```

2023-02-18 00:43 UTC, Junoth commented on core/api/gql/app.go
>  func (a App) AppName() string {
sounds good

2023-02-18 00:47 UTC, Junoth commented on core/dao/sqldb/app.go
> +	    apisecret,
I'll add that in the migration

2023-02-18 00:57 UTC, Junoth commented on core/service/app.go
> +	if input.ActiveVersionNumber != nil && app.ActiveVersionNumber == nil {
I'll split that

2023-02-18 00:58 UTC, Junoth commented on core/service/app.go
> +				if appInstallation.EnabledVersionNumber < *input.ActiveVersionNumber {
Yes. we decided not to roll forward user's app if their enabled version is higher

2023-02-18 01:15 UTC, Junoth commented on core/service/app.go
> +	if filter != nil && filter.AppID != nil {
sounds good

2023-02-18 01:19 UTC, Junoth commented on core/service/app.go
> +			}
Will update this logic

2023-02-18 01:25 UTC, Junoth commented on core/service/app.go
> +		_, err = a.authorizer.createUserGroupAndAssignPermissions(ct,
I'm not sure if we should couple the permissions into app table. We may change the group number to create or even change the permission strategy. In that case, we need to update the app table schema.

2023-02-18 01:26 UTC, Junoth commented on core/service/app.go
> +		if *app.ActiveVersionNumber > *input.ActiveVersionNumber {
Will fix this

2023-02-18 01:27 UTC, naturetime10 commented on core/service/app.go
> +		_, err = a.authorizer.createUserGroupAndAssignPermissions(ct,
@Junoth How would app admin add people to those user groups? How will they know which user group should they add people to?

2023-02-18 01:28 UTC, naturetime10 commented on core/service/app.go
> +		_, err = a.authorizer.createUserGroupAndAssignPermissions(ct,
@Junoth We can create a new table called app user group. How does that sound? `AppID, UserGroupID, userGroupType`

2023-02-18 03:07 UTC, Junoth commented
I tested more scenarios in Imsonia including different parameter in filters and roll forward.

2023-02-18 21:07 UTC, Junoth commented on core/service/app.go
> +		_, err = a.authorizer.createUserGroupAndAssignPermissions(ct,
@magicoder10 How do we handle team group now? I think we can do that if we've decided to build the relationship between permission groups and resources, so user can know permission groups under the resource.

2023-02-18 21:12 UTC, Junoth commented on core/service/app.go
> +			userID,
But those two groups have different authorization operations? I followed what we did in team service

2023-02-19 02:45 UTC, Junoth commented on core/service/app.go
> +		_, err = a.authorizer.createUserGroupAndAssignPermissions(ct,
Discussed offline. We'll work on new APIs and DB tables in authorization service later

2023-02-19 02:45 UTC, Junoth commented on core/service/app.go
> +			userID,
Discussed offline. We'll work on new APIs and DB tables in authorization service later

2023-02-19 10:33 UTC, naturetime10 requested changes

2023-02-19 10:33 UTC, naturetime10 commented on core/api/gql/app.go
> +	appVersions, err := a.deps.appService.FindAppVersionByAppId(ct, a.app.ID)
Let's use `ID` instead of `Id`

2023-02-19 10:33 UTC, naturetime10 commented on core/api/gql/app.go
> +	appTeamInstallations, err := a.deps.appService.FindAppTeamInstallationsByAppId(ct, a.app.ID)
Let's use `ID` instead of `Id`

2023-02-19 10:33 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> -	).Scan(&maxVersion)
Does chaining `Scan` work? If yes, I think we don't need to break this into a separate part.

2023-02-19 10:33 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> -	).Scan(&maxVersion)
If we really want to get error of row, let's do `err := row.Err()` instead of calling `row.Err()` at every place.

2023-02-19 10:33 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +		return 0, nil
```suggestion
                 internalErr := &errs.Error{
			Code:     errs.Unknown,
			EmbedErr: err,
		}
		return 0, internalErr
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +			apps = append(apps, app)
```suggestion
			}
			
			apps = append(apps, app)
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +					a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
					a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +							return false
```suggestion
							}
							
							return false
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +					return true
What happens if the app version is not active version but public version? We should consider it as private.

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +		if filter.AppID != nil {
Let's breakdown logics in this method into smaller private helpers to improve readability.

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +			// find all apps that are visible to the team
Can we have pairing session to go through and refactor this logic?

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +						"Roll back active version is invalid: stateID=%v", appID),
```suggestion
						"cannot rollback app version: appID=%v, prevAppVesion=%v newAppVersion=%v", 
						appID, 
						app.ActiveVersionNumber, 
						input.ActiveVersionNumber),
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +			a.authorizer.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +				a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: internalErr})
```suggestion
				a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +				a.RollForwardAppInstallations(ct, appID, *input.ActiveVersionNumber)
```suggestion
				a.rollForwardAppInstallations(ct, appID, *input.ActiveVersionNumber)
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +			a.authorizer.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +			a.authorizer.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
			a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +		a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
		a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +func (a App) RollForwardAppInstallations(ct context.Context, appID uint64, activeVersionNumber int32) *errs.Error {
```suggestion
func (a App) rollForwardAppInstallations(ct context.Context, appID uint64, activeVersionNumber int32) *errs.Error {
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +// RollForwardAppInstallations Helper function to roll forward all app installations when a
```suggestion
// rollForwardAppInstallations moves all app installations to a new version
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +// newer active version enabled
```suggestion
```

2023-02-19 10:33 UTC, naturetime10 commented on core/service/app.go
> +				a.dataCollector.Logger.LogWithContext(ct, telemetry.Error, telemetry.Props{telemetry.CauseProp: err})
```suggestion
				a.dataCollector.Logger.ErrorWithContext(ct, err)
```

2023-02-19 10:33 UTC, naturetime10 commented on migrations/20230218125200_update_api_secret_column.sql
> +    DROP COLUMN app_name,
```suggestion
	DROP COLUMN apisecret,
        DROP COLUMN app_name,
```

2023-02-19 10:33 UTC, naturetime10 commented on migrations/20230218125200_update_api_secret_column.sql
> +	DROP COLUMN api_secret,
```suggestion
    DROP COLUMN name,
    DROP COLUMN api_secret,
```

2023-02-19 23:10 UTC, Junoth commented on core/dao/sqldb/app_version.go
> -	).Scan(&maxVersion)
No that will fail if there is no row.

I'll update that

2023-02-24 07:31 UTC, Junoth commented on core/service/app.go
> +					return true
If a public version is not active version but larger than it, I think we need to consider it as a public one and visible to everyone.

For example, the developer creates a beta version and want to expose to all customer for early experience, but doesn't want to set it as active since it may not be very stable.

2023-02-24 07:31 UTC, Junoth commented on core/service/app.go
> +		if filter.AppID != nil {
I'll break down the logic

2023-02-24 07:40 UTC, Junoth commented on core/service/app.go
> +			// find all apps that are visible to the team
I've updated the logic of this part and added some helper function. Please let me know if you still want to have a pair session

2023-02-24 07:52 UTC, Junoth commented on migrations/20230218125200_update_api_secret_column.sql
> +	DROP COLUMN apisecret,
I don't know why this looks different in github. The format in my local machine is good

<img width="2560" alt="Screen Shot 2023-02-23 at 11 51 58 PM" src="https://user-images.githubusercontent.com/36186063/221122691-bc2ce229-d220-411c-bcfd-f570eca7da61.png">

2023-02-24 08:27 UTC, naturetime10 requested changes

2023-02-24 08:27 UTC, naturetime10 commented on migrations/20230218125200_update_api_secret_column.sql
> +	DROP COLUMN apisecret,
Okey.

2023-02-24 08:27 UTC, naturetime10 commented on core/service/app.go
> +// rollForwardAppInstallations moves all app installations to a new version
```suggestion
// rollForwardAppInstallations moves all app installations to a newly enabled version
```

2023-02-24 08:27 UTC, naturetime10 commented on core/service/app.go
> +// isAppVisibleToTeam check if an app is visible to a team
```suggestion
```

I think the help name is very clear already.

2023-02-24 08:27 UTC, naturetime10 commented on core/service/app.go
> +// isAppVersionVisibleToTeam check if an app version is visible to a team
```suggestion
```

2023-02-24 08:27 UTC, naturetime10 commented on core/service/app.go
> +	}
```suggestion
```

2023-02-24 08:27 UTC, naturetime10 commented on core/service/app.go
> +	if !appVersion.IsPublic {
```
if app.ActiveVersionNumber == appVersion.VersionNumber {
    if appVersion.IsPublic {
        return true
    }
}
```

2023-02-25 21:41 UTC, Junoth commented on core/service/app.go
> +	if !appVersion.IsPublic {
I don't get this part. Could you elaborate?

2023-02-25 21:42 UTC, naturetime10 commented on core/service/app.go
> +	if !appVersion.IsPublic {
@Junoth If the appVersion is not active, it will always be treated as private no matter whether `IsPublic` is `true` or `false`

2023-02-25 21:49 UTC, Junoth commented on core/service/app.go
> +	if !appVersion.IsPublic {
Discussed offline. We'll allow app developer to create a public version but not activated, since they migth need a public beta version for customers to experience

2023-02-25 22:02 UTC, naturetime10 approved these changes

2023-02-25 22:11 UTC, merged