Update realtime and mutation package for new txn system
teamyapp/teamy-backend pull request #376
Opened 2023-02-22 08:00 UTC by Junoth

This PR is the first one to update existing methods to adopt new transaction system, which was added in this PR: https://github.com/teamyapp/teamy-backend/pull/363

To avoid affecting other methods, we add v2Dao and v2Mutation packages and according methods for new implementation.

Also, we updated the mutation and passed in client notifiers when creation instead of call DAO in the mthod.

2023-02-22 08:02 UTC, Junoth commented
@magicoder10, this PR is larger than I expected since we have to add multiple v2 packages to avoid affecting other methods.

2023-02-22 08:03 UTC, Junoth commented on core/mutationv2/update_task_mutation.go
> +	clientNotifiers []*realtimev2.ClientNotifier,
@magicoder10 I have to update the mutation to pass in client notifiers when creation instead of querying when calling the method, since this will be called when realtime transaction commit which is outside of db transaction. Please let me know if you have concerns.

2023-02-22 08:25 UTC, naturetime10 commented on core/mutationv2/update_task_mutation.go
> +	clientNotifiers []*realtimev2.ClientNotifier,
Certain mutations, such as adding an user to a team, will need to send the transaction to the newly added user. How about we add a new API to mutation `PrepareClientNotifiers(ct context.Context, sqlTx *sql.Tx)` which cache client notifiers into instance variable of the `Mutation`? It will be invoked before calling `sqlTx.Commit()`

2023-02-22 09:00 UTC, naturetime10 requested changes

2023-02-22 09:00 UTC, naturetime10 commented on core/daov2/sqldb/sprint.go
> +func NewSprint(dataCollector telemetry.DataCollector, sqlDB *sql.DB) Sprint {
```suggestion
func NewSprint(dataCollector telemetry.DataCollector) Sprint {
```

2023-02-22 09:00 UTC, naturetime10 commented on core/daov2/sqldb/sprint_task_relation.go
> +func NewSprintTaskRelation(dataCollector telemetry.DataCollector, db *sql.DB) SprintTaskRelation {
```suggestion
func NewSprintTaskRelation(dataCollector telemetry.DataCollector) SprintTaskRelation {
```

2023-02-22 09:00 UTC, naturetime10 commented on core/mutationv2/update_sprint_participant_mutation.go
> +	clientNotifiers []*realtimev2.ClientNotifier,
Certain mutations, such as adding an user to a team, will need to send the transaction to the newly added user. How about we add a new API to mutation `PrepareClientNotifiers(ct context.Context, sqlTx *sql.Tx)` which cache client notifiers into instance variable of the `Mutation`? It will be invoked before calling `sqlTx.Commit()`

2023-02-22 09:00 UTC, naturetime10 commented on core/service/task.go
> +		updatedAt := time.Now()
```suggestion
		updatedAt := time.Now().UTC()
```

2023-02-22 09:00 UTC, naturetime10 commented on core/service/task.go
> +		clientNotifiers, internalErr = t.stateSyncerV2.GetClientNotifiersByTeamID(ct, task.OwningTeamID)
Need to handle error

2023-02-22 09:00 UTC, naturetime10 commented on core/service/task.go
> +		rtTx.AppendMutation(updateTaskMutation)
```suggestion
		}
		
		rtTx.AppendMutation(updateTaskMutation)
```

2023-02-23 05:21 UTC, naturetime10 requested changes

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/create_invitation_mutation.go
> +func (c *CreateInvitationMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/create_message_mutation.go
> +var _ realtime.Mutation = (*CreateMessageMutation)(nil)
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/create_sprint_participant_mutation.go
> +func (c *CreateSprintParticipantMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/create_sprint_task_relation_mutation.go
> +func (c *CreateSprintTaskRelationMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/create_task_await_for_relation_mutation.go
> +func (c *CreateTaskAwaitForRelationMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/create_task_link_mutation.go
> +func (c *CreateTaskLinkMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/create_task_mutation.go
> +func (c *CreateTaskMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/create_team_member_muation.go
> +func (c *CreateTeamMemberMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/create_team_mutation.go
> +func (c *CreateTeamMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/delete_invitation_mutation.go
> +func (d *DeleteInvitationMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/delete_message_mutation.go
> +func (d *DeleteMessageMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/delete_sprint_participant_mutation.go
> +func (d *DeleteSprintParticipantMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/delete_sprint_task_relation_mutation.go
> +func (d *DeleteSprintTaskRelationMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/delete_task_await_for_relation_mutation.go
> +func (d *DeleteTaskAwaitForRelationMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/delete_task_mutation.go
> +func (d *DeleteTaskMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/delete_team_member_muation.go
> +func (d *DeleteTeamMemberMutation) PrepareClientNotifiers(ct context.Context, tx *sql.Tx) ([]*realtime.ClientNotifier, *errs.Error) {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/delete_team_mutation.go
> +func (u *DeleteTeamMutation) PrepareClientNotifiers(ct context.Context, tx *sql.Tx) ([]*realtime.ClientNotifier, *errs.Error) {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/update_invitation_mutation.go
> +func (u *UpdateInvitationMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/update_message_mutation.go
> +func (u *UpdateMessageMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/update_task_activity_mutation.go
> +func (u *UpdateTaskActivityMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/update_task_mutation.go
> +func (u *UpdateTaskMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/update_team_member_muation.go
> +func (u *UpdateTeamMemberMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/update_team_mutation.go
> +func (u *UpdateTeamMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/mutation/update_user_mutation.go
> +func (u *UpdateUserMutation) ExecuteV2(ct context.Context, tx *sql.Tx) *errs.Error {
Let's move `ExecuteV2` and `PrepareClientNotifiers` below `GetID`.

2023-02-23 05:21 UTC, naturetime10 commented on core/realtime/mutation.go
> +	PrepareClientNotifiers(ct context.Context, tx *sql.Tx) ([]*ClientNotifier, *errs.Error)
```suggestion
	PrepareClientNotifiers(ct context.Context, tx *sql.Tx) *errs.Error
```

We are going to change internal state of mutation instead of returning `[]*ClientNotifier`

2023-02-23 05:21 UTC, naturetime10 commented on core/realtime/transaction.go
> +}
Let's add a method called `GetMutations() []Mutation`.

2023-02-23 05:24 UTC, naturetime10 requested changes
It seems that we are not including updateTask changes in TaskService.

2023-02-23 05:24 UTC, naturetime10 commented on core/service/transaction.go
> +	rtTx := realtime.NewTransaction(t.dataCollector, t.stateSyncer)
Please get and loop through all mutations from rtTx and invoke prepare client notifiers between line 34 and line 35.

2023-02-23 05:45 UTC, naturetime10 approved these changes

2023-02-23 05:48 UTC, merged