Handle errors for Github GraphQL API
teamyapp/teamy-backend pull request #377
Opened 2023-02-22 08:21 UTC by szheng2207

2023-02-22 08:31 UTC, naturetime10 requested changes

2023-02-22 08:31 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +	} `json:"locations"`
Let's extract 
```
struct {
		Line   int `json:"line"`
		Column int `json:"column"`
}
```
into a struct called `Location`?

2023-02-22 08:31 UTC, naturetime10 commented on apps/github/client/gql_api.go
> +		} `json:"problems"`
Can we extract
```
struct {
			Path        []interface{} `json:"path"`
			Explanation string        `json:"explanation"`
		}
```
into a struct called `Problem`?

2023-02-22 08:31 UTC, naturetime10 commented on apps/github/client/gql_api.go
>  		}
Can we create multiple `internalErr` and log them individually?

2023-02-22 19:32 UTC, szheng2207 commented on apps/github/client/gql_api.go
>  		}
sure, mind sharing why can't we combine the errors in the log?

2023-02-23 04:21 UTC, naturetime10 commented on apps/github/client/gql_api.go
>  		}
@szheng2207 We can. Let's create our own `MultiErrors` helper.

2023-02-23 04:21 UTC, naturetime10 commented on apps/github/client/gql_api.go
>  		}
@szheng2207 In the next PR.

2023-02-23 07:19 UTC, naturetime10 approved these changes

2023-02-23 07:19 UTC, merged