Add transaction into sprint service
teamyapp/teamy-backend pull request #394
Opened 2023-03-09 06:00 UTC by Junoth

Tested in Imsonia
<img width="1679" alt="Screen Shot 2023-03-08 at 9 19 28 PM" src="https://user-images.githubusercontent.com/36186063/223933908-9168d893-1f40-4bb7-9f32-6aaab026a365.png">
<img width="1683" alt="Screen Shot 2023-03-08 at 9 19 59 PM" src="https://user-images.githubusercontent.com/36186063/223933915-9d273ad9-39d9-45f8-9853-a68338b1c045.png">
<img width="1680" alt="Screen Shot 2023-03-08 at 9 45 17 PM" src="https://user-images.githubusercontent.com/36186063/223933921-32ffe88c-8643-4ead-bc08-9bc23c5a6b7a.png">
<img width="1686" alt="Screen Shot 2023-03-08 at 9 46 54 PM" src="https://user-images.githubusercontent.com/36186063/223933925-23ddad6c-dcfc-439d-8e63-3da697e051ac.png">
<img width="1681" alt="Screen Shot 2023-03-08 at 9 47 23 PM" src="https://user-images.githubusercontent.com/36186063/223933928-cf422a47-b740-42b5-86e3-2be970251d44.png">
<img width="1681" alt="Screen Shot 2023-03-08 at 9 48 07 PM" src="https://user-images.githubusercontent.com/36186063/223933931-5710d0b9-ed38-4b51-8bb6-026eefc059d3.png">
<img width="1678" alt="Screen Shot 2023-03-08 at 9 48 46 PM" src="https://user-images.githubusercontent.com/36186063/223933936-8ee55835-6095-4ea3-8d9d-cfb53fe6d0fb.png">

2023-03-09 09:14 UTC, naturetime10 requested changes

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/create_sprint_participant_mutation.go
> +	sprint, err := c.sprintDaoV2.FindSprintByID(ct, tx, c.sprintParticipant.SprintID)
```suggestion
	}
	
	sprint, err := c.sprintDaoV2.FindSprintByID(ct, tx, c.sprintParticipant.SprintID)
```

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/create_sprint_participant_mutation.go
> +	notifiersPrepared      bool
Is this needed?

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/create_sprint_task_relation_mutation.go
> +	sprint, err := c.sprintDao.FindSprintByID(ct, c.sprintTaskRelation.SprintID)
```suggestion
	}
	
	sprint, err := c.sprintDao.FindSprintByID(ct, c.sprintTaskRelation.SprintID)
```

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/create_task_await_for_relation_mutation.go
>  	task, err := c.taskDaoV2.FindTaskByID(ct, tx, c.taskAwaitForRelation.AwaitForTaskID)
```suggestion
	}
	
	task, err := c.taskDaoV2.FindTaskByID(ct, tx, c.taskAwaitForRelation.AwaitForTaskID)
```

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/create_task_mutation.go
>  	var internalErr *errs.Error
```suggestion
	}
	
	var internalErr *errs.Error
```

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/delete_sprint_task_relation_mutation.go
> +	}
```suggestion
		return nil
	}
	
```

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/delete_task_await_for_relation_mutation.go
> +	}
```suggestion
		return nil
	}
	
```

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/delete_task_mutation.go
> +	}
```suggestion
	}
	
```

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/update_sprint_participant_mutation.go
> +	}
```suggestion
	}
	
```

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/update_task_activity_mutation.go
> +	}
```suggestion
	}
	
```

2023-03-09 09:14 UTC, naturetime10 commented on core/mutation/update_task_mutation.go
> +	}
```suggestion
	}
	
```

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +		}
Can this be done outside `txCtx.withTransactions`?

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +		}
Can this be done outside `withTransactions?

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +		})
Can this be done outside `withTransactions`?

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +		sprint = sprints[0]
Can this be done outside `withTransactions`?

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +			deleteSprintParticipantMutation.PrepareClientNotifiers(ct, sqlTx)
So we are deduping `PrepareClientNotifiers` because of this?

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +			deleteSprintParticipantMutation.PrepareClientNotifiers(ct, sqlTx)
Should we remove `PrepareClientNotifiers` from `withTransactions`?

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +	// TODO(yuhang): these genID requests should be batched in one
```suggestion
	// TODO(yuhang): these genID requests should be batched in a single RPC
```

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +	// TODO(yuhang): these genID requests should be batched in one
We can create batching API afterwards

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +func (s Sprint) copyTaskToSprint(ct context.Context, sqlTx *sql.Tx, rtTx *realtime.Transaction, toSprintID uint64, taskID uint64, newTaskID uint64, newThreadID uint64) (entity.Task, *errs.Error) {
```suggestion
func (s Sprint) copyTaskToSprint(
    ct context.Context, 
    sqlTx *sql.Tx, 
    rtTx *realtime.Transaction, 
    toSprintID uint64, 
    taskID uint64, 
    newTaskID uint64, 
    newThreadID uint64,
) (entity.Task, *errs.Error) {
```

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +func (s Sprint) moveTaskToSprint(ct context.Context, sqlTx *sql.Tx, rtTx *realtime.Transaction, fromSprintID uint64, toSprintID uint64, taskID uint64) (entity.Task, *errs.Error) {
```suggestion
func (s Sprint) moveTaskToSprint(
   bct context.Context, 
   sqlTx *sql.Tx, 
   rtTx *realtime.Transaction, 
   fromSprintID uint64, 
   toSprintID uint64, 
   taskID uint64,
) (entity.Task, *errs.Error) {
```

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +func (s Sprint) tryReduceBandwidth(ct context.Context, sqlTx *sql.Tx, rtTx *realtime.Transaction, sprintID uint64, task entity.Task) *errs.Error {
```suggestion
func (s Sprint) tryReduceBandwidth(
    ct context.Context, 
    sqlTx *sql.Tx, 
    rtTx *realtime.Transaction, 
    sprintID uint64, 
    task entity.Task,
) *errs.Error {
```

2023-03-09 09:14 UTC, naturetime10 commented on core/service/sprint.go
> +func (s Sprint) tryIncreaseBandwidth(ct context.Context, sqlTx *sql.Tx, rtTx *realtime.Transaction, sprintID uint64, task entity.Task) *errs.Error {
```suggestion
func (s Sprint) tryIncreaseBandwidth(
    ct context.Context, 
    sqlTx *sql.Tx, 
    rtTx *realtime.Transaction, 
    sprintID uint64, 
    task entity.Task,
) *errs.Error {
```

2023-03-10 04:41 UTC, Junoth commented on core/mutation/create_sprint_participant_mutation.go
> +	notifiersPrepared      bool
Yes. This is needed for DeleteSprint at least. We have to prepare notifiers before delete the sprint in the txn

2023-03-10 04:46 UTC, Junoth commented on core/service/sprint.go
> +		}
There is no lock or api calling in that method so I think it should not impact performance

2023-03-10 04:46 UTC, Junoth commented on core/service/sprint.go
> +		}
The same. We can put it outside of transaction but I think it will not make much difference

2023-03-10 04:47 UTC, Junoth commented on core/service/sprint.go
> +		})
Same as above

2023-03-10 04:50 UTC, Junoth commented on core/service/sprint.go
> +			deleteSprintParticipantMutation.PrepareClientNotifiers(ct, sqlTx)
Right. I think we put PrepareClientNotifiers instide withTransactions because we want to use the same txn

2023-03-10 04:51 UTC, Junoth commented on core/service/sprint.go
> +	// TODO(yuhang): these genID requests should be batched in one
sounds good

2023-03-10 04:53 UTC, Junoth commented on core/service/sprint.go
> +		sprint = sprints[0]
Same as above

2023-03-10 05:35 UTC, naturetime10 approved these changes

2023-03-10 05:35 UTC, naturetime10 commented on teamy-backend
> +(HappenAt:2023-03-10 05:29:26.051071 +0000 UTC) (Severity:Info) (FileName:/Users/yuhangmiao/Junoth/Proj/teamyapp/teamy-backend/main.go) (LineNumber:87) (Message:https://github.com///commit/)
Let's remove this file. My previous PR accidentally introduced wrong log location. I will create a PR for the fix afterwards.

2023-03-10 05:52 UTC, merged