Add backfill API to backfill Github pull request metadata
teamyapp/teamy-backend pull request #395
Opened 2023-03-09 08:41 UTC by szheng2207

2023-03-09 09:16 UTC, naturetime10 requested changes

2023-03-09 09:16 UTC, naturetime10 commented on apps/dao/github_pull_request.go
> +	FindPullRequestsMissingMetadata(ct context.Context) ([]entity.GithubPullRequest, *errs.Error)
I think this belongs to business logic instead of pure data access.

2023-03-10 05:42 UTC, naturetime10 requested changes

2023-03-10 05:42 UTC, naturetime10 commented on apps/dao/sqldb/github_installation.go
> +
What if we have error but not `sql.ErrNoRows`, such as connection error?

2023-03-10 05:42 UTC, naturetime10 commented on apps/github/app_api.go
> +
```suggestion
```

2023-03-10 05:42 UTC, naturetime10 commented on apps/github/app_api.go
> +			fmt.Sprintf("complete backfilling pull request, metadata=%v", pr))
```suggestion
			fmt.Sprintf("finish backfilling pull request, metadata=%v", pr))
```

2023-03-10 05:42 UTC, naturetime10 commented on apps/github/app_api.go
> +			err = errs.FromGRPCErr(rpcErr)
Isn't error always set to `nil` if `rpcErr` is `nil`?

2023-03-10 05:42 UTC, naturetime10 commented on apps/github/app_api.go
> +			err = sqlErr
Isn't `err` always  set to `nil` in this case

2023-03-11 06:43 UTC, szheng2207 commented on apps/dao/github_pull_request.go
> +	FindPullRequestsMissingMetadata(ct context.Context) ([]entity.GithubPullRequest, *errs.Error)
Replaced this API with `FindAllPullRequests` and the filtering is done in the actual backfill business logic `BackfillPullRequestMetadata`.

2023-03-11 06:48 UTC, szheng2207 commented on apps/entity/github_pull_request.go
> +	RepositoryOwner *string
Changing struct field type to pointer in order to avoid following error when scanning query result with NULL value
```
converting NULL to string is unsupported
```

2023-03-11 06:57 UTC, naturetime10 requested changes

2023-03-11 06:57 UTC, naturetime10 commented on apps/dao/github_pull_request.go
> +	FindAllPullRequest(ct context.Context) ([]entity.GithubPullRequest, *errs.Error)
```suggestion
	FindAllPullRequests(ct context.Context) ([]entity.GithubPullRequest, *errs.Error)
```

2023-03-11 06:57 UTC, naturetime10 commented on apps/dao/sqldb/github_installation.go
> +			Message: fmt.Sprintf("installation not found, team_id=%d", teamID),
```suggestion
			Message: fmt.Sprintf("installation not found: teamID=%d", teamID),
```

2023-03-11 06:57 UTC, naturetime10 commented on apps/dao/sqldb/github_pull_request.go
> +	var prs []entity.GithubPullRequest
```suggestion
	var pullRequests []entity.GithubPullRequest
```

2023-03-11 06:57 UTC, naturetime10 commented on apps/dao/sqldb/github_pull_request.go
> +		var pr entity.GithubPullRequest
```suggestion
		var pullRequest entity.GithubPullRequest
```

2023-03-11 06:57 UTC, naturetime10 commented on apps/entity/github_pull_request.go
> +		*g.OrganizationID,
This could call `nil` pointer dereferencing.

2023-03-11 06:57 UTC, naturetime10 commented on apps/github/app_api.go
> +	prs = collect.Filter(prs, func(pr entity.GithubPullRequest) bool {
```suggestion
	pullRequests = collect.Filter(prs, func(pr entity.GithubPullRequest) bool {
```

2023-03-11 06:57 UTC, naturetime10 commented on apps/github/app_api.go
> +		return pr.RepositoryName == nil ||
```suggestion
		return pullRequest.RepositoryName == nil ||
```

2023-03-11 06:57 UTC, naturetime10 commented on apps/github/app_api.go
> +	for _, pr := range prs {
```suggestion
	for _, pullRequest := range prs {
```

2023-03-11 07:28 UTC, naturetime10 commented on apps/entity/github_pull_request.go
> +		"[GithubPullRequest NodeID:%s InternalTaskID:%d RepositoryOwner:%s RepositoryName:%s Number:%d URL:%s OrganizationID:%d]",
Can we use `%v`

2023-03-11 07:44 UTC, naturetime10 approved these changes

2023-03-11 08:00 UTC, naturetime10 approved these changes

2023-03-11 08:00 UTC, merged