Remove transaction use for single query APIs
teamyapp/teamy-backend pull request #398
Opened 2023-03-12 23:13 UTC by Junoth

Add non-transactional query methods in daoV2. 
Use non-transactional query methods for single query APIs.

2023-03-14 02:22 UTC, naturetime10 requested changes
Left a comment

2023-03-14 02:22 UTC, naturetime10 commented on core/daov2/sqldb/sprint_participant.go
> +func (s SprintParticipant) FindParticipantIDsBySprintID(ct context.Context, sprintID uint64) ([]uint64, *errs.Error) {
I wonder whether we can invoke `FindParticipantIDsBySprintIDWithTx` inside of this method instead of reimplementing the logic?

2023-03-14 03:50 UTC, Junoth commented on core/daov2/sqldb/sprint_participant.go
> +func (s SprintParticipant) FindParticipantIDsBySprintID(ct context.Context, sprintID uint64) ([]uint64, *errs.Error) {
You mean we start a tx inside of this method and call FindParticipantIDsBySprintIDWithTx? I think it's doable

Though I think some duplicate is fine since DAO method is relatively small and we'll only create non-transactional read methods when needed.

2023-03-14 05:50 UTC, naturetime10 approved these changes

2023-03-14 05:50 UTC, naturetime10 commented on core/daov2/sqldb/sprint_participant.go
> +func (s SprintParticipant) FindParticipantIDsBySprintID(ct context.Context, sprintID uint64) ([]uint64, *errs.Error) {
Discussed offline. Will call `FindParticipantIDsBySprintIDWithTx` in side `FindParticipantIDsBySprintID` to encourage code reuse and measure latency moving forwards.

2023-03-15 00:45 UTC, naturetime10 requested changes
Let's invoke transaction APIs in side non transaction APIs.

2023-03-19 06:24 UTC, naturetime10 requested changes

2023-03-19 06:24 UTC, naturetime10 commented on core/daov2/sqldb/sprint.go
> +	}
```suggestion
	if err != nil {
		return entity.Sprint{}, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:24 UTC, naturetime10 commented on core/daov2/sqldb/sprint.go
> +	}
```suggestion
	if err != nil {
		return nil, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:24 UTC, naturetime10 commented on core/daov2/sqldb/sprint.go
> +	}
```suggestion
	if err != nil {
		return nil, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:24 UTC, naturetime10 commented on core/daov2/sqldb/sprint_participant.go
> +	}
```suggestion
	if err != nil {
		return nil, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:24 UTC, naturetime10 commented on core/daov2/sqldb/sprint_participant.go
> +	}
```suggestion
	if err != nil {
		return nil, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:24 UTC, naturetime10 commented on core/daov2/sqldb/sprint_participant.go
> +	}
```suggestion
	if err != nil {
		return nil, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:24 UTC, naturetime10 commented on core/daov2/sqldb/task.go
> +	}
```suggestion
	if err != nil {
		return nil, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:24 UTC, naturetime10 commented on core/daov2/sqldb/task.go
> +	}
```suggestion
	if err != nil {
		return nil, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:24 UTC, naturetime10 commented on core/daov2/sqldb/task.go
> +	}
```suggestion
	if err != nil {
		return nil, err
	}
	
	defer tx.Rollback()
```

2023-03-19 21:40 UTC, naturetime10 approved these changes

2023-03-19 21:40 UTC, naturetime10 commented on core/daov2/sqldb/sprint.go
> +
```suggestion
```

2023-03-19 21:40 UTC, naturetime10 commented on core/daov2/sqldb/sprint.go
> +
```suggestion
```

2023-03-19 21:40 UTC, naturetime10 commented on core/daov2/sqldb/sprint.go
> +
```suggestion
```

2023-03-19 21:40 UTC, naturetime10 commented on core/daov2/sqldb/sprint_participant.go
> +
```suggestion
```

2023-03-19 21:40 UTC, naturetime10 commented on core/daov2/sqldb/sprint_participant.go
> +
```suggestion
```

2023-03-19 21:40 UTC, naturetime10 commented on core/daov2/sqldb/sprint_participant.go
> +
```suggestion
```

2023-03-19 21:40 UTC, naturetime10 commented on core/daov2/sqldb/task.go
> +
```suggestion
```

2023-03-19 21:40 UTC, naturetime10 commented on core/daov2/sqldb/task.go
> +
```suggestion
```

2023-03-19 22:10 UTC, merged