Backfill Github organization ID in apps_github_pull_request table
teamyapp/teamy-backend pull request #403
Opened 2023-03-15 06:52 UTC by szheng2207

2023-03-15 07:17 UTC, naturetime10 requested changes

2023-03-15 07:17 UTC, naturetime10 commented on apps/github/app_api.go
> +		orgID, err := a.githubRestAPI.GetOrgIDByOrgName(ct, ins, node.Repository.Owner.Login)
```suggestion
		orgID, err := a.githubRestAPI.GetOrganizationIDByLogin(ct, ins, node.Repository.Owner.Login)
```

2023-03-15 07:17 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +		}
```suggestion
		internalErr := errs.NewError(errs.Unknown, err.Error())
```

Let's use `NewError` constructor to include stack trace in error.

2023-03-15 07:17 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", accessToken))
```suggestion
	}
	
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", accessToken))
```

2023-03-15 07:17 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +		}
```suggestion
		internalErr := errs.NewError(errs.Unknown, err.Error())
```

2023-03-15 07:17 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +		}
```suggestion
		return 0, internalErr := errs.NewError(errs.NotFound, "Not found")
```

2023-03-15 07:17 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +		}
```suggestion
		internalErr = errs.NewError(errs.IO, err.Error())
```

2023-03-15 07:17 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +func (r RestAPI) GetOrgIDByOrgName(ct context.Context, installation *Installation, orgName string) (uint64, *errs.Error) {
```suggestion
func (r RestAPI) GetOrganizationByLogin(ct context.Context, installation *Installation, orgName string) (uint64, *errs.Error) {
```

2023-03-15 07:17 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +func (r RestAPI) GetOrgIDByOrgName(ct context.Context, installation *Installation, orgName string) (uint64, *errs.Error) {
Let's return the complete organization info instead of just the `ID` so that we can reuse this API in the future.

2023-03-15 07:17 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +		}
```suggestion
		internalErr = errs.NewError(errs.Deserialization , err.Error())
```

2023-03-16 04:33 UTC, szheng2207 commented on apps/github/client/rest_api.go
> +		}
Can we make this change part of the refactor later? 
```
internalErr := errs.NewError(errs.Unknown, err.Error())
```
returns Error struct, but the log and return value expect pointers.

2023-03-16 04:36 UTC, szheng2207 commented on apps/github/client/rest_api.go
> +		}
I changed it back to `EmbedErr: err,` to make it consistent with the rest of the code.

2023-03-16 04:51 UTC, szheng2207 commented on apps/github/client/rest_api.go
> +func (r RestAPI) GetOrgIDByOrgName(ct context.Context, installation *Installation, orgName string) (uint64, *errs.Error) {
I see we already have an `organization` struct in `github` package so I can reuse it. But then it has an issue of introducing import cycle. For this PR I moved `organization` into a new package called `entity`. I will have a follow-up PR to move other github entities into this new package once this PR is merged. Let me know your thought.

2023-03-17 05:19 UTC, naturetime10 requested changes

2023-03-17 05:19 UTC, naturetime10 commented on apps/github/app_api.go
> +	githubRestAPI               client.RestAPI
```suggestion
	githubRESTAPI               client.RESTAPI
```

2023-03-17 05:19 UTC, naturetime10 commented on apps/dep/wire.go
> +		client.NewRestAPI,
```suggestion
		client.NewRESTAPI,
```

2023-03-17 05:19 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +type RestAPI struct {
```suggestion
type RESTAPI struct {
```

2023-03-17 05:23 UTC, naturetime10 requested changes

2023-03-17 05:23 UTC, naturetime10 commented on apps/github/app_api.go
> +		orgID, err := a.githubRestAPI.GetOrganizationIDByLogin(ct, ins, node.Repository.Owner.Login)
```suggestion
		org, err := a.githubRESTAPI.GetOrganizationByLogin(ct, ins, node.Repository.Owner.Login)
```

2023-03-17 05:23 UTC, naturetime10 commented on apps/github/app_api.go
> +	githubRestAPI client.RestAPI,
```suggestion
	githubRESTAPI client.RESTAPI,
```

2023-03-17 05:23 UTC, naturetime10 commented on apps/github/app_api.go
> +		githubRestAPI:               githubRestAPI,
```suggestion
		githubRESTAPI:               githubRESTAPI,
```

2023-03-17 05:23 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +func (r RestAPI) GetOrganizationIDByLogin(ct context.Context, installation *Installation, orgName string) (uint64, *errs.Error) {
```suggestion
func (r RestAPI) GetOrganizationByLogin(ct context.Context, installation *Installation, login string) (entity.Organization, *errs.Error) {
```

2023-03-17 05:23 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +	url := fmt.Sprintf("https://api.github.com/orgs/%s", orgName)
```suggestion
	url := fmt.Sprintf("https://api.github.com/orgs/%s", login)
```

2023-03-17 05:23 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +	if res.StatusCode == http.StatusNotFound {
I think we should check common status codes mention in the doc.

2023-03-17 05:23 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +func NewRestAPI(dataCollector telemetry.DataCollector, httpClient web.HTTPClient) RestAPI {
```suggestion
func NewRESTAPI(dataCollector telemetry.DataCollector, httpClient web.HTTPClient) RestAPI {
```

2023-03-17 05:23 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +	return RestAPI{
```suggestion
	return RESTAPI{
```

2023-03-17 05:31 UTC, szheng2207 commented on apps/github/client/rest_api.go
> +	if res.StatusCode == http.StatusNotFound {
The doc only mentioned this error code for this API. 
https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#get-an-organization

2023-03-17 06:03 UTC, naturetime10 requested changes

2023-03-17 06:03 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +		return entity.Organization{}, internalErr
```suggestion
		return entity.Organization{}, errs.NewError(errs.Unknown, "Unknown")
```

2023-03-17 06:03 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +		}
```suggestion
		}
```

2023-03-17 06:07 UTC, naturetime10 requested changes

2023-03-17 06:07 UTC, naturetime10 commented on apps/github/client/rest_api.go
> +		return entity.Organization{}, errs.NewError(errs.Unknown, "Unknown")
```suggestion
		}
		
		return entity.Organization{}, errs.NewError(errs.Unknown, "Unknown")
```

2023-03-17 06:08 UTC, naturetime10 approved these changes

2023-03-17 06:12 UTC, merged