Integrate user service with transaction
teamyapp/teamy-backend pull request #404
Opened 2023-03-16 06:34 UTC by Junoth

Tested in Imsonia
<img width="1677" alt="Screen Shot 2023-03-15 at 11 32 07 PM" src="https://user-images.githubusercontent.com/36186063/225534075-13d1f6b8-adca-443f-bc0c-d91c38024bce.png">
<img width="1682" alt="Screen Shot 2023-03-15 at 11 31 14 PM" src="https://user-images.githubusercontent.com/36186063/225534084-83aba005-24cd-4db8-a0bd-dcbac3403e47.png">
<img width="1675" alt="Screen Shot 2023-03-15 at 11 30 40 PM" src="https://user-images.githubusercontent.com/36186063/225534086-aed0a8bb-6575-48d9-bc11-ba5bbba3978a.png">
<img width="1678" alt="Screen Shot 2023-03-15 at 11 30 24 PM" src="https://user-images.githubusercontent.com/36186063/225534091-0c0971d2-b470-4a84-9cbf-4f82ad01ad3c.png">
<img width="1677" alt="Screen Shot 2023-03-15 at 11 30 03 PM" src="https://user-images.githubusercontent.com/36186063/225534094-7d161c21-c842-45ee-9d0c-f13149c20cab.png">

Also verified error change in the log. The error was logged only once and took correct stacktrace
```
(HappenAt:2023-03-16 06:12:19.261132 +0000 UTC) (Severity:Error) (FileName:/Users/yuhangmiao/Junoth/Proj/teamyapp/teamy-backend/core/api/gql/query.go) (LineNumber:18) (TraceId:00000000000000000000000000000000) (SpanId:0000000000000000) (RequestId:76a77f90-4c62-44d6-baa0-b4af49ae2e0a) (Cause:[Code=Unauthenticated Message=user ID not found EmbedErr=nil, StackTrace=/Users/yuhangmiao/Junoth/Proj/teamyapp/teamy-backend/core/service/user.go:48 User.Me
/Users/yuhangmiao/Junoth/Proj/teamyapp/teamy-backend/core/api/gql/query.go:16 Query.Me
/usr/local/opt/go/libexec/src/reflect/value.go:586 Value.call
/usr/local/opt/go/libexec/src/reflect/value.go:370 Value.Call
/Users/yuhangmiao/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.5.0/internal/exec/exec.go:211 execFieldSelection.func2
/Users/yuhangmiao/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.5.0/internal/exec/exec.go:231 execFieldSelection])
```

2023-03-16 06:35 UTC, Junoth commented on core/daov2/daotestv2/user.go
> +	//TODO implement me
@magicoder10 Do you want me to add unit tests in this PR or have a separate one to add unit tests in DAO?

2023-03-16 06:37 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +	//TODO implement me
@Junoth Can we add in this PR?

2023-03-19 02:26 UTC, naturetime10 requested changes

2023-03-19 02:26 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +	return u.FindUserByIDWithTx(ct, tx, userID)
```suggestion
	}
	
	return u.FindUserByIDWithTx(ct, tx, userID)
```

2023-03-19 02:26 UTC, naturetime10 commented on core/daov2/daotestv2/team_member.go
> +			return nil
Return not found error?

2023-03-19 02:26 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +			}
Can we convert userIDs into map and do a single for loop of rows to find all users?

2023-03-19 02:26 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +					return errs.NewError(errs.Unknown, fmt.Sprintf("row already exist: userID=%v", user.ID))
```suggestion
					return errs.NewError(errs.AlreadyExists, fmt.Sprintf("row already exist: userID=%v", user.ID))
```

2023-03-19 02:26 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +	}
Can we call `FindUserByIDWithTx` here instead?

2023-03-19 02:26 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +			for i, row := range table.Rows {
```suggestion
			for index, row := range table.Rows {
```

2023-03-19 02:26 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +			for i, row := range table.Rows {
```suggestion
			for index, row := range table.Rows {
```

2023-03-19 02:26 UTC, naturetime10 commented on core/daov2/daotestv2/user_file_upload_session.go
> +func (u UserFileUploadSession) FindUserFileUploadSessionByUserIDWithTx(ct context.Context, tx *transaction.Transaction, userID uint64, userFileUploadSessionType entity.UserFileUploadSessionType, file
```suggestion
func (u UserFileUploadSession) FindUserFileUploadSessionByUserIDWithTx(
    ct context.Context, 
    tx *transaction.Transaction, 
    userID uint64, 
    userFileUploadSessionType entity.UserFileUploadSessionType, 
    fileUploadSessionID uint64,
) (entity.UserFileUploadSession, *errs.Error) {
```

2023-03-19 05:04 UTC, Junoth commented on core/daov2/daotestv2/user.go
> +			}
sure

2023-03-19 05:04 UTC, Junoth commented on core/daov2/daotestv2/team_member.go
> +			return nil
I was trying to mimic the sqldb where we return Unknown error

2023-03-19 05:12 UTC, Junoth commented on core/daov2/daotestv2/user.go
> +	}
updated

2023-03-19 05:31 UTC, naturetime10 requested changes

2023-03-19 05:31 UTC, naturetime10 commented on core/daov2/daotestv2/team_member.go
> +			return nil
@Junoth I was wrong.

2023-03-19 05:31 UTC, naturetime10 commented on core/daov2/daotestv2/team_member.go
> +					return nil
```suggestion
```

2023-03-19 05:38 UTC, naturetime10 requested changes

2023-03-19 05:38 UTC, naturetime10 commented on core/daov2/daotestv2/team_member.go
> +					return nil
A user can be inside many teams.

2023-03-19 05:39 UTC, naturetime10 commented on core/daov2/daotestv2/team_member.go
> +			return nil
@Junoth Sorry, I was wrong.

2023-03-19 06:21 UTC, naturetime10 requested changes

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +	}
```suggestion
	if err != nil {
		return entity.User{}, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +
```suggestion
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +					return nil
```suggestion
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +			return errs.NewError(errs.Unknown, fmt.Sprintf("row not exist: userID=%v", user.ID))
```suggestion
			return errs.NewError(errs.NotFound, fmt.Sprintf("row not exist: userID=%v", user.ID))
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/daotestv2/user_file_upload_session.go
> +					return errs.NewError(errs.Unknown, fmt.Sprintf("row already exist: userID=%v, userFileUploadSessionType=%v, fileUploadSessionID=%v",
```suggestion
					return errs.NewError(errs.AlreadyExists, fmt.Sprintf("row already exist: userID=%v, userFileUploadSessionType=%v, fileUploadSessionID=%v",
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/daotestv2/user_file_upload_session.go
> +			table.Rows = table.Rows[:len(table.Rows)-1]
We can't assume the last record is the previously created one. Need to filter out that row instead.

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/daotestv2/user_file_upload_session.go
> +			return errs.NewError(errs.Unknown, fmt.Sprintf("row not exist: userID=%v, userFileUploadSessionType=%v, fileUploadSessionID=%v",
```suggestion
			return errs.NewError(errs.NotFound, fmt.Sprintf("row not exist: userID=%v, userFileUploadSessionType=%v, fileUploadSessionID=%v",
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/daotestv2/user_file_upload_session.go
> +					table.Rows[i] = oldFileUploadSession
```suggestion
					table.Rows[i] = oldFileUploadSession
					return nil
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/daotestv2/user_file_upload_session.go
> +			for i, row := range table.Rows {
```suggestion
			for index, row := range table.Rows {
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/sqldb/user.go
> +	}
```suggestion
	if err != nil {
		return entity.User{}, err
	}
	
	defer tx.Rollback()
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/sqldb/user.go
> +	_, err := tx.SQLTx().Exec(`
```suggestion

	_, err := tx.SQLTx().Exec(`
```

2023-03-19 06:21 UTC, naturetime10 commented on core/daov2/sqldb/user_file_upload_session.go
> +		userID, userFileUploadSessionType, fileUploadSessionID).
```suggestion
		userID, 
		userFileUploadSessionType, 
		fileUploadSessionID).
```

2023-03-19 06:21 UTC, naturetime10 commented on core/mutation/update_user_mutation.go
> +	teamIDs, err := u.teamMemberDaoV2.FindTeamIDsByUserID(ct, tx, u.user.ID)
Can we include this for all mutations in case we use it in the future so that we won't forget anything?
```
if c.notifiersPrepared {
	return nil
}
```

2023-03-19 06:21 UTC, naturetime10 commented on core/realtime/state_syncer.go
> +	teamIDs, err := s.teamMemberDao.FindTeamIDsByUserID(ct, userID)
Let's handle error before calling the next line.

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user.go
> +		updatedAt := time.Now()
```suggestion
		updatedAt := time.Now().UTC()
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user.go
> +		now := time.Now()
```suggestion
		now := time.Now().UTC()
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		SlackClientSecret:        "Slack",
```suggestion
		SlackClientSecret:        "SlackSecret",
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, internalErr)
```suggestion
	assert.Nil(t, internalErr)
	if internalErr != nil {
	    return
	}
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, err)
```suggestion
	assert.Nil(t, err)
	if err != nil {
	    return
	}
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		LastName:   "test_lastname",
```suggestion
		LastName:   "LastName",
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		FirstName:  "test_firstname",
```suggestion
		FirstName:  "FirstName",
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, internalErr)
```suggestion
	assert.Nil(t, internalErr)
	if internalErr != nil {
	    return
	}
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, err)
```suggestion
	assert.Nil(t, err)
	if err != nil {
	    return;
	}
	
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		LastName:   "test_lastname",
```suggestion
		LastName:   "LastName",
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		FirstName:  "test_firstname",
```suggestion
		FirstName:  "FirstName",
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, userService.userDaoV2.CreateUser(ct, tx, user))
We need to return if `CreateUser` has error

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		LastName:  "test_lastname_updated",
```suggestion
		LastName:  "LastNameUpdated",
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		FirstName: "test_firstname_updated",
```suggestion
		FirstName: "FirstNameUpdated",
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, internalErr)
```suggestion
	assert.Nil(t, internalErr)
	if internalErr == nil {
	    return
	}
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.NotNil(t, updatedUser.UpdatedAt)
Let's use create a helper.

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	updateTime := time.Now().UTC()
```suggestion
	now := time.Now().UTC()
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		CreatedAt:  time.Now().UTC(),
```suggestion
		CreatedAt:  now,
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		UpdatedAt:  &updateTime,
```suggestion
		UpdatedAt:  &now,
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, err)
```suggestion
	assert.Nil(t, err)
	if err != nil {
	    return
	}
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, userService.userDaoV2.CreateUser(ct, tx, user))
We need to return if this has error.

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	userFound, internalErr := userService.FindUserByID(ct, user.ID)
We need to return if this has error.

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, err)
Return if err != nil

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, err)
Return if err != nil

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	updateTime := time.Now().UTC()
```suggestion
	now := time.Now().UTC()
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		CreatedAt:  time.Now().UTC(),
```suggestion
		CreatedAt:  now,
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +		UpdatedAt:  &updateTime,
```suggestion
		UpdatedAt:  &now,
```

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Nil(t, userService.userDaoV2.CreateUser(ct, tx, user))
Return if err != nil

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	uploadSessionID, err := userService.CreateUserProfileUploadSession(ct)
Return if err != nil

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	updatedUser, err := userService.FinishUserProfileUploadSession(ct, uploadSessionID)
Return if err != nil

2023-03-19 06:21 UTC, naturetime10 commented on core/service/user_test.go
> +	assert.Equal(t, uploadSessionInMemory.IsCompleted, true)
Can we assert the above fields also? Thanks!

2023-03-19 20:55 UTC, Junoth commented on core/service/user_test.go
> +	assert.Equal(t, uploadSessionInMemory.IsCompleted, true)
sure

2023-03-19 20:56 UTC, Junoth commented on core/service/user_test.go
> +	updatedUser, err := userService.FinishUserProfileUploadSession(ct, uploadSessionID)
What does this mean?

2023-03-19 20:56 UTC, Junoth commented on core/service/user_test.go
> +	uploadSessionID, err := userService.CreateUserProfileUploadSession(ct)
What does this mean?

2023-03-19 20:57 UTC, Junoth commented on core/daov2/daotestv2/user.go
> +					return nil
removed

2023-03-19 20:58 UTC, Junoth commented on core/daov2/daotestv2/user.go
> +			return errs.NewError(errs.Unknown, fmt.Sprintf("row not exist: userID=%v", user.ID))
I think we need to follow what sqldb does

2023-03-19 20:58 UTC, Junoth commented on core/service/user_test.go
> +		UpdatedAt:  &updateTime,
I don't get this change

2023-03-19 21:01 UTC, naturetime10 commented on core/daov2/daotestv2/user.go
> +			return errs.NewError(errs.Unknown, fmt.Sprintf("row not exist: userID=%v", user.ID))
Can we fix sqlDB?

2023-03-19 21:03 UTC, Junoth commented on core/service/user_test.go
> +		UpdatedAt:  &updateTime,
nvm, i saw the new change after rebase. Updated

2023-03-26 08:09 UTC, naturetime10 approved these changes

2023-03-26 08:09 UTC, naturetime10 commented on core/daov2/sqldb/team_member.go
> +
```suggestion
```

2023-03-26 08:09 UTC, naturetime10 commented on core/service/user.go
```suggestion
```

2023-03-26 08:09 UTC, naturetime10 commented on core/service/user.go
> +		err = userMutation.ExecuteV2(ct, tx)
```suggestion
		return userMutation.ExecuteV2(ct, tx)
```

2023-03-26 08:09 UTC, naturetime10 commented on core/service/user.go
> +		}
```suggestion
```

2023-03-26 08:09 UTC, naturetime10 commented on core/service/user.go
> +		return nil
```suggestion
```

2023-03-26 08:09 UTC, naturetime10 commented on core/service/user.go
> +		err := u.userFileUploadSessionDaoV2.CreateUserFileUploadSession(ct, tx, fileUploadSession)
```suggestion
		return u.userFileUploadSessionDaoV2.CreateUserFileUploadSession(ct, tx, fileUploadSession)
```

2023-03-26 08:09 UTC, naturetime10 commented on core/service/user.go
> +		return nil
```suggestion
```

2023-03-26 08:09 UTC, naturetime10 commented on core/service/user_test.go
> +
```suggestion
```

2023-03-26 18:33 UTC, merged