Refactor errors in apps
teamyapp/teamy-backend pull request #420
Opened 2023-04-02 22:06 UTC by duanxianbo

(task:13688)

2023-04-02 22:30 UTC, szheng2207 commented on apps/dao/sqldb/github_code_review.go
> -		g.dataCollector.Logger.ErrorWithContext(ct, internalErr)
I think the log should not be removed?

2023-04-02 22:31 UTC, naturetime10 requested changes

2023-04-02 22:31 UTC, naturetime10 commented on apps/dao/sqldb/github_code_review.go
> +			return entity.GithubCodeReview{}, errs.NewError(errs.NotFound, fmt.Sprintf(
```suggestion
			return entity.GithubCodeReview{}, errs.NewError(
			    errs.NotFound, 
			    fmt.Sprintf(
```

2023-04-02 22:31 UTC, naturetime10 commented on apps/dao/sqldb/github_code_review.go
> +			return entity.GithubCodeReview{}, errs.NewError(errs.NotFound, fmt.Sprintf(
```suggestion
			return entity.GithubCodeReview{}, errs.NewError(
			    errs.NotFound, 
			    fmt.Sprintf(
```

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
>  		errs.SetHTTPErr(internalErr, writer)
We do need to log here, or we will lose stack trace.

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
> +		task, _ := a.teamyClientRegistry.TaskClient().GetTask(ct, getTaskReq)
Need to handler error

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
> +		node, _ := a.githubGraphQLAPI.GetPullRequestByNodeID(ct, ins, pullRequest.NodeID)
Need to handler error

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
> +		org, _ := a.githubRESTAPI.GetOrganizationByLogin(ct, ins, node.Repository.Owner.Login)
Need to handler error

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
> +		a.githubPullRequestDao.UpdatePullRequest(ct, gpr)
Need to handler error

2023-04-02 22:31 UTC, naturetime10 commented on apps/github/app_api.go
> +			a.tryCreateTaskForPullRequestReviewer(ct, teamID, prEvt.PullRequest.NodeID, prTaskRelation.InternalTaskID, githubReviewer.NodeID, evt, prEvt)
Need to handler error

2023-04-02 22:32 UTC, naturetime10 commented
We please format `NewError` also. Thanks.

2023-04-03 01:18 UTC, duanxianbo commented on apps/dao/sqldb/github_code_review.go
> -		g.dataCollector.Logger.ErrorWithContext(ct, internalErr)
this one should be removed, we will log it in the api level

2023-04-03 01:23 UTC, duanxianbo commented on apps/github/app_api.go
> +		task, _ := a.teamyClientRegistry.TaskClient().GetTask(ct, getTaskReq)
you mean to log?

2023-04-03 01:38 UTC, duanxianbo commented on apps/github/app_api.go
> +		task, _ := a.teamyClientRegistry.TaskClient().GetTask(ct, getTaskReq)
log added

2023-04-03 01:38 UTC, duanxianbo commented
> NewError

what do you mean by formating newError?

2023-04-03 02:10 UTC, naturetime10 approved these changes

2023-04-03 02:10 UTC, merged