Implement txn in invitation service
teamyapp/teamy-backend pull request #421
Opened 2023-04-02 22:44 UTC by Junoth

Tested in Insomnia and also added unit tests
<img width="1680" alt="Screen Shot 2023-04-02 at 3 34 45 PM" src="https://user-images.githubusercontent.com/36186063/229383099-95a89377-2380-4a03-bea5-ed3d6b948de6.png">
<img width="1687" alt="Screen Shot 2023-04-02 at 3 38 41 PM" src="https://user-images.githubusercontent.com/36186063/229383100-ad039ee9-1c56-414a-822e-1826f0681079.png">
<img width="1682" alt="Screen Shot 2023-04-02 at 3 39 23 PM" src="https://user-images.githubusercontent.com/36186063/229383103-12c9a3c9-deb6-4896-8a30-d230395a4418.png">
<img width="1680" alt="Screen Shot 2023-04-02 at 3 39 47 PM" src="https://user-images.githubusercontent.com/36186063/229383104-543d76c4-7090-49d9-9a0f-e268e943ab0b.png">
<img width="1683" alt="Screen Shot 2023-04-02 at 3 40 21 PM" src="https://user-images.githubusercontent.com/36186063/229383105-13163c19-95ef-48ae-ad95-d8bd5bf678ec.png">
<img width="1685" alt="Screen Shot 2023-04-02 at 3 40 30 PM" src="https://user-images.githubusercontent.com/36186063/229383108-c6ce34a9-a2bb-45da-87a1-966c14897bc1.png">

(task:13707)

2023-04-03 04:46 UTC, naturetime10 requested changes

2023-04-03 04:46 UTC, naturetime10 commented on core/daov2/daotestv2/invitation.go
> +			}
Let's use `NewError`

2023-04-03 04:46 UTC, naturetime10 commented on core/daov2/sqldb/invitation.go
> +			return entity.Invitation{}, errs.NewError(errs.NotFound, fmt.Sprintf("invitation not found: invitationID=%v", invitationID))
```suggestion
			return entity.Invitation{}, errs.NewError(
			    errs.NotFound, 
			    fmt.Sprintf("invitation not found: invitationID=%v", invitationID))
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation.go
> +			return entity.Invitation{}, errs.NewError(errs.PermissionDenied, fmt.Sprintf("permission denied: authorization query=%v", query))
```suggestion
			return entity.Invitation{}, errs.NewError(
			    errs.PermissionDenied, 
			    fmt.Sprintf("permission denied: authorization query=%v", query))
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation.go
> +			return entity.Invitation{}, errs.NewError(errs.PermissionDenied, fmt.Sprintf("permission denied: authorization query=%v", query))
```suggestion
			return entity.Invitation{}, errs.NewError(
			    errs.PermissionDenied, 
			    fmt.Sprintf("permission denied: authorization query=%v", query))
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation.go
> +		return entity.Invitation{}, errs.NewError(errs.PermissionDenied, fmt.Sprintf("invalid invitation code: invitationID=%v, invitationCode=%v",
```suggestion
		return entity.Invitation{}, errs.NewError(
		    errs.InvalidArgument, 
		    fmt.Sprintf("invalid invitation code: invitationID=%v, invitationCode=%v",
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation.go
> +
```suggestion
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation.go
> +
```suggestion
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation.go
> +
```suggestion
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation.go
> +		return errs.NewError(errs.InvalidOperation, fmt.Sprintf("invitation is already responded: invitationID=%v", invitation.ID))
```suggestion
		return errs.NewError(
		    errs.InvalidOperation, 
		    fmt.Sprintf("invitation is already responded: invitationID=%v", invitation.ID))
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation.go
> +		return errs.NewError(errs.InvalidOperation, fmt.Sprintf("invitation is expired: invitationID=%v", invitation.ID))
```suggestion
		return errs.NewError(
		    errs.InvalidOperation, 
		    fmt.Sprintf("invitation is expired: invitationID=%v", invitation.ID))
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation.go
> +		return errs.NewError(errs.InvalidOperation, fmt.Sprintf("invitation is revoked: invitationID=%v", invitation.ID))
```suggestion
		return errs.NewError(
		    errs.InvalidOperation, 
		    fmt.Sprintf("invitation is revoked: invitationID=%v", invitation.ID))
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +
```suggestion
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	invitationFound, internalErr = invitationRef.invitationService.FindInvitationsInTeam(ct, teamID1, &filter2)
```suggestion
	invitationsFound, internalErr = invitationRef.invitationService.FindInvitationsInTeam(ct, teamID1, &filter2)
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, 0, len(invitationFound))
```suggestion
	assert.Equal(t, 0, len(invitationsFound))
```

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, *(invitation2.UpdatedAt), *(invitationFound[0].UpdatedAt))
Can we create a helper function for this to encourage code reuse?

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, *(invitation2.UpdatedAt), *(invitationFound[0].UpdatedAt))
Let's use the previously created helper function here

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, invitation.CreatedAt, accepted.CreatedAt)
Let's use previously created helper function

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.NotNil(t, invitationInMemory.UpdatedAt)
Let's use previously created helper function

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.NotNil(t, accepted.UpdatedAt)
Let's use previously created helper function

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.NotNil(t, invitationInMemory.UpdatedAt)
Let's use previously created helper function

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, invitation.CreatedAt, deleted.CreatedAt)
Let's use previously created helper function

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.NotNil(t, invitationInMemory.UpdatedAt)
Let's use previously created helper function

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.NotNil(t, updated.UpdatedAt)
Let's use previously created helper function

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Nil(t, invitationInMemory.UpdatedAt)
Let's use previously created helper function

2023-04-03 04:46 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Nil(t, invitation.UpdatedAt)
Let's use previously created helper function

2023-04-07 06:04 UTC, naturetime10 requested changes

2023-04-07 06:04 UTC, naturetime10 commented on core/daov2/sqldb/invitation.go
> +	    team_id,
```suggestion
	        id,
		sender_user_id,
		receiver_first_name,
	 	receiver_last_name,
		receiver_email,
	        team_id,
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation.go
> +
```suggestion
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation.go
> +
```suggestion
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation.go
> +				CreatedAt: time.Now().UTC(),
```suggestion
				CreatedAt: now,
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation.go
> +					CreatedAt: time.Now().UTC(),
```suggestion
					CreatedAt: now,
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation_test.go
> +		if !(one.ReceiverUserID == nil && other.ReceiverUserID == nil) {
```suggestion
		if one.ReceiverUserID != nil || other.ReceiverUserID != nil {
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation_test.go
> +		if !(one.ReceiverLastName == nil && other.ReceiverLastName == nil) {
```suggestion
		if one.ReceiverLastName != nil || other.ReceiverLastName != nil) {
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation_test.go
> +		if *(one.ReceiverUserID) != *(other.ReceiverUserID) {
```suggestion
		if *one.ReceiverUserID) != *other.ReceiverUserID {
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation_test.go
> +		if *(one.ReceiverLastName) != *(other.ReceiverLastName) {
```suggestion
		if *one.ReceiverLastName) != *other.ReceiverLastName) {
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation_test.go
> +		if !(one.ReceiverFirstName == nil && other.ReceiverFirstName == nil) {
```suggestion
		if one.ReceiverFirstName != nil || other.ReceiverFirstName != nil) {
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation_test.go
> +		if *(one.ReceiverFirstName) != *(other.ReceiverFirstName) {
```suggestion
		if *one.ReceiverFirstName != *other.ReceiverFirstName {
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation_test.go
> +		if !(one.ReceiverEmail == nil && other.ReceiverEmail == nil) {
```suggestion
		if one.ReceiverEmail != nil || other.ReceiverEmail != nil {
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation_test.go
> +		if *(one.ReceiverEmail) != *(other.ReceiverEmail) {
```suggestion
		if *one.ReceiverEmail != *other.ReceiverEmail {
```

2023-04-07 06:04 UTC, naturetime10 commented on core/service/invitation_test.go
> +	} else {
Maybe merge all 
```
else {
    if {}
}

to
else if {}
```
?

2023-04-07 06:07 UTC, naturetime10 requested changes

2023-04-07 06:07 UTC, naturetime10 commented on core/service/invitation_test.go
> +func isInvitationEqual(one entity.Invitation, other entity.Invitation) bool {
```suggestion
func areInvitationsEqual(one entity.Invitation, other entity.Invitation) bool {
```

2023-04-07 06:07 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, true, isInvitationEqual(invitation2, invitationsFound[0]))
assert.True

2023-04-07 06:07 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, true, isInvitationEqual(invitation, invitationInMemory))
assert.True

2023-04-07 06:07 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, errs.NotFound, err.Code)
```suggestion
	}
	
	assert.Equal(t, errs.NotFound, err.Code)
```

2023-04-07 06:07 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, true, isInvitationEqual(invitation, deleted))
assert.True

2023-04-07 06:07 UTC, naturetime10 commented on core/service/invitation_test.go
> +	assert.Equal(t, true, isInvitationEqual(invitation, invitationInMemory))
assert.True

2023-04-07 06:07 UTC, naturetime10 commented on core/service/invitation_test.go
> +// helper
```suggestion
```

2023-04-07 06:11 UTC, Junoth commented on core/daov2/sqldb/invitation.go
> +	    team_id,
This seems to be github format issue. I tried goland and vscode in my local machine and this looked good
<img width="708" alt="Screen Shot 2023-04-06 at 11 09 57 PM" src="https://user-images.githubusercontent.com/36186063/230552102-98d49d3b-9b92-47dd-a505-0d015d4281b1.png">

2023-04-07 07:05 UTC, naturetime10 approved these changes

2023-04-07 23:25 UTC, merged