Set and get team active sprint
teamyapp/teamy-backend pull request #439
Opened 2023-04-15 20:31 UTC by duanxianbo

(task:15602)

2023-04-16 01:22 UTC, duanxianbo commented
@magicoder10 it is ready for review

2023-04-16 22:59 UTC, naturetime10 requested changes
Let's make sure each Dao corresponds to 1 DB table and delegate business logic to service layer.

2023-04-16 22:59 UTC, naturetime10 commented on core/api/sprint_rpc.go
> +	sprint, err := s.sprintService.GetTeamActiveSprint(ct, req.TeamId)
```suggestion
	sprint, err := s.sprintService.GetActiveSprint(ct, req.TeamId)
```

2023-04-16 22:59 UTC, naturetime10 commented on core/daov2/sprint.go
> +	FindActiveSprintByTeamIDWithTx(ct context.Context, tx *transaction.Transaction, teamID uint64) (entity.Sprint, *errs.Error)
```suggestion
```

2023-04-16 22:59 UTC, naturetime10 commented on core/daov2/sqldb/team.go
> +
```suggestion
```

2023-04-18 08:27 UTC, naturetime10 requested changes

2023-04-18 08:27 UTC, naturetime10 commented on core/daov2/sqldb/sprint.go
> +
```suggestion
```

2023-04-18 08:27 UTC, naturetime10 commented on core/service/sprint.go
> +		updateTeamActiveSprintMutation := mutation.NewUpdateTeamActiveSprintMutation(
Should we use `update team mutation` instead?

2023-04-18 08:27 UTC, naturetime10 commented on core/service/sprint.go
> +func (s Sprint) GetActiveSprint(ct context.Context, teamID uint64) (*entity.Sprint, *errs.Error) {
Is this API actually needed for GraphQL API?

2023-04-19 00:36 UTC, duanxianbo commented on core/service/sprint.go
> +func (s Sprint) GetActiveSprint(ct context.Context, teamID uint64) (*entity.Sprint, *errs.Error) {
no, but it is needed in grpc service that is needed by github apps

2023-04-19 00:41 UTC, duanxianbo commented on core/service/sprint.go
> +		updateTeamActiveSprintMutation := mutation.NewUpdateTeamActiveSprintMutation(
I was thinking maybe we can make the payload less heavy, but actually the team has just a couple of more fields, will remove this and use update team mutation instead

2023-04-19 02:41 UTC, naturetime10 requested changes

2023-04-19 02:41 UTC, naturetime10 commented on core/realtime/collection.go
> +	TeamActiveSprintCollectionType     CollectionType = "TeamActiveSprint"
```suggestion
```

2023-04-19 02:41 UTC, naturetime10 commented on core/service/sprint.go
> +		updateTeamActiveSprintMutation := mutation.NewUpdateTeamActiveSprintMutation(
Let's use update Team mutation.

2023-04-19 02:41 UTC, naturetime10 commented on migrations/20230409101508_add_active_sprint_column.sql
> +	ADD active_sprint_id BIGINT REFERENCES sprint (id) ON UPDATE CASCADE ON DELETE CASCADE;
```suggestion
	ADD active_sprint_id BIGINT REFERENCES sprint (id) 
	    ON UPDATE CASCADE 
	    ON DELETE CASCADE;
```

2023-04-19 02:41 UTC, naturetime10 commented on core/service/sprint_test.go
> +			return "accessToken"
Need to generate this on the fly

2023-04-21 02:22 UTC, naturetime10 requested changes

2023-04-21 02:22 UTC, naturetime10 commented on core/service/sprint.go
> +
```suggestion
```

2023-04-21 02:22 UTC, naturetime10 commented on core/service/sprint.go
> +
```suggestion
```

2023-04-21 02:22 UTC, naturetime10 commented on core/service/sprint_test.go
> +	testkit.StartServiceInstance(cloudTestKitConfig, virtualNetwork, cloudTestKit.ServiceInstanceRunner)
```suggestion
	testkit.StartServiceInstance(cloudTestKitConfig, virtualNetwork, cloudTestKit.ServiceInstanceRunner)
	
	apiToken, internalErr := servicetest.GetServiceAccountAPIToken(cloudTestKit.IdentityService)
	if !assert.Nil(t, internalErr) {
		return SprintTestRef{}, false
	}
```

2023-04-21 02:22 UTC, naturetime10 commented on core/service/sprint_test.go
> +			now := time.Now()
```suggestion
			now := time.Now().UTC()
```

2023-04-21 02:22 UTC, naturetime10 commented on core/service/sprint_test.go
> +	teamyPrometheus := metricstest.NewNoopMetrics()
```suggestion
	noopMetrics := metricstest.NewNoopMetrics()
```

2023-04-21 02:22 UTC, naturetime10 commented on core/service/sprint_test.go
> +			if testCase.expectedErr != nil {
```suggestion
			if testCase.expectedSprint1Err != nil {
```

2023-04-21 02:22 UTC, naturetime10 commented on core/service/sprint_test.go
> +			if testCase.expectedErr != nil {
```suggestion
			if testCase.expectedSprint2Err != nil {
```

2023-04-22 02:50 UTC, duanxianbo commented
@magicoder10

2023-04-22 05:40 UTC, naturetime10 requested changes

2023-04-22 05:40 UTC, naturetime10 commented on core/service/sprint.go
> +
```suggestion
```

2023-04-22 05:41 UTC, naturetime10 approved these changes

2023-04-22 10:21 UTC, merged