Insert task link in PR description
teamyapp/teamy-backend pull request #454
Opened 2023-07-25 08:13 UTC by yijia-cc

Insert teamy clickable task link in pull request description

Tested 
- create PR without description will have automatic tracking task 
- close PR and will automatically delete automatic tracking task
- multiple task can be mentioned in a single PR
- manually link task, non automatic tracking task will not be deleted when PR is closed

(task:16811)

2023-07-26 02:59 UTC, duanxianbo approved these changes

2023-07-26 03:02 UTC, naturetime10 requested changes

2023-07-26 03:02 UTC, naturetime10 commented on apps/github/app_api.go
> +			body = strings.ReplaceAll(body, fmt.Sprintf(taskIDPatternWithTaskLink, prTaskRelation.InternalTaskID, webURL), "")
Can we extract `fmt.Sprintf(taskIDPatternWithTaskLink, prTaskRelation.InternalTaskID, webURL)` and `taskIDPatternWithTaskLink` into a helper function instead? Then we only need to pass in the typed parameters afterwards.

2023-07-26 03:02 UTC, naturetime10 commented on apps/github/app_api.go
> +			webURL := a.composeWebURL(a.teamyWebUIBaseURL, teamID, prTaskRelation.InternalTaskID)
It seems that `composeWebURL` is not using instance variable. Let's use `a.teamyWebUIBaseURL` inside this helper method instead of passing it in.
Also, can we have a clear name for this function such as `formatTeamyWebTaskURL`?

2023-07-26 03:02 UTC, naturetime10 commented on apps/github/app_api.go
> +var taskIDPatternWithTaskLink = "[(task:%d)](%s)"
```suggestion
var taskIDWithTaskLinkFormat = "[(task:%d)](%s)"
```

2023-07-26 03:02 UTC, naturetime10 commented on apps/github/app_api.go
> +			webPreviousTaskURL := a.composeWebURL(a.teamyWebUIBaseURL, teamID, prTaskRelation.InternalTaskID)
```suggestion
			webPrevTaskURL := a.composeWebURL(a.teamyWebUIBaseURL, teamID, prTaskRelation.InternalTaskID)
```

2023-07-26 03:02 UTC, naturetime10 commented on apps/github/app_api.go
> +				fmt.Sprintf(taskIDPatternWithTaskLink, *taskID, webNewTaskURL),
Use helper method instead.

2023-07-26 03:02 UTC, naturetime10 commented on apps/github/app_api.go
> +				fmt.Sprintf(taskIDPatternWithTaskLink, *taskID, webNewTaskURL),
If there is no mentioned task in the PR, can we just append the `mentionTask` string at the top of the body?

2023-07-26 03:02 UTC, naturetime10 commented on apps/github/app_api.go
> +		body := fmt.Sprintf("%v\n"+taskIDPatternWithTaskLink, prEvt.PullRequest.Body, *taskID, webURL)
Can we use proper formatting instead of mix of string formatting and string concatenation?

2023-07-26 03:02 UTC, naturetime10 commented on k8s/production.yaml
> +              value: "https://teamyapp.com/"
```suggestion
              value: "https://teamyapp.com"
```

2023-07-26 03:02 UTC, naturetime10 commented on k8s/testing.yaml
> +              value: "http://localhost:3000"
```suggestion
              value: "https://testing.teamyapp.com"
```
Teamy backend API in testing environment should redirect user to testing UI.

2023-07-27 06:50 UTC, yijia-cc commented on apps/github/app_api.go
> +			webPreviousTaskURL := a.composeWebURL(a.teamyWebUIBaseURL, teamID, prTaskRelation.InternalTaskID)
Changed to `prevTaskIDWithTaskURL` to keep consistent with string content

2023-07-27 07:11 UTC, yijia-cc commented on apps/github/app_api.go
> +				fmt.Sprintf(taskIDPatternWithTaskLink, *taskID, webNewTaskURL),
This is not related to my change. Will refactor github app logic in next PR.

2023-07-27 07:43 UTC, naturetime10 approved these changes

2023-07-27 07:43 UTC, merged