Implement AppPackageUploadSession APIs
teamyapp/teamy-backend pull request #465
Opened 2023-08-22 02:44 UTC by duanxianbo

[(task:17301)](https://staging.teamyapp.com/teams/107/tasks/17301)

2023-08-22 07:00 UTC, naturetime10 requested changes

2023-08-22 07:00 UTC, naturetime10 commented on .DS_Store
Can we removed this file?

2023-08-22 07:00 UTC, naturetime10 commented on core/api/gql/app_version.go
> +}) (graphql.ID, error) {
```suggestion
func (m Mutation) CreateAppPackageUploadSession(
    ct context.Context, 
    args struct {
	    AppID         graphql.ID
	    VersionNumber int
	},
) (graphql.ID, error) {
```

2023-08-22 07:00 UTC, naturetime10 commented on core/api/gql/app_version.go
> +}) (graphql.ID, error) {
Are you able to pass in `int` instead of `int32` for `VersionNumber` for GraphQL API?

2023-08-22 07:00 UTC, naturetime10 commented on core/api/gql/app_version.go
> +	VersionNumber       int
Are you able to pass in `int` instead of `int32` for `VersionNumber` for GraphQL API?

2023-08-22 07:00 UTC, naturetime10 commented on core/api/gql/app_version.go
> +}) (AppVersion, error) {
```suggestion
func (m Mutation) FinishAppPackageUploadSession(
    ct context.Context, 
    args struct {
	    AppID               graphql.ID
	    VersionNumber       int
	    FileUploadSessionID graphql.ID
	    },
) (AppVersion, error) {
```

2023-08-22 07:00 UTC, naturetime10 commented on core/api/gql/app_version.go
> +
```suggestion
```

2023-08-22 07:00 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	finishAppPackageUploadSession(appId: ID! versionNumber: Int!, fileUploadSessionId: ID!): AppVersion!
Those 2 APIs are already defined in the above lines.

2023-08-22 07:00 UTC, naturetime10 commented on core/dao/app.go
> +	FindAppByID(ct context.Context, appID uint64) (entity.App, *errs.Error)
```suggestion
	FindAppByID(ct context.Context, appID uint64) (entity.App, *errs.Error)
	FindAppByIDWithTx(ct context.Context, tx *transaction.Transaction, appID uint64) (entity.App, *errs.Error)
```

2023-08-22 07:00 UTC, naturetime10 commented on core/dao/app_version.go
> +	FindMaxVersionNumberWithTx(ct context.Context, tx *transaction.Transaction, appID uint64) (int, *errs.Error)
Is this API still needed?

2023-08-22 07:00 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +			updated_at
```suggestion
			total_installations,
			created_at,
			updated_at,
			managed_by_team_id
```

2023-08-22 07:00 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +			&app.UpdatedAt,
```suggestion
			&app.TotalInstallations,
			&app.CreatedAt,
			&app.UpdatedAt,
			&app.ManagedByTeamID,
```

2023-08-22 07:00 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +			updated_at
```suggestion
			total_installations,
			created_at,
			updated_at,
			managed_by_team_id
```

2023-08-22 07:00 UTC, naturetime10 commented on core/dao/sqldb/app.go
> +		app.UpdatedAt,
```suggestion
		app.ID,
		app.TotalInstallations,
		app.CreatedAt,
		app.UpdatedAt,
		app.ManagedByTeamID,
```

2023-08-22 07:00 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +}
Is this API still needed?

2023-08-22 07:00 UTC, naturetime10 commented on core/dep/wire.go
> +	wire.Bind(new(storage.MapClient), new(*storage.HTTPClient)),
Let's move Bind statements to the first parameters of `wire.NewSet`

2023-08-22 07:00 UTC, naturetime10 commented on core/dep/wire.go
> +	newHTTPClient,
Let's move this before `service.NewThread`

2023-08-22 07:00 UTC, naturetime10 commented on core/dep/wire.go
> +	cloudWebAPIExternalBaseURL CloudWebAPIExternalBaseURL,
```suggestion
	mapServerURL MapServerURL,
```

2023-08-22 07:00 UTC, naturetime10 commented on core/dep/wire.go
> +	return storage.NewHTTPClient(string(cloudWebAPIExternalBaseURL))
```suggestion
	return storage.NewHTTPClient(string(mapServerURL))
```

2023-08-22 07:00 UTC, naturetime10 commented on core/entity/app.go
> +	UpdatedAt          *time.Time
```suggestion
	CreatedAt          time.Time
	UpdatedAt          *time.Time
	ManagedByTeamID    uint64
```

2023-08-22 07:00 UTC, naturetime10 commented on go.sum
> +github.com/teamyapp/cloud v0.0.0-20230822020004-59d350ec3218 h1:GyRYs1YU7wrhsEFZrRx2y02jwuExI/A5CHapHj+eWeM=
Where are we using 2 different version of cloud? Can we do `go mod tidy`?

2023-08-22 07:00 UTC, naturetime10 commented on migrations/20230821201549_change_app_tables.sql
> +ALTER TABLE app
Can we do the exact opposite order for migrate down so that we can make sure order of dependent changes is already correct?

2023-08-22 07:00 UTC, naturetime10 commented on migrations/20230821201549_change_app_tables.sql
> +
```suggestion
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	appPackageRoot = "apps/packages"
```suggestion
	appPackageRoot = path.Join("app","packages")
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	readAhead      = 28
```suggestion
	readAheadBytes      = 28
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	maxRead        = 4096
```suggestion
	maxReadBytes        = 4096
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +}
```suggestion
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +}
```suggestion
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	// TODO(yuhang): delete registered app resource and groups
```suggestion
	// TODO: delete registered app resource and groups
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	zipReader, err := a.storageMapClient.Get(strconv.Itoa(int(uploadSession.FileId)))
```suggestion
	fileReader, err := a.storageMapClient.Get(strconv.Itoa(int(uploadSession.FileId)))
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	gzf, error := gzip.NewReader(bufio.NewReaderSize(zipReader, bufferSize))
```suggestion
	gzipReader, error := gzip.NewReader(bufio.NewReaderSize(zipReader, bufferSize))
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	gzf, error := gzip.NewReader(bufio.NewReaderSize(zipReader, bufferSize))
May I ask why do we need this buffer from performance perspective?

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	appIDStr := strconv.Itoa(int(appID))
Let's use `strconv.FormatInt` so that we can use `int64` to avoid cutting the higher bit when converting `uint64` to `int`

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	versionNumberStr := strconv.Itoa(int(versionNumber))
```suggestion
	versionNumberStr := strconv.Itoa(versionNumber)
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +			err := a.storageMapClient.Put(fullPath, tarReader)
Let's put a comment and mention we will use separate storage map client for reading `gzip` file and for uploading extracted `files`.

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +		err = a.appPackageUploadSessionDao.UpdateAppPackageFileUploadSession(ct, tx, appPackageUploadSession)
```suggestion
		return a.appPackageUploadSessionDao.UpdateAppPackageFileUploadSession(ct, tx, appPackageUploadSession)
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +		return err
```suggestion
```

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +	}()
I think this is the last step of this function. Can we put it right before `return` of this API?

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +func (a App) uploadAppPackageFiles(
Let's move `private` helpers after public `APIs`?

2023-08-22 07:00 UTC, naturetime10 commented on core/service/app.go
> +		return nil
```suggestion
		return a.appVersionDao.DeleteAppVersion(ct, tx, appID, versionNumber)
```

2023-08-22 15:30 UTC, duanxianbo commented on core/dao/app_version.go
> +	FindMaxVersionNumberWithTx(ct context.Context, tx *transaction.Transaction, appID uint64) (int, *errs.Error)
i think yes, because when we want to create version, we need the highest version number?

2023-08-22 15:44 UTC, duanxianbo commented on migrations/20230821201549_change_app_tables.sql
> +ALTER TABLE app
I do not quite understand, I think I have already maintained the opposite order

2023-08-22 23:45 UTC, duanxianbo commented on core/service/app.go
> +	}()
you mean outside the goroutine ?

2023-08-23 00:24 UTC, duanxianbo commented on core/api/gql/app_version.go
> +	VersionNumber       int
no, it does not work, reverted

2023-08-23 02:41 UTC, naturetime10 approved these changes

2023-08-23 02:41 UTC, naturetime10 commented on core/service/app.go
> +			//TODO use separate storage map client for reading gzip file and for uploading extracted files
```suggestion
			// TODO: use separate storage map client for reading gzip file and for uploading extracted files
```

2023-08-23 02:41 UTC, naturetime10 commented on core/service/app.go
> +		// TODO, change app version status to ready
```suggestion
		// TODO: change app version status to ready
```

2023-08-23 02:41 UTC, naturetime10 commented on migrations/20230821201549_change_app_tables.sql
> +ALTER TABLE app
Discussed offline. We complete reverse the order of all SQL statements.

2023-08-23 02:41 UTC, naturetime10 commented on main.go
> +		dep.MapServerURL(cfg.CloudWebAPIExternalBaseURL),
Join for the full path.

2023-08-24 00:42 UTC, naturetime10 requested changes

2023-08-24 00:42 UTC, naturetime10 commented on core/service/app.go
> +func (a App) FinishAppPackageFileUploadSession(ct context.Context, appID uint64, versionNumber int32, fileUploadSessionID uint64) (entity.AppVersion, *errs.Error) {
```suggestion
func (a App) FinishAppPackageFileUploadSession(ct context.Context, appID uint64, versionNumber int, fileUploadSessionID uint64) (entity.AppVersion, *errs.Error) {
```

2023-08-24 00:42 UTC, naturetime10 commented on core/service/app.go
> +func (a App) CreateAppPackageFileUploadSession(ct context.Context, appID uint64, versionNumber int32) (uint64, *errs.Error) {
```suggestion
func (a App) CreateAppPackageFileUploadSession(ct context.Context, appID uint64, versionNumber int) (uint64, *errs.Error) {
```

2023-08-24 00:42 UTC, naturetime10 commented on core/service/app.go
> +		VersionNumber:       int(versionNumber),
```suggestion
		VersionNumber:      versionNumber,
```

2023-08-24 00:42 UTC, naturetime10 commented on core/service/app.go
> +	versionNumberInt := int(versionNumber)
```suggestion
```

2023-08-24 00:42 UTC, naturetime10 commented on core/service/app.go
> +	}()
Let's move it right before line 384.

2023-08-24 01:57 UTC, naturetime10 requested changes

2023-08-24 01:57 UTC, naturetime10 commented on migrations/20230821201549_change_app_tables.sql
> +
```suggestion
```

2023-08-24 02:08 UTC, naturetime10 approved these changes

2023-08-24 02:10 UTC, merged