Add rollout apis
teamyapp/teamy-backend pull request #471
Opened 2023-09-04 14:14 UTC by duanxianbo

[(task:18101)](https://staging.teamyapp.com/teams/107/tasks/18101)

2023-09-04 18:30 UTC, naturetime10 requested changes

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/activator.go
> +	deps               *Dependencies
Did we use it?

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/activator.go
> +	deps                *Dependencies
Did we use it?

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/activator.go
> +	deps *Dependencies,
Did we use it?

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/activator.go
> +	deps                *Dependencies
Did we use it?

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/activator.go
> +	return TimeRangeActivator{deps: deps, timeRangeActivator: timeRangeActivator}
```suggestion
	return TimeRangeActivator{
	    deps: deps, 
	    timeRangeActivator: timeRangeActivator,
	}
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/activator.go
> +	return PercentageActivator{deps: deps, percentageActivator: percentageActivator}
```suggestion
	return PercentageActivator{
	    deps: deps, 
	    percentageActivator: percentageActivator,
	}
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	secrets, err := a.deps.appService.FindAppSecretsByAppID(ctx, a.app.ID)
```suggestion
	secrets, err := a.deps.appService.FindSecretsByAppID(ctx, a.app.ID)
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	}
```suggestion
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	userGroups := make([]UserGroup, 0)
```suggestion
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	for _, group := range filterGroups {
```suggestion
	userGroups := make([]UserGroup, 0)
	for _, group := range groups {
		userGroups = append(userGroups, newStaticUserGroup(a.deps, group))
	}
	
	for _, group := range filterGroups {
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	}
```suggestion
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	}
```suggestion
    teamGroups := make([]TeamGroup, 0)
	for _, group := range groups {
		teamGroups = append(teamGroups, newStaticUserGroup(a.deps, group))
	}
	
	for _, group := range filterGroups {
		teamGroups = append(teamGroups, newFilterUserGroup(a.deps, group))
	}
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	}) (TeamAppInstallation, error) {
```suggestion
	},
) (TeamAppInstallation, error) {
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_installation.go
> +	teamEntity, err := t.deps.teamService.FindTeamByID(ctx, t.teamAppInstallation.InstalledTeamID)
```suggestion
	team, err := t.deps.teamService.FindTeamByID(ctx, t.teamAppInstallation.InstalledTeamID)
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_installation.go
> +	appVersion := newAppVersion(t.deps, appVersionEntity)
```suggestion
	gqlAppVersion := newAppVersion(t.deps, appVersionEntity)
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_installation.go
> +	appVersionEntity, err := t.deps.appService.FindAppVersionByAppIDAndNumber(ctx, t.teamAppInstallation.AppID, appVersionNumber)
```suggestion
	appVersion, err := t.deps.appService.FindAppVersionByAppIDAndNumber(ctx, t.teamAppInstallation.AppID, appVersionNumber)
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_installation.go
> +func newTeamAppInstallation(deps *Dependencies, teamAppInstallation entity.TeamAppInstallation) TeamAppInstallation {
```suggestion
func newTeamAppInstallation(
    deps *Dependencies, 
    teamAppInstallation entity.TeamAppInstallation,
) TeamAppInstallation {
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_secret.go
> +	}) (AppSecret, error) {
```suggestion
	},
) (AppSecret, error) {
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_secret.go
> +	}) (AppSecret, error) {
```suggestion
	},
) (AppSecret, error) {
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_version.go
> +	prices, err := a.deps.appService.FindAppVersionPricesByAppVersionID(ctx, a.appVersion.AppID, a.appVersion.Number)
```suggestion
	prices, err := a.deps.appService.FindPricesByAppVersionID(ctx, a.appVersion.AppID, a.appVersion.Number)
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_version.go
> +	}) (AppVersion, error) {
```suggestion
	},
) (AppVersion, error) {
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_version.go
> +		m.deps.logger.Error(internalErr)
```suggestion
		m.deps.logger.ErrorWithContext(ct, internalErr)
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app_version.go
> +		m.deps.logger.Error(err)
```suggestion
		m.deps.logger. ErrorWithContext(ct, err)
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/rollout.go
>  }
```suggestion
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/rollout.go
>  }
```suggestion
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/rollout.go
>  }
```suggestion
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	userGroups := make([]UserGroup, 0)
A type switch is a construct that permits several type assertions in series.

A type switch is like a regular switch statement, but the cases in a type switch specify types (not values), and those values are compared against the type of the value held by the given interface value.

```
switch v := i.(type) {
case T:
    // here v has type T
case S:
    // here v has type S
default:
    // no match; here v has the same type as i
}
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	groups, err := a.deps.groupService.FindStaticUserGroupsByAppID(ctx, a.app.ID)
Maybe try this: 
```
type Groups struct {
	StaticGroups []StaticGroup
	FilterGroups []FilterGroup
}
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/app.go
> +	groups, err := a.deps.groupService.FindStaticTeamGroupsByAppID(ctx, a.app.ID)
```
type Groups struct {
	StaticGroups []StaticGroup
	FilterGroups []FilterGroup
}
```

2023-09-04 18:30 UTC, naturetime10 commented on core/api/gql/rollout.go
> +}
```suggestion
}

func (r Rollout) VersionSelector(ctx context.Context) (VersionSelector, error)
```

2023-09-04 21:52 UTC, naturetime10 requested changes

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	createPercentageActivator(input: CreatePercentageActivatorInput!): PercentageActivator!
Although there seems to be just relations between `VersionSelector` and `appVersion`, I think we should have API to create `StaticVersionSelector` and `ExperimentVersionSelector`. We may have other selectors in the future.

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	createRollout(appID: ID!, appRolloutRelationType: AppRolloutRelationType!, input: CreateRolloutInput!): Rollout!
```suggestion
	createAppRollout(appID: ID!, appRolloutType: AppRolloutType!, input: CreateRolloutInput!): Rollout!
```

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	createPercentageActivator(input: CreatePercentageActivatorInput!): PercentageActivator!
Can user update or delete activator or selector?

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	selectorID: ID!
```suggestion
	versionSelector: VersionSelector!
```

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	selectorType: SelectorType
```suggestion
```

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	selectorType:  SelectorType!
```suggestion
	versionSelectorType:  VersionSelectorType!
        versionSelectorId: ID!
```

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	activatorType: ActivatorType!
```suggestion
	activatorType: ActivatorType!
	activatorID:  ID!
```

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	selectorType:  SelectorType!
```suggestion
	activatorType: ActivatorType!
	activatorID:  ID!
	versionSelectorType:  VersionSelectorType!
	versionSelectorID:  ID!
```

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +enum AppRolloutRelationType {
```suggestion
enum AppRolloutType {
```

2023-09-04 21:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +enum SelectorType {
```suggestion
enum VersionSelectorType {
```

2023-09-04 23:16 UTC, naturetime10 requested changes

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +
```suggestion
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +		teamIDs[i] = teamID
```suggestion
		}
		
		teamIDs[i] = teamID
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +	teamIDs := make([]uint64, len(args.Input.TeamIDs))
We can allocate a slice and append to that slice. Are you using array without `dynamic resizing` to improve performance?

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +	for i, id := range args.Input.TeamIDs {
```suggestion
	for index, id := range args.Input.TeamIDs {
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +		teamIDs[i] = teamID
```suggestion
		}
		
		teamIDs[i] = teamID
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +	}) (StaticTeamGroup, error) {
```suggestion
	},
) (StaticTeamGroup, error) {
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +	groupID, internalErr := fromGraphQLID(args.GroupID)
```suggestion
	}
	
	groupID, internalErr := fromGraphQLID(args.GroupID)
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +	for i, id := range args.Input.TeamIDs {
```suggestion
	for index, id := range args.Input.TeamIDs {
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +		teamIDs[i] = teamID
```suggestion
		}
		
		teamIDs[i] = teamID
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +	}) (FilterTeamGroup, error) {
```suggestion
	},
) (FilterTeamGroup, error) {
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
> +
```suggestion
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/user_groups.go
> +
```suggestion
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/user_groups.go
>  func (f FilterUserGroup) App(ctx context.Context) App {
```suggestion
func (f FilterUserGroup) App(ctx context.Context) (App, error) {
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/app_installation.go
> +func (t TeamAppInstallation) ActiveAppVersion(ctx context.Context) (*AppVersion, *errs.Error) {
```suggestion
func (t TeamAppInstallation) ActiveAppVersion(ctx context.Context) (*AppVersion, error) {
```

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/rollout.go
> +	return nil, nil
I think we should throw some unsupported database error here.

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/schema.graphql
>  interface TeamGroup implements Group{
`UserGroup` and `TeamGroup` are having exactly the same structure. Let's merge `UserGroup` and `TeamGroup` into `Group`.

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
>  }
Let merge `TeamGroup` and `UserGroup` into `Group` because they have exactly the same structure.

2023-09-04 23:16 UTC, naturetime10 commented on core/api/gql/team_groups.go
>  func (f FilterTeamGroup) TeamCount(ctx context.Context) int32 {
```suggestion
func (f FilterTeamGroup) MemberCount(ctx context.Context) int32 {
```

2023-09-05 06:53 UTC, naturetime10 requested changes

2023-09-05 06:53 UTC, naturetime10 commented on core/api/gql/user_groups.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/api/gql/user_groups.go
>  type UserGroup interface {
Merge with `TeamGroup` into `Group`

2023-09-05 06:53 UTC, naturetime10 commented on core/dao/app_group_relation.go
> +	FindGroupIDsByAppIDAndType(ct context.Context, appID uint64, appGroupRelationType entity.AppGroupRelationType) ([]uint64, *errs.Error)
```suggestion
	FindGroupIDsByAppIDAndRelationType(ct context.Context, appID uint64, appGroupRelationType entity.AppGroupRelationType) ([]uint64, *errs.Error)
```

2023-09-05 06:53 UTC, naturetime10 commented on core/dao/app_rollout_relation.go
> +	FindRolloutIDsByAppIDAndType(ct context.Context, appID uint64, rolloutType entity.AppRolloutRelationType) ([]uint64, *errs.Error)
```suggestion
	FindRolloutIDsByAppIDAndRelationType(ct context.Context, appID uint64, rolloutType entity.AppRolloutRelationType) ([]uint64, *errs.Error)
```

2023-09-05 06:53 UTC, naturetime10 commented on core/dao/filter_group.go
> +	FindFilterGroupsByIDs(ct context.Context, groupID []uint64) ([]entity.FilterGroup, *errs.Error)
Should we also add `FindFilterGroupByID` API?

2023-09-05 06:53 UTC, naturetime10 commented on core/dao/group.go
> +	FindGroupsByIDs(ct context.Context, GroupIDs []uint64) ([]entity.Group, *errs.Error)
Should we also add `FindGroupByID`?

2023-09-05 06:53 UTC, naturetime10 commented on core/dao/group.go
> +	FindGroupsByIDs(ct context.Context, GroupIDs []uint64) ([]entity.Group, *errs.Error)
```suggestion
	FindGroupsByIDs(ct context.Context, groupIDs []uint64) ([]entity.Group, *errs.Error)
```

2023-09-05 06:53 UTC, naturetime10 commented on core/dao/group.go
> +	UpdateGroup(ct context.Context, GroupID uint64, Group entity.Group) *errs.Error
```suggestion
	CreateGroup(ct context.Context, group entity.Group) (entity.Group, *errs.Error)
	UpdateGroup(ct context.Context, Group entity.Group) *errs.Error
```

ID should be part of `Group` entity.

2023-09-05 06:53 UTC, naturetime10 commented on core/dao/group_rollout_relation.go
> +	FindRolloutIDsByGroupIDAndSortByOrderedIndex(ct context.Context, groupID uint64) ([]uint64, *errs.Error)
```suggestion
	FindRolloutIDsByGroupID(ct context.Context, groupID uint64) ([]uint64, *errs.Error)
```
Sorting is considered as part of business logic and should be done in service layer.

2023-09-05 06:53 UTC, naturetime10 commented on core/dao/sqldb/app_version.go
> +// FindAppVersionByAppIDAndVersionNumber implements dao.AppVersion.
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/dao/team_app_installation.go
> +	FindTeamAppInstallationByIDWithTx(ct context.Context, tx *transaction.Transaction, appInstallationID uint64) (entity.TeamAppInstallation, *errs.Error)
```suggestion
        FindTeamAppInstallationByIDWithTx(ct context.Context, tx *transaction.Transaction, appInstallationID uint64) (entity.TeamAppInstallation, *errs.Error)
	CreateTeamAppInstallation(ct context.Context, teamAppInstallation entity.TeamAppInstallation) (entity.TeamAppInstallation, *errs.Error)
```

2023-09-05 06:53 UTC, naturetime10 commented on core/entity/activator.go
> +
type Activator struct {
        ID        uint64
	CreatedAt time.Time
	UpdatedAt *time.Time
}

2023-09-05 06:53 UTC, naturetime10 commented on core/entity/activator.go
> +	UpdatedAt *time.Time
```suggestion
	Activator
	StartAt   time.Time
	EndAt     time.Time
```

2023-09-05 06:53 UTC, naturetime10 commented on core/entity/activator.go
> +	UpdatedAt  *time.Time
```suggestion
	Activator
	MaxViewers int
```

2023-09-05 06:53 UTC, naturetime10 commented on core/entity/activator.go
> +	UpdatedAt  *time.Time
```suggestion
	Activator
	Percentage int
```

2023-09-05 06:53 UTC, naturetime10 commented on core/entity/rollout.go
> +type SelectorType string
```suggestion
type VersionSelectorType string
```

2023-09-05 06:53 UTC, naturetime10 commented on core/entity/rollout.go
> +	SelectorTypeExperiment SelectorType = "EXPERIMENT"
```suggestion
	VersionSelectorTypeStatic           VersionSelectorType = "STATIC"
	VersionSelectorTypeExperiment VersionSelectorType = "EXPERIMENT"
```

2023-09-05 06:53 UTC, naturetime10 commented on core/entity/rollout.go
> +	SelectorType  SelectorType
```suggestion
         ActivatorType             ActivatorType
	ActivatorID                  uint64
	VersionSelectorType  SelectorType
	VersionSelectorID       uint64
```

2023-09-05 06:53 UTC, naturetime10 commented on core/entity/rollout_store.go
> +}
What is this for?

2023-09-05 06:53 UTC, naturetime10 commented on core/service/app.go
> +	appVersionChangeDaO        dao.AppVersionChange
```suggestion
	appVersionChangeDao        dao.AppVersionChange
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/app.go
> +	return appSecret, nil
```suggestion
	return appSecret, err
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/app.go
> +	return appSecret, nil
```suggestion
	return appSecret, err
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/app.go
> +	return teamAppInstallation, nil
```suggestion
	return teamAppInstallation, err
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +		return entity.Group{}, internalErr
```suggestion
		return entity.Group{}, errs.FromGRPCErr(rpcErr)
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +func (g *Group) UpdateStaticUserGroup(ct context.Context, appID uint64, groupID uint64, name string, userIDs []uint64) (entity.Group, *errs.Error) {
```suggestion
func (g *Group) UpdateStaticUserGroup(ct context.Context, groupID uint64, name string, userIDs []uint64) (entity.Group, *errs.Error) {
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +	}
Let's use delta library to detect diff.

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +		return entity.FilterGroup{}, internalErr
```suggestion
		return entity.FilterGroup{}, errs.FromGRPCErr(rpcErr)
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +func (g *Group) UpdateFilterUserGroup(ct context.Context, appID uint64, groupID uint64, name string, filter string) (entity.FilterGroup, *errs.Error) {
```suggestion
func (g *Group) UpdateFilterUserGroup(ct context.Context, groupID uint64, input UpdateFilterGroupInput) (entity.FilterGroup, *errs.Error) {
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +func (g *Group) CreateFilterUserGroup(ct context.Context, appID uint64, name string, filter string) (entity.FilterGroup, *errs.Error) {
```suggestion
func (g *Group) CreateFilterUserGroup(ct context.Context, appID uint64, input CreateFilterGroupInput) (entity.FilterGroup, *errs.Error) {
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +	}
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +		return entity.Group{}, internalErr
```suggestion
		internalErr := errs.FromGRPCErr(rpcErr)
		return entity.Group{}, internalErr
```
```suggestion
		return entity.Group{}, errs.FromGRPCErr(rpcErr)
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +func (g *Group) CreateStaticTeamGroup(ct context.Context, appID uint64, name string, teamIDs []uint64) (entity.Group, *errs.Error) {
```suggestion
func (g *Group) CreateStaticTeamGroup(ct context.Context, appID uint64, input CreateStaticGroupInput) (entity.Group, *errs.Error) {
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +func (g *Group) UpdateStaticTeamGroup(ct context.Context, appID, groupID uint64, name string, teamIDs []uint64) (entity.Group, *errs.Error) {
```suggestion
func (g *Group) UpdateStaticTeamGroup(
    ct context.Context, 
    groupID uint64, 
    input UpdateStaticTeamGroupInput) (entity.Group, *errs.Error) {
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +	}
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +	ct context.Context, appID, groupID uint64, name string, filter string,
```suggestion
	ct context.Context, 
	groupID uint64, 
	input UpdateFilterTeamGroupInput,
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +	}
Let's use delta library to detect changes.

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +	return filterGroup, nil
```suggestion
	return filterGroup, err
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +		return nil
```suggestion
		return err
```

2023-09-05 06:53 UTC, naturetime10 commented on core/service/group.go
> +	return users, nil
```suggestion
	return users, err
```

2023-09-05 07:08 UTC, naturetime10 requested changes

2023-09-05 07:08 UTC, naturetime10 commented on core/dao/rollout_store.go
> +}
What is this for? We should call it something other than `RolloutStore`

2023-09-05 07:08 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/group.go
> +
```suggestion
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/group.go
> +		return nil
```suggestion
		return err
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/group.go
> +	return teams, nil
```suggestion
	return teams, err
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +	isEnabled bool,
```suggestion
	input CreateRolloutInput,
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +
```suggestion
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +		ActivatorType: activatorType,
```suggestion
		ActivatorType: activatorType,
		ActivatorID:   activatorID,
                 VersionSelectorType:  versionSelectorType,
		VersionSelectorID:  versionSelectorID,
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +
```suggestion
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +		var err *errs.Error
Should we also clean up `Activator` and `VersionSelector`?

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +	return rollout, nil
```suggestion
	return rollout, err
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +
```suggestion
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +		sortedRolloutIDs = append(sortedRolloutIDs, rolloutIDs...)
Sort by relation index. GetActiveVersionNumber for that group. Compare & swap with `maxActiveVersionNumber`

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +		rolloutIDs, err := r.groupRolloutRelationDao.FindRolloutIDsByGroupIDAndSortByOrderedIndex(ct, teamGroupID)
```suggestion
		groupRolloutRelations, err := r.groupRolloutRelationDao.FindRolloutIDsByGroupID(ct, teamGroupID)
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +	rolloutEntities, err := r.rolloutDao.FindRolloutsByIDs(ct, sortedRolloutIDs)
```suggestion
	rawRollouts, err := r.rolloutDao.FindRolloutsByIDs(ct, sortedRolloutIDs)
```

2023-09-05 07:08 UTC, naturetime10 commented on core/service/rollout.go
> +	for _, rolloutEntity := range rolloutEntities {
```suggestion
	for _, rawRollout := range rawRollouts {
```

2023-09-05 07:24 UTC, naturetime10 requested changes

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout.go
> +func (r *Rollout) GetActiveAppVersionNumberForTeam(ct context.Context, appTeamInstallation entity.TeamAppInstallation) (int, *errs.Error) {
```suggestion
func (r *Rollout) GetActiveAppVersionNumberForTeam(ct context.Context, appTeamInstallation entity.TeamAppInstallation) (*int, *errs.Error) {
```

ActiveVersion is `nil` when there is no rollout.

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout.go
> +func (r *Rollout) newRollout(ct context.Context, rolloutEntity entity.Rollout) (rollout.Rollout, *errs.Error) {
```suggestion
func (r *Rollout) newRollout(ct context.Context, rawRollout entity.Rollout) (rollout.Rollout, *errs.Error) {
```

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout.go
> +	selectorType := rolloutEntity.SelectorType
```suggestion
	versionSelectorType := rawRollout.VersionSelectorType
```

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout.go
> +		}
```suggestion
		rawActivator, err := r.FindTimeRangeActivatorByID(ct, activatorID)
		if err != nil {
			return nil, err
		}
		
		activator = rollout.NewTimeRangeActivator(clock.New(), &activatorEntity.StartAt, &activatorEntity.EndAt)
```

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout.go
> +		activatorEntity, err := r.FindMaxViewersActivatorByID(ct, activatorID)
```suggestion
		rawActivator, err := r.FindMaxViewersActivatorByID(ct, activatorID)
```

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout.go
> +	}
Throw error for unsupported `versionSelectorType`

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout.go
> +	}
I think it makes more sense if we put this logic inside `getRolloutVersionSelector`?

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout.go
> +	}
Throw error for unsupported `activatorType`

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +	rolloutViewer, err := m.rolloutViewerDao.FindRolloutViewerByViewerIDAndRolloutID(ct, viewerID, m.rolloutID)
Return `nil, nil` if `err.Code` is `NotFound`.

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +	rolloutViewer.IsActivated = isActivated
```suggestion
	}
	
	rolloutViewer.IsActivated = isActivated
```

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +package service
Let's move this to `store` package

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +	store.TotalViewers = totalViewers
```suggestion
	}
	
	store.TotalViewers = totalViewers
```

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +	return &viewer.VersionNumber, err
Return `nil, nil` if `err.Code` is `NotFound`.

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +	viewer.VersionNumber = versionNumber
```suggestion
	}
	
	viewer.VersionNumber = versionNumber
```

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +	return &viewer.IsActivated, nil
```suggestion
	}
	
	return &viewer.IsActivated, nil
```
Return `nil, nil` if `err.Code` is `NotFound`.

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +	viewer.IsActivated = isActivated
```suggestion
	}
	
	viewer.IsActivated = isActivated
```

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +	rolloutEntity, err := r.rolloutDao.FindRolloutByID(ct, r.rolloutID)
```suggestion
	rawRollout, err := r.rolloutDao.FindRolloutByID(ct, r.rolloutID)
```

2023-09-05 07:24 UTC, naturetime10 commented on core/service/rollout_store.go
> +	rolloutEntity.IsEnabled = isRolloutEnabled
```suggestion
	rolloutEntity, err := r.rolloutDao.FindRolloutByID(ct, r.rolloutID)
	if err != nil {
		return err
	}
	
	rolloutEntity.IsEnabled = isRolloutEnabled
```

2023-09-05 07:24 UTC, naturetime10 commented on go.mod
> +	github.com/benbjohnson/clock v1.3.5
Where did we use this?

2023-09-07 02:06 UTC, naturetime10 requested changes

2023-09-07 02:06 UTC, naturetime10 commented on core/service/rollout.go
> +	teamGroupsIDs, err := r.appGroupRelationDao.FindGroupIDsByAppIDAndType(ct, appID, entity.AppGroupRelationTypeTeam)
Let's handle error.

```
teamGroupIDs = r.filterTeamGroupIDs(teamGroupIDs, teamID)
```

2023-09-07 02:06 UTC, naturetime10 commented on core/service/rollout.go
> +	sortedRolloutIDs := make([]uint64, 0)
maxActiveVersionNumber int  := math.MinInt

2023-09-07 02:06 UTC, naturetime10 commented on core/service/rollout.go
> +	rolloutEntities, err := r.rolloutDao.FindRolloutsByIDs(ct, sortedRolloutIDs)
Move the below logic into a helper method and invoke it inside the above for loop.

2023-09-08 00:00 UTC, duanxianbo commented on core/entity/rollout_store.go
> +}
it is for the maxviewer rollout, maybe it should go to maxviewer rollout activator?

2023-09-08 00:01 UTC, duanxianbo commented on core/entity/rollout_store.go
> +}
we said totalViewer is maybe userful for every rollout

2023-09-09 00:04 UTC, duanxianbo commented on core/service/rollout.go
> +		var err *errs.Error
but activators and selectors can be shared among rollouts?

2023-09-10 17:01 UTC, naturetime10 requested changes

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/activator.go
> +
```suggestion
```

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/activator.go
> +
```suggestion
```

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/activator.go
> +
```suggestion
```

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/app.go
> +	groups, err := a.deps.groupService.FindStaticUserGroupsByAppID(ctx, a.app.ID)
Above suggestion is obsolete.

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/app.go
> +	groups, err := a.deps.groupService.FindStaticUserGroupsByAppID(ctx, a.app.ID)
I thought we are merging `FindStaticUserGroupsByAppID` and `FindFilterUserGroupsByAppID` into `FindUserGroupsByAppID` inside `groupService`, then we will use `type switch` in GraphQL API.

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/app.go
> +	groups, err := a.deps.groupService.FindStaticTeamGroupsByAppID(ctx, a.app.ID)
Above comment is outdated.

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/app.go
> +	groups, err := a.deps.groupService.FindStaticTeamGroupsByAppID(ctx, a.app.ID)
I thought we are merging `FindStaticTeamGroupsByAppID` and `FindFilterTeamGroupsByAppID` into `FindTeamGroupsByAppID` inside `groupService`, then we will use `type switch` in GraphQL API.

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/app.go
> +	}) (TeamAppInstallation, error) {
```suggestion
	},
) (TeamAppInstallation, error) {
```

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/app_version.go
> +	}) (AppVersion, error) {
```suggestion
	},
) (AppVersion, error) {
```

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/rollout.go
> +	}
Can we do `findActivatorByID` in `rolloutService` service and do `type switch` in GraphQL just to invoke `newMaxViewersActivator(activator)`?

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/rollout.go
> +		errs.NotReady, fmt.Sprintf("activator type: %v is not ready", activatorType),
```suggestion
		errs.NotReady, fmt.Sprintf("activator type %v is not supported", activatorType),
```

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/rollout.go
> +	selectorID, internalErr := fromGraphQLID(args.Input.VersionSelectorID)
```suggestion
	versionSelectorID, internalErr := fromGraphQLID(args.Input.VersionSelectorID)
```

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/rollout.go
> +	selectorID, internalErr := fromGraphQLID(args.Input.VersionSelectorID)
```suggestion
	versionSelectorID, internalErr := fromGraphQLID(args.Input.VersionSelectorID)
```

2023-09-10 17:01 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	updateFilterGroup(groupId: ID!, input: UpdateFilterUserGroupInput!): FilterGroup!
```suggestion
	updateFilterGroup(groupId: ID!, input: UpdateFilterGroupInput!): FilterGroup!
```

2023-09-10 17:31 UTC, naturetime10 requested changes

2023-09-10 17:31 UTC, naturetime10 commented on core/api/gql/user_groups.go
> +	updateUserStaticInput := service.UpdateUserStaticGroupInput{
```suggestion
	updateStaticUserInput := service.UpdateStaticUserGroupInput{
```

Can we make the names consistent between API and inputs? Thanks!

2023-09-10 17:31 UTC, naturetime10 commented on core/api/gql/user_groups.go
> +
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/app_rollout_relation.go
> +	FindRolloutIDsByAppIDAndRelationType(ct context.Context, appID uint64, rolloutType entity.AppRolloutRelationType) ([]uint64, *errs.Error)
```suggestion
	FindRolloutIDsByAppIDAndRelationType(ct context.Context, appID uint64, rolloutType entity.AppRolloutRelationType) ([]uint64, *errs.Error)
	CreateAppRolloutRelation(ct context.Context, appRolloutRelation entity.AppRolloutRelation) (entity.AppRolloutRelation, *errs.Error)
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/activator_type_relation.go
> +// FindActivatorTypeByID implements dao.ActivatorTypeRelation.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_group_relation.go
> +// CreateAppGroupRelation implements dao.AppGroupRelation.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_group_relation.go
> +// FindAppIDByGroupID implements dao.AppGroupRelation.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_group_relation.go
> +// FindGroupIDsByAppIDAndRelationType implements dao.AppGroupRelation.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_rollout_relation.go
> +// CreateAppRolloutRelation implements dao.AppRolloutRelation.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_rollout_relation.go
> +// FindRolloutIDsByAppIDAndRelationType implements dao.AppRolloutRelation.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_rollout_relation.go
> +func (*AppRolloutRelation) FindRolloutIDsByAppIDAndRelationType(ct context.Context, appID uint64, rolloutType entity.AppRolloutRelationType) ([]uint64, *errs.Error) {
Move `FindRolloutIDsByAppIDAndRelationType` before `CreateAppRolloutRelation`?

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_secret.go
> +}
Move `Finds` before `Create`?

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_secret.go
> +// CreateAppSecret implements dao.AppSecret.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_secret.go
> +// DeleteAppSecretWithTx implements dao.AppSecret.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_secret.go
> +// FindAppSecretByIDWithTx implements dao.AppSecret.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_secret.go
> +// FindSecretsByAppID implements dao.AppSecret.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_secret.go
> +// UpdateAppSecretWithTx implements dao.AppSecret.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_version_change.go
> +// FindAppVersionChangesByAppIDAndVersionNumber implements dao.AppVersionChange.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_version_price.go
> +// FindAppVersionPricesByAppIDAndVersionNumber implements dao.AppVersionPrice.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_version_price.go
> +var _ dao.AppVersionPrice = (*AppVersionPrice)(nil)
Move this before APIs.

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/app_version_change.go
> +var _ dao.AppVersionChange = (*AppVersionChange)(nil)
Move this before APIs.

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/filter_group.go
> +// CreateFilterGroup implements dao.FilterGroup.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/filter_group.go
> +// FindFilterGroupByID implements dao.FilterGroup.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/filter_group.go
> +// FindFilterGroupsByIDs implements dao.FilterGroup.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/filter_group.go
> +// UpdateFilterGroup implements dao.FilterGroup.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/filter_group.go
> +func (*FilterGroup) FindFilterGroupByID(ct context.Context, groupID uint64) (entity.FilterGroup, *errs.Error) {
Move this before `create`

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/filter_group.go
> +var _ dao.FilterGroup = (*FilterGroup)(nil)
Move before APIs.

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/group_rollout_relation.go
> +// FindGroupRolloutRelationsByGroupID implements dao.GroupRolloutRelation.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/group_rollout_relation.go
> +// FindRolloutIDsByGroupID implements dao.GroupRolloutRelation.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/group_rollout_relation.go
> +var _ dao.GroupRolloutRelation = (*GroupRolloutRelation)(nil)
Move before APIs.

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/max_viewers_activator.go
> +// CreateMaxViewersActivator implements dao.MaxViewersActivator.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/max_viewers_activator.go
> +// FindMaxViewersActivatorByID implements dao.MaxViewersActivator.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/max_viewers_activator.go
> +var _ dao.MaxViewersActivator = (*MaxViewersActivator)(nil)
Move before APIs

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/percentage_activator.go
> +// CreatePercentageActivator implements dao.PercentageActivator.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/percentage_activator.go
> +// FindPercentageActivatorByID implements dao.PercentageActivator.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/percentage_activator.go
> +func (*PercentageActivator) FindPercentageActivatorByID(ct context.Context, ActivatorID uint64) (entity.PercentageActivator, *errs.Error) {
Move before create.

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/percentage_activator.go
> +var _ dao.PercentageActivator = (*PercentageActivator)(nil)
Move before APIs.

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +// UpdateRolloutWithTx implements dao.Rollout.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +// CreateRollout implements dao.Rollout.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +// DeleteRolloutWithTx implements dao.Rollout.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +// FindRolloutByID implements dao.Rollout.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +// FindRolloutByIDWithTx implements dao.Rollout.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +// FindRolloutsByIDs implements dao.Rollout.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +// UpdateRollout implements dao.Rollout.
```suggestion
```

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +func (*Rollout) FindRolloutByID(ct context.Context, rolloutIDs uint64) (entity.Rollout, *errs.Error) {
Let's move `find` APIs before `create`

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +func (*Rollout) UpdateRollout(ct context.Context, rollout entity.Rollout) *errs.Error {
Let's move `update` before `delete`.

2023-09-10 17:31 UTC, naturetime10 commented on core/dao/sqldb/rollout.go
> +var _ dao.Rollout = (*Rollout)(nil)
Let's move this before APIs.

2023-09-10 17:40 UTC, naturetime10 requested changes

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/rollout_store.go
> +// FindRolloutStoreByID implements dao.RolloutStore.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/rollout_store.go
> +// UpdateRolloutStore implements dao.RolloutStore.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/rollout_store.go
> +var _ dao.RolloutStore = (*RolloutStore)(nil)
Move before APIs.

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/rollout_viewer.go
> +// CreateRolloutViewer implements dao.RolloutViewer.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/rollout_viewer.go
> +// FindRolloutViewerByViewerIDAndRolloutID implements dao.RolloutViewer.
```suggestion
```
Move this before `create`.

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/rollout_viewer.go
> +// UpdateRolloutViewer implements dao.RolloutViewer.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/rollout_viewer.go
> +var _ dao.RolloutViewer = (*RolloutViewer)(nil)
Move before APIs.

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/static_group.go
> +// CreateStaticGroup implements dao.StaticGroup.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/static_group.go
> +// FindStaticGroupsByID implements dao.StaticGroup.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/static_group.go
> +// FindStaticGroupsByIDs implements dao.StaticGroup.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/static_group.go
> +// UpdateStaticGroup implements dao.StaticGroup.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/static_group.go
> +func (*StaticGroup) FindStaticGroupsByIDs(ct context.Context, groupIDs []uint64) ([]entity.StaticGroup, *errs.Error) {
Move before `create`.

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/static_group.go
> +func (*StaticGroup) FindStaticGroupsByID(ct context.Context, groupID uint64) (entity.StaticGroup, *errs.Error) {
Move before `create`.

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/static_group.go
> +var _ dao.StaticGroup = (*StaticGroup)(nil)
Move before APIs

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/team_app_installation.go
> +// CreateTeamAppInstallation implements dao.TeamAppInstallation.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/team_app_installation.go
> +// DeleteTeamAppInstallationByIDWithTx implements dao.TeamAppInstallation.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/team_app_installation.go
> +// FindTeamAppInstallationByIDWithTx implements dao.TeamAppInstallation.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/team_app_installation.go
> +// FindTeamAppInstallationsByAppID implements dao.TeamAppInstallation.
```suggestion
```

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/team_app_installation.go
> +func (*TeamAppInstallation) FindTeamAppInstallationsByAppID(ct context.Context, appID uint64) ([]entity.TeamAppInstallation, *errs.Error) {
Move before `create`.

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/team_app_installation.go
> +func (*TeamAppInstallation) FindTeamAppInstallationByIDWithTx(ct context.Context, tx *transaction.Transaction, appInstallationID uint64) (entity.TeamAppInstallation, *errs.Error) {
Move before `create`.

2023-09-10 17:40 UTC, naturetime10 commented on core/dao/sqldb/team_app_installation.go
> +var _ dao.TeamAppInstallation = (*TeamAppInstallation)(nil)
Move before APIs.

2023-09-10 17:46 UTC, naturetime10 requested changes

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/team_group_relation.go
> +// CreateTeamGroupRelation implements dao.TeamGroupRelation.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/team_group_relation.go
> +// DeleteTeamGroupRelation implements dao.TeamGroupRelation.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/team_group_relation.go
> +// FindTeamIDsByGroupID implements dao.TeamGroupRelation.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/team_group_relation.go
> +func (*TeamGroupRelation) FindTeamIDsByGroupID(ct context.Context, groupID uint64) ([]uint64, *errs.Error) {
Move before `create`

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/team_group_relation.go
> +var _ dao.TeamGroupRelation = (*TeamGroupRelation)(nil)
Move before APIs.

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/time_range_activator.go
> +// CreateTimeRangeActivator implements dao.TimeRangeActivator.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/time_range_activator.go
> +// FindTimeRangeActivatorByID implements dao.TimeRangeActivator.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/time_range_activator.go
> +func (*TimeRangeActivator) FindTimeRangeActivatorByID(ct context.Context, activatorID uint64) (entity.TimeRangeActivator, *errs.Error) {
Move before `create`.

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/time_range_activator.go
> +var _ dao.TimeRangeActivator = (*TimeRangeActivator)(nil)
Move before APIs.

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/user_group_relation.go
> +// CreateUserGroupRelation implements dao.UserGroupRelation.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/user_group_relation.go
> +// DeleteUserGroupRelation implements dao.UserGroupRelation.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/user_group_relation.go
> +// FindUserIDsByGroupID implements dao.UserGroupRelation.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/user_group_relation.go
> +func (*UserGroupRelation) FindUserIDsByGroupID(ct context.Context, groupID uint64) ([]uint64, *errs.Error) {
Move before `create`

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/user_group_relation.go
> +var _ dao.UserGroupRelation = (*UserGroupRelation)(nil)
Move before APIs.

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/version_selector.go
> +// CreateVersionSelector implements dao.VersionSelector.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/version_selector.go
> +// FindVersionSelectorByID implements dao.VersionSelector.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/version_selector.go
> +func (*VersionSelector) FindVersionSelectorByID(ct context.Context, selectorID uint64) (entity.VersionSelector, *errs.Error) {
Move before `create`

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/version_selector.go
> +var _ dao.VersionSelector = (*VersionSelector)(nil)
Move before `APIs`

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/version_selector_version_relation.go
> +// CreateVersionSelectorVersionRelation implements dao.VersionSelectorVersionRelation.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/version_selector_version_relation.go
> +// FindVersionNumbersBySelectorID implements dao.VersionSelectorVersionRelation.
```suggestion
```

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/version_selector_version_relation.go
> +func (*VersionSelectorVersionRelation) FindVersionNumbersBySelectorID(ct context.Context, selectorID uint64) ([]int, *errs.Error) {
Move before `create`

2023-09-10 17:46 UTC, naturetime10 commented on core/dao/sqldb/version_selector_version_relation.go
> +var _ dao.VersionSelectorVersionRelation = (*VersionSelectorVersionRelation)(nil)
Move before APIs.

2023-09-10 19:31 UTC, duanxianbo commented on go.mod
> +	github.com/benbjohnson/clock v1.3.5
used in timeRangeActivator

2023-09-10 20:15 UTC, naturetime10 requested changes

2023-09-10 20:15 UTC, naturetime10 commented on core/service/app.go
> +func (a App) CreateAppSecret(ct context.Context, appID uint64, name string) (entity.AppSecret, *errs.Error) {
```suggestion
func (a App) CreateAppSecret(ct context.Context, appID uint64, input CreateAppSecretInput) (entity.AppSecret, *errs.Error) {
```

Define input type so that we can easily add more fields in the future without changing API signature.

2023-09-10 20:15 UTC, naturetime10 commented on core/service/app.go
> +func (a App) UpdateAppSecret(ct context.Context, appID uint64, appSecretID uint64, name string) (entity.AppSecret, *errs.Error) {
```suggestion
func (a App) UpdateAppSecret(ct context.Context, appID uint64, input UpdateAppSecretInput) (entity.AppSecret, *errs.Error) {
```

Define input type so that we can easily add more fields in the future without changing API signature.

2023-09-10 20:15 UTC, naturetime10 commented on core/service/group.go
> +}
Put `create` before `update`.

2023-09-10 20:15 UTC, naturetime10 commented on core/service/group.go
> +	}
Can we add `TODO` to use transaction in the follow up PR?

2023-09-10 20:15 UTC, naturetime10 commented on core/service/group.go
> +	err := g.staticGroupDao.UpdateStaticGroup(ct, group)
Can we add `TODO` to use transaction in the follow up PR?

2023-09-10 20:15 UTC, naturetime10 commented on core/service/group.go
> +	filterGroup, err := g.filterGroupDao.CreateFilterGroup(ct, filterGroup)
Can we add `TODO` to use transaction in the follow up PR?

2023-09-10 20:15 UTC, naturetime10 commented on core/service/group.go
> +	group, err := g.staticGroupDao.CreateStaticGroup(ct, group)
Can we add `TODO` to use transaction in the follow up PR?

2023-09-10 20:15 UTC, naturetime10 commented on core/service/group.go
> +	err := g.staticGroupDao.UpdateStaticGroup(ct, group)
Can we add `TODO` to use transaction in the follow up PR?

2023-09-10 20:15 UTC, naturetime10 commented on core/service/group.go
> +	filterGroup, err := g.filterGroupDao.CreateFilterGroup(ct, filterGroup)
Can we add `TODO` to use transaction in the follow up PR?

2023-09-10 20:15 UTC, naturetime10 commented on core/service/rollout.go
> +		var err *errs.Error
@duanxianbo Maybe not? Activator and version selector have states (activated, viewed). Will sharing between rollouts mess them up?

2023-09-10 20:17 UTC, naturetime10 requested changes

2023-09-10 20:17 UTC, naturetime10 commented on core/service/rollout.go
> +
```suggestion
```

2023-09-10 22:03 UTC, naturetime10 approved these changes

2023-09-10 22:03 UTC, naturetime10 commented on core/dao/sqldb/team_group_relation.go
> +func (*TeamGroupRelation) CreateTeamGroupRelation(ct context.Context, teamGroupRelation entity.TeamGroupRelation) (entity.TeamGroupRelation, *errs.Error) {
Add empty line above this.

2023-09-10 22:03 UTC, naturetime10 commented on core/dao/sqldb/user_group_relation.go
> +func (*UserGroupRelation) CreateUserGroupRelation(ct context.Context, userGroupRelation entity.UserGroupRelation) (entity.UserGroupRelation, *errs.Error) {
Add empty line above

2023-09-10 22:06 UTC, naturetime10 approved these changes

2023-09-10 22:06 UTC, merged