Allow user to set priority for a task
teamyapp/teamy-backend pull request #476
Opened 2023-09-21 08:37 UTC by xiaoral2

[(task:18335)](https://staging.teamyapp.com/teams/107/tasks/18335)

2023-09-21 10:01 UTC, naturetime10 requested changes

2023-09-21 10:01 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	priority: Priority
Move priority above dueAt

2023-09-21 10:02 UTC, naturetime10 commented
Please remove "backend" from PR title.

2023-09-21 10:14 UTC, naturetime10 commented
Can we also add this field to all gRPC APIs related to task?

2023-09-21 10:19 UTC, naturetime10 commented
You need to install protoc, golang grpc plugin, and then run ./scripts/proto_gen.js to generate updated client and server code for gRPC in Go.

2023-09-22 02:33 UTC, naturetime10 approved these changes

2023-09-22 03:19 UTC, duanxianbo commented on core/api/proto/task.proto
> +
```suggestion
```

2023-09-22 14:28 UTC, merged