Extract metadata data from manifest and update AppVersion
teamyapp/teamy-backend pull request #479
Opened 2023-09-24 15:15 UTC by duanxianbo

[(task:18631)](https://staging.teamyapp.com/teams/107/tasks/18631)

2023-09-24 18:02 UTC, naturetime10 requested changes

2023-09-24 18:02 UTC, naturetime10 commented on core/dao/sqldb/app_version_change.go
> +		INSERT INTO app_version_change (app_id, version_number, change)
```suggestion
		INSERT INTO app_version_change (
		  app_id, 
		  version_number, 
		  change
		) 
```

2023-09-24 18:02 UTC, naturetime10 commented on core/dao/sqldb/app_version_price.go
> +		INSERT INTO app_version_price (app_id, version_number, currency, amount)
```suggestion
		INSERT INTO app_version_price (
		  app_id, 
		  version_number, 
		  currency, 
		  amount
		)
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +}
Maybe put between line 680 and line line 681?

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +type Uploader func(io.Reader) *errs.Error
Can we put this to the top of this file?

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +*/
```suggestion
/*
    removeTarFilePrefix removes the first directory name from file header name.
    The file extracted from the tar will have the name of tar as prefix in the file name.
    The prefix is defined by the user
    Eg:
        tar name: app.tar
        before tar: manifest.yaml
        after extract from tar: app/manifest.yaml
*/
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +func (a App) sanitizeTarHeaderName(headerName string) string {
```suggestion
func (a App) removeTarFilePrefix(fileHeaderName string) string {
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +	headerName = tarNameSanitizer.ReplaceAllString(headerName, "")
parts := strings.Split(headerName, string(os.PathSeparator))
return filepath.join(parts[1:]...)

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +var tarNameSanitizer = regexp.MustCompile(`^[^/]+/`)
```suggestion
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +	readers := multiReader.GenerateMultiReaders(reader, 2)
```suggestion
	readers := tmio.NewMultiReaders(reader, 2)
```

Is the additional `GenerateMultiReaders` necessary? Can we merge `NewMultiReaders` and `GenerateMultiReaders` to a single API?

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +type Uploader func(io.Reader) *errs.Error
```suggestion
type uploadFunc func(io.Reader) *errs.Error
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +		return a.processManifestFile(ct, userID, appID, reader, uploader)
```suggestion
		return a.processManifestFile(ct, userID, appID, reader, uploadFunc)
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +func (a App) processFile(ct context.Context, userID uint64, appID uint64, reader *tar.Reader, fileName string, uploader Uploader) *errs.Error {
```suggestion
func (a App) processFile(ct context.Context, userID uint64, appID uint64, reader *tar.Reader, fileName string, uploader uploadFunc) *errs.Error {
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +		return uploader(reader)
```suggestion
		return uploadFunc(reader)
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +		err := uploader(uploadReader)
```suggestion
		err := uploadFunc(uploadReader)
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +		IsReady:         true,
Are we going to change this to enum in the next PR?

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +		}
I thought we already created the app version in the UI and we are waiting for the app version to be updated through this logic.

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2023-09-24 18:02 UTC, naturetime10 commented on core/service/app.go
> +		Number:          manifestData.Number,
Maybe we can exclude `versionNumber` from manifest and the `versionNumber` passed into this API?

2023-09-24 18:02 UTC, naturetime10 commented on migrations/20230924110050_update-app-version-price-and-change-tables.sql
> +ALTER TABLE app_version_price
Can we use `app_id, version_number, currency` as PRIMARY KEY instead? There can't be multiple prices in the same currency for the same AppVersion

2023-09-24 18:02 UTC, naturetime10 commented on migrations/20230924110050_update-app-version-price-and-change-tables.sql
> +ALTER TABLE app_version_change
Can we add change_id? `change` is string description and is okay to have repetition. It shouldn't be part of primary key.

2023-09-24 18:02 UTC, naturetime10 commented on migrations/20230924110050_update-app-version-price-and-change-tables.sql
> +
```suggestion
```

2023-09-24 18:03 UTC, naturetime10 commented
Great job for getting this feature to work!

2023-09-24 18:17 UTC, naturetime10 commented
Please rename this PR to `Extract metadata data from manifest and update AppVersion`

2023-09-26 01:19 UTC, naturetime10 requested changes

2023-09-26 01:19 UTC, naturetime10 commented on core/service/app.go
> +	Prices         []struct {
We need to add tag for `prices` also.

2023-09-26 01:36 UTC, duanxianbo commented on core/service/app.go
> +	Prices         []struct {
you mean add a new field in app_version_price table?

2023-09-27 01:32 UTC, naturetime10 requested changes

2023-09-27 01:32 UTC, naturetime10 commented on core/service/app.go
> +	}
```suggestion
	Prices         []struct {
		Currency entity.Currency `yaml:"currency"`
		Amount   int             `yaml:"amount"`
	} `yaml:"prices"`
```

2023-09-27 01:32 UTC, naturetime10 commented on core/service/app.go
> +	manifestData := manifest{}
Let inline `manifest` struct into `processManifestFile`.

2023-09-27 01:32 UTC, naturetime10 commented on migrations/20230924110050_update-app-version-price-and-change-tables.sql
> +	DROP CONSTRAINT pk_app_version_price;
```suggestion
    DROP CONSTRAINT pk_app_version_price;
```

2023-09-27 01:32 UTC, naturetime10 commented on migrations/20230924110050_update-app-version-price-and-change-tables.sql
> +
```suggestion
```

2023-09-27 01:32 UTC, naturetime10 commented on migrations/20230924110050_update-app-version-price-and-change-tables.sql
> +    DROP COLUMN tag;
```suggestion
```

2023-09-27 01:56 UTC, naturetime10 approved these changes

2023-09-27 01:56 UTC, naturetime10 commented on core/api/gql/money.go
> +}
```suggestion
```

2023-09-27 01:56 UTC, naturetime10 commented on core/entity/money.go
> +	Tag      string
```suggestion
```

2023-09-27 01:57 UTC, merged