Add get apps api
teamyapp/teamy-backend pull request #506
Opened 2024-02-27 03:20 UTC by duanxianbo

[(task:19908)](https://staging.teamyapp.com/teams/107/tasks/19908)

2024-02-27 03:20 UTC, duanxianbo commented
need to update cloud

2024-02-27 09:47 UTC, naturetime10 approved these changes

2024-02-27 09:47 UTC, naturetime10 commented on core/dao/sqldb/sql.go
> +}
```suggestion
```

2024-02-27 09:47 UTC, naturetime10 commented on core/dao/sqldb/app_tag_relation.go
> +	tagsStr := toStrsString(tagValues)
```suggestion
	tagsStr := strings.Join(tagValues, ",")
```

2024-02-27 09:47 UTC, naturetime10 commented on core/service/app.go
> +
```suggestion
```

2024-02-27 10:14 UTC, naturetime10 requested changes

2024-02-27 10:14 UTC, naturetime10 commented on core/service/app.go
```
AppName        string         `yaml:"appName"`
Description    string         `yaml:"description"`
HasUiExtension bool           `yaml:"hasUiExtension"`
Changes        []string       `yaml:"changes"`
Prices         map[string]int `yaml:"prices"`
```

2024-02-28 00:03 UTC, duanxianbo commented on core/service/app.go
what is this?

2024-02-28 07:34 UTC, naturetime10 commented on core/service/app.go
Sorry I couldn't add the comment inline. It's inside `processManifestFile`.

2024-02-28 07:34 UTC, naturetime10 approved these changes

2024-02-28 07:34 UTC, merged