Add project, phase and story tables
teamyapp/teamy-backend pull request #519
Opened 2024-03-04 03:41 UTC by duanxianbo

[(task:20404)](https://staging.teamyapp.com/teams/107/tasks/20404)

2024-03-04 03:45 UTC, duanxianbo commented on core/dao/sqldb/phase.go
> +
```suggestion
```

2024-03-04 03:45 UTC, duanxianbo commented on core/dao/sqldb/project.go
> +			updated_at
```suggestion
		id,
		name,
		expected_start_at,
		actual_start_at,
		expected_end_at,
		actual_end_at,
		creator_id,
		created_at,
		updated_at
```

2024-03-04 03:45 UTC, duanxianbo commented on core/dao/sqldb/project.go
> +			updated_at = $8
```suggestion
		name = $1,
		expected_start_at = $2,
		actual_start_at = $3,
		expected_end_at = $4,
		actual_end_at = $5,
		creator_id = $6,
		created_at = $7,
		updated_at = $8
```

2024-03-04 03:45 UTC, duanxianbo commented on core/dao/sqldb/story.go
> +			updated_at
```suggestion
		id,
		name,
		owner_id,
		status,
		priority,
		creator_id,
		created_at,
		updated_at
```

2024-03-04 03:45 UTC, duanxianbo commented on core/dao/sqldb/story.go
> +			updated_at
```suggestion
		id,
		name,
		owner_id,
		status,
		priority,
		creator_id,
		created_at,
		updated_at
```

2024-03-04 03:45 UTC, duanxianbo commented on core/dao/sqldb/story.go
> +			updated_at = $7
```suggestion
		name = $1,
		owner_id = $2,
		status = $3,
		priority = $4,
		creator_id = $5,
		created_at = $6,
		updated_at = $7
```

2024-03-04 03:53 UTC, naturetime10 requested changes

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/phase.go
> +		phases = append(phases, phase)
```suggestion
		}
		
		phases = append(phases, phase)
```

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/phase_story_relation.go
> +		storyIDs = append(storyIDs, storyID)
```suggestion
		}
		
		storyIDs = append(storyIDs, storyID)
```

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/phase_story_relation.go
> +	`, phaseID, storyID)
```suggestion
	`, 
	phaseID, 
	storyID)
```

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/project.go
> +
```suggestion
```

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/project.go
> +
```suggestion
```

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/project_phase_relation.go
> +		phaseIDs = append(phaseIDs, phaseID)
```suggestion
		}
		
		phaseIDs = append(phaseIDs, phaseID)
```

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/project_story_relation.go
> +		storyIDs = append(storyIDs, storyID)
```suggestion
		}
		
		storyIDs = append(storyIDs, storyID)
```

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/story.go
> +
```suggestion
```

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/story.go
> +		stories = append(stories, story)
```suggestion
		}
		
		stories = append(stories, story)
```

2024-03-04 03:53 UTC, naturetime10 commented on core/dao/sqldb/story_task_relation.go
> +		taskIDs = append(taskIDs, taskID)
```suggestion
		}
		
		taskIDs = append(taskIDs, taskID)
```

2024-03-04 03:53 UTC, naturetime10 commented on migrations/20240303215744_add_project_phase_story_tables.sql
> +
```suggestion
```

2024-03-05 02:21 UTC, naturetime10 approved these changes

2024-03-05 02:21 UTC, merged