Add isPlanned to task
teamyapp/teamy-backend pull request #527
Opened 2024-04-05 09:22 UTC by duanxianbo

[(task:20610)](https://staging.teamyapp.com/teams/107/tasks/20610)

2024-04-06 00:28 UTC, naturetime10 requested changes

2024-04-06 00:28 UTC, naturetime10 commented on core/service/story.go
> +		task.IsPlanned = false
This assumes a task can only be in 1 story. I think we allow a task to be in multiple stories.

2024-04-06 00:28 UTC, naturetime10 commented on core/service/story.go
> +			task.IsPlanned = false
This assumes a task can only be in 1 story. I think we allow a task to be in multiple stories.

2024-04-07 02:11 UTC, duanxianbo commented on core/service/story.go
> +		task.IsPlanned = false
but that means, tasks will always be in the story task backlog?

2024-04-07 02:53 UTC, naturetime10 approved these changes

2024-04-07 02:53 UTC, naturetime10 commented on core/service/story.go
> +
```suggestion
```

2024-04-07 03:07 UTC, merged