Add and delete sprint participant
teamyapp/teamy-backend pull request #543
Opened 2024-04-23 07:05 UTC by duanxianbo

[(task:21433)](https://staging.teamyapp.com/teams/107/tasks/21433)

2024-04-23 07:11 UTC, naturetime10 requested changes

2024-04-23 07:11 UTC, naturetime10 commented on core/service/sprint.go
> +			numOfWeeks := sprintLength / timePerWeek
There are some tasks assigned to this person in this sprint already?

2024-04-23 07:11 UTC, naturetime10 commented on core/service/sprint.go
> +
```suggestion
```

2024-04-23 07:11 UTC, naturetime10 commented on core/service/sprint.go
> +				participant.UserID,
```suggestion
				userID,
```

2024-04-23 07:11 UTC, naturetime10 commented on core/service/sprint.go
> +
```suggestion
```

2024-04-23 10:20 UTC, duanxianbo commented on core/service/sprint.go
> +			numOfWeeks := sprintLength / timePerWeek
what does that change?

2024-04-23 10:21 UTC, duanxianbo commented on core/service/sprint.go
> +			numOfWeeks := sprintLength / timePerWeek
oh, you mean to subtract the bandwidth with those task efforts?

2024-04-24 02:52 UTC, naturetime10 requested changes

2024-04-24 02:52 UTC, naturetime10 commented on core/service/sprint.go
> +				SprintID:        sprint.ID,
```suggestion
				SprintID:        sprintID,
```

2024-04-24 02:52 UTC, naturetime10 commented on core/service/sprint.go
> +				UserID:          teamMember.UserID,
```suggestion
				UserID:          userID,
```

2024-04-24 04:25 UTC, naturetime10 requested changes

2024-04-24 04:25 UTC, naturetime10 commented on core/service/sprint.go
> +			var subtractedBandwidth time.Duration = 0
```suggestion
			var usedBandwidth time.Duration = 0
```

2024-04-24 04:25 UTC, naturetime10 commented on core/service/sprint.go
> +			totalBandwidth := teamMember.WeeklyBandwidth*numOfWeeks - subtractedBandwidth
```suggestion
			totalBandwidth := teamMember.WeeklyBandwidth*numOfWeeks
```

2024-04-24 04:25 UTC, naturetime10 commented on core/service/sprint.go
>  				UnusedBandwidth: totalBandwidth,
Can we create a variable for unusedBandwidth?

2024-04-24 04:30 UTC, naturetime10 approved these changes

2024-04-24 07:17 UTC, naturetime10 approved these changes

2024-04-24 07:20 UTC, merged