Add upload task context image APIs
teamyapp/teamy-backend pull request #552
Opened 2024-05-15 02:04 UTC by duanxianbo

[(task:21621)](https://staging.teamyapp.com/teams/107/tasks/21621)

2024-05-16 04:52 UTC, naturetime10 requested changes

2024-05-16 04:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	finishTaskContextFileUploadSession(taskId: ID!, fileUploadSessionId: ID!, attachmentListId: ID): Task!
```suggestion
	createAttachmentListFileUploadSession(attachmentListId: ID!): ID!
	finishAttachmentListUploadSession(fileUploadSessionId: ID!, attachmentListId: ID): AttachmentList!
```

2024-05-16 04:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	finishTaskContextFileUploadSession(taskId: ID!, fileUploadSessionId: ID!, attachmentListId: ID): Task!
AttachmentList should be created when creating the task.

2024-05-16 04:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +
```suggestion
```

2024-05-16 04:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	images: [Image!]!
```suggestion
	attachments: [Attachment!]!
```

2024-05-16 04:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +type Image {
```suggestion
type Attachment {
```

2024-05-16 04:52 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	url: String!
```suggestion
    type: AttachmentType!
	url: String!
```

2024-05-16 21:34 UTC, duanxianbo commented on core/api/gql/schema.graphql
> +	finishTaskContextFileUploadSession(taskId: ID!, fileUploadSessionId: ID!, attachmentListId: ID): Task!
I suppose we will do backfill for existing tasks? or we do not care?

2024-05-18 02:13 UTC, naturetime10 requested changes

2024-05-18 02:13 UTC, naturetime10 commented on core/dao/sqldb/attachment.go
> +
```suggestion
```

2024-05-18 02:13 UTC, naturetime10 commented on core/dao/sqldb/attachment.go
> +		INSERT INTO image (id, type, url, size, attachment_list_id, created_at)
```suggestion
		INSERT INTO image 
		(
		    id, 
		    type, 
		    url, 
		    size, 
		    attachment_list_id, 
		    created_at
		  )
```

2024-05-18 02:13 UTC, naturetime10 commented on core/dao/attachment_list.go
> +	FindAttachmentListByIDWithTx(ct context.Context, tx *transaction.Transaction, attachmentListID uint64) (entity.AttachmentList, *errs.Error)
```suggestion
	FindAttachmentListByIDWithTx(
	    ct context.Context, 
	    tx *transaction.Transaction, 
	    attachmentListID uint64,
	) (entity.AttachmentList, *errs.Error)
```

2024-05-18 02:13 UTC, naturetime10 commented on core/dao/attachment_list.go
> +	FindAttachmentListsWithTx(ct context.Context, tx *transaction.Transaction, ownerID uint64, ownerType entity.AttachmentListOwnerType, ListLabel string) ([]entity.AttachmentList, *errs.Error)
```suggestion
	FindAttachmentListsWithTx(
	    ct context.Context, 
	    tx *transaction.Transaction,
	    ownerType entity.AttachmentListOwnerType, 
	    ownerID uint64, 
	    listLabel string
	 ) ([]entity.AttachmentList, *errs.Error)
```

2024-05-18 02:13 UTC, naturetime10 commented on core/dao/attachment.go
> +	FindAttachmentsByAttachmentListIDWithTx(ct context.Context, tx *transaction.Transaction, attachmentListID uint64) ([]entity.Attachment, *errs.Error)
```suggestion
	FindAttachmentsByAttachmentListIDWithTx(
	    ct context.Context, 
	    tx *transaction.Transaction, 
	    attachmentListID uint64,
	) ([]entity.Attachment, *errs.Error)
```

2024-05-18 02:13 UTC, naturetime10 commented on core/mutation/create_attachment.go
> +	return internalErr
```suggestion
	return c.attachmentDao.CreateAttachment(ct, tx, c.attachment)
```

2024-05-18 02:13 UTC, naturetime10 commented on core/realtime/collection.go
> +	ImageCollectionType                CollectionType = "Image"
```suggestion
	AttachmentCollectionType                CollectionType = "Attachment"
```

2024-05-18 02:13 UTC, naturetime10 commented on core/service/attachment.go
> +func (a *Attachment) FindAttachmentList(ct context.Context, ownerID uint64, ownerType entity.AttachmentListOwnerType, listLabel string) (*entity.AttachmentList, *errs.Error) {
```suggestion
func (a *Attachment) FindAttachmentList(
    ct context.Context,
    ownerType entity.AttachmentListOwnerType,
    ownerID uint64,  
    listLabel string,
) (*entity.AttachmentList, *errs.Error) {
```

2024-05-18 02:13 UTC, naturetime10 commented on core/service/attachment.go
> +	err := a.transactionGroupFactory.WithTransactionGroup(ct, true, func(tx *cloudTransaction.Transaction, rtTx *realtime.Transaction) *errs.Error {
Should we make `ownerType, ownerID, listLabel` the primary instead?

2024-05-18 02:13 UTC, naturetime10 commented on core/service/attachment.go
> +
```suggestion
```

2024-05-18 02:13 UTC, naturetime10 commented on core/service/attachment.go
> +
```suggestion
```

2024-05-18 02:13 UTC, naturetime10 commented on core/service/attachment.go
> +
```suggestion
```

2024-05-18 02:13 UTC, naturetime10 commented on core/service/attachment.go
> +	logger                         telemetry.Logger
```suggestion
	logger                         telemetry.Logger
	cloudClientRegistry            *client.Registry
	transactionGroupFactory        transaction.GroupFactory
	cloudWebAPIExternalBaseURL     string
```

2024-05-18 02:13 UTC, naturetime10 commented on core/service/attachment.go
> +	logger telemetry.Logger,
```suggestion
	logger telemetry.Logger,
	cloudClientRegistry *client.Registry,
	transactionGroupFactory transaction.GroupFactory,
	cloudWebAPIExternalBaseURL string,
```

2024-05-18 02:13 UTC, naturetime10 commented on core/service/task.go
> +
```suggestion
```

2024-05-18 02:13 UTC, naturetime10 commented on migrations/20240512212746_create_attachment_tables.sql
> +    attachment_list_id BIGINT NOT NULL REFERENCES attachment_list (list_id),
```suggestion
    attachment_list_id BIGINT NOT NULL REFERENCES attachment_list(list_id),
```

2024-05-18 02:13 UTC, naturetime10 commented on migrations/20240512212746_create_attachment_tables.sql
> +    attachment_list_id BIGINT NOT NULL REFERENCES attachment_list (list_id),
```suggestion
    attachment_list_id BIGINT NOT NULL REFERENCES attachment_list(list_id),
```

2024-05-18 02:13 UTC, naturetime10 commented on core/dao/sqldb/attachment_list.go
> +func (a *AttachmentList) FindAttachmentListsByOwnerIDAndOwnerTypeWithTx(ct context.Context, tx *transaction.Transaction, ownerID uint64, ownerType entity.AttachmentListOwnerType) ([]entity.Attachment
```suggestion
func (a *AttachmentList) FindAttachmentListsByOwnerIDAndOwnerTypeWithTx(
    ct context.Context, 
    tx *transaction.Transaction, 
    ownerType entity.AttachmentListOwnerType,
    ownerID uint64,
) ([]entity.AttachmentList, *errs.Error) {
```

2024-05-18 02:13 UTC, naturetime10 commented on core/dao/attachment_list.go
> +	FindAttachmentListsByOwnerIDAndOwnerTypeWithTx(ct context.Context, tx *transaction.Transaction, ownerID uint64, ownerType entity.AttachmentListOwnerType) ([]entity.AttachmentList, *errs.Error)
```suggestion
	FindAttachmentListsByOwnerIDAndOwnerTypeWithTx(
	    ct context.Context, 
	    tx *transaction.Transaction, 
	    ownerType entity.AttachmentListOwnerType,
	    ownerID uint64,
	) ([]entity.AttachmentList, *errs.Error)
```

2024-05-18 02:13 UTC, naturetime10 approved these changes

2024-05-18 18:29 UTC, duanxianbo commented on core/service/attachment.go
> +	err := a.transactionGroupFactory.WithTransactionGroup(ct, true, func(tx *cloudTransaction.Transaction, rtTx *realtime.Transaction) *errs.Error {
discussed offline, we control this at app level

2024-05-18 20:39 UTC, merged