Use protocol
teamyapp/teamy-backend pull request #570
Opened 2024-06-22 21:57 UTC by duanxianbo

2024-06-26 02:13 UTC, naturetime10 requested changes

2024-06-26 02:13 UTC, naturetime10 commented on apps/github/app_api.go
> +
```suggestion
```

2024-06-26 02:13 UTC, naturetime10 commented on apps/github/app_api.go
> +
```suggestion
```

2024-06-26 02:13 UTC, naturetime10 commented on apps/github/app_api.go
> +	userIDs := collect.Map(listTeamMembersRes.TeamMembers, func(member *pbmessage.TeamMember, _ int) uint64 {
Can we fetch users directly?

2024-06-26 02:13 UTC, naturetime10 commented on core/api/task_rpc.go
> +		Goal:         *req.Goal,
Is this `*` needed? Will this cause `nil` pointer error?

2024-06-26 02:13 UTC, naturetime10 commented on core/api/user_rpc.go
> +
```suggestion
```

2024-06-26 02:13 UTC, naturetime10 commented on go.mod
> +replace github.com/teamyapp/protocol/pb/pbgo => ../protocol/pb/pbgo
Remember to check in protocol first.

2024-06-28 01:22 UTC, duanxianbo commented on core/api/task_rpc.go
> +		Goal:         *req.Goal,
make every update field nullable

2024-06-28 05:06 UTC, naturetime10 approved these changes

2024-06-28 05:06 UTC, naturetime10 commented on core/service/task.go
> +			}
```suggestion
			}
			
```

2024-06-28 05:06 UTC, naturetime10 commented on core/service/task.go
> +			}
```suggestion
			}
			
```

2024-06-28 05:06 UTC, naturetime10 commented on core/api/task_rpc.go
> +func NewTaskRPC(logger telemetry.Logger, taskService service.Task, taskLinkService service.TaskLink, attachmentService *service.Attachment) TaskRPC {
```suggestion
func NewTaskRPC(
    logger telemetry.Logger, 
    taskService service.Task, 
    taskLinkService service.TaskLink, 
    attachmentService *service.Attachment,
) TaskRPC {
```

2024-06-28 05:07 UTC, naturetime10 approved these changes

2024-06-28 05:07 UTC, naturetime10 commented on core/api/gql/schema.graphql
> +	owningTeamId: ID
This is changing the semantics for update input. Is this a pattern change moving forwards?

2024-06-29 00:14 UTC, duanxianbo commented on core/api/gql/schema.graphql
> +	owningTeamId: ID
I think so, to generalize this pattern will make our migration easier

2024-06-29 00:17 UTC, merged