Draft GraphQL schema v2
teamyapp/teamy-backend pull request #60
Opened 2021-11-26 09:38 UTC by CreatCodeBuild

![image](https://user-images.githubusercontent.com/8919794/143684227-161066d8-afc5-4b71-a631-00792d142bfc.png)

![image](https://user-images.githubusercontent.com/8919794/143685186-9a3a652d-df42-4ee4-8052-ab51f2342b1e.png)

2021-11-27 00:39 UTC, naturetime10 requested changes
Hi Albert, thank you so much for making our next version of API flexible and scalable. I left few questions & comments

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/schema-draft.graphqls
> +    change
```suggestion
    update
```

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/resolver-draft.go
> +package schema
Let's create `app/api/gqlv2` package and move everything inside so that we don't need `draft` suffix for everything.

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/task.gql
> +	goal: String!    # is this title?
Yes, this is the title. It cannot be `null`. A task without goal is `achievable`.

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/schema-draft.graphqls
> +    change
Are there any reason we prefer `change` over `update`?

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/schema-draft.graphqls
> +}
Just wondering, we are not going to record any additional `payload`, right?

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/task.gql
> +	context: String! # content?
This means description or any additional information that's need to complete this task. You can consider it as notes for the doer.

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/task.gql
> +	creator: User!
Just wondering, is this immutable? Are we recording this field for future usage?

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/schema-draft.graphqls
> +    creation
Let's make the enum values all caps

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/task.gql
> +union Mentionable = User | Task
Do we need to use retrospection at frontend?

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/schema-draft.graphqls
> +}
Are we going to add `teams` and `activeUser` later?

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/schema-draft.graphqls
> +	mutation: Mutation
So mutation will be the next PR?

2021-11-27 00:39 UTC, naturetime10 commented on app/api/gql/schema/resolver-draft.go
> +	deps           DependencyObject
```suggestion
	deps           Dependencies
```

Great! I think this will allow the business logic to evolve without constantly adding or removing dependencies.

2021-11-27 02:12 UTC, CreatCodeBuild commented on app/api/gql/schema/schema-draft.graphqls
> +}
`teams` yes. What is `activeUser`?

2021-11-27 02:12 UTC, CreatCodeBuild commented on app/api/gql/schema/schema-draft.graphqls
> +}
What do you mean?

2021-11-27 02:13 UTC, CreatCodeBuild commented on app/api/gql/schema/schema-draft.graphqls
> +    change
no

2021-11-27 02:13 UTC, CreatCodeBuild commented on app/api/gql/schema/task.gql
> +	creator: User!
creator is immutable. It's history.

2021-11-27 02:15 UTC, CreatCodeBuild commented on app/api/gql/schema/task.gql
> +union Mentionable = User | Task
introspection, yes

2021-11-27 03:14 UTC, naturetime10 requested changes

2021-11-27 03:14 UTC, naturetime10 commented on app/api/gql/schema/schema-draft.graphqls
> +}
Discussed offline. Add `me: User!` as represent current signed in user.

2021-11-27 03:14 UTC, naturetime10 commented on app/api/gql/schema/schema-draft.graphqls
> +}
Discussed offline.

Leaving out `payload` recording for now and add a comment. May consider using GraphQL union:
```
type AssignTo {
   asigneeID: ID
}

type Delete {}

union LifetimeEventType = AssignTo | Delete
```

2021-11-27 03:14 UTC, naturetime10 commented on app/api/gql/schema/schema-draft.graphqls
> +    change
Discussed offline. Prefer `update` over `change` to distinguish semantics from `close`, `delete`, etc...

2021-11-27 03:14 UTC, naturetime10 commented on app/api/gql/schema/task.gql
> +    # time flow
```suggestion
    # time flow for everything below

```

2021-11-27 03:14 UTC, naturetime10 commented on app/api/gql/schema/task.gql
> +union Mentionable = User | Task
Thanks!

2021-11-27 03:14 UTC, naturetime10 commented on app/api/gql/schema/user.gql
> +input UserInput {
```suggestion
input UserFilter {

```

2021-11-28 10:18 UTC, CreatCodeBuild commented
favor #61

2021-11-28 10:18 UTC, closed without merging