Add creator to task
teamyapp/teamy-backend pull request #64
Opened 2021-11-28 14:08 UTC by CreatCodeBuild

# creator
![image](https://user-images.githubusercontent.com/8919794/143772313-6a9180f9-b1b2-45f2-aad1-ed4087e78b94.png)

# Mentions
![image](https://user-images.githubusercontent.com/8919794/143772280-3b3eaff9-b082-401a-83a0-e1efc98f7518.png)

2021-11-28 14:43 UTC, CreatCodeBuild commented on app/api/gql/resolver/task.go
> +	return resolver.ParseMentions(*t.Context()), nil
> To be honest, `content` or even `detail` is a better name than `context` and `goal` could just be `title`.
I find `goal` & `context` quite distracting.

2021-11-28 14:43 UTC, CreatCodeBuild commented on app/api/gqlv2/resolver/mention.go
> +func ParseMentions(input string) (m []Mention) {
This function can also check if parsed mentions are valid entities in the database. But keeping it pure computation is also nice.

2021-11-28 14:43 UTC, CreatCodeBuild commented on app/api/gqlv2/resolver/mention.go
> +func ParseMentions(input string) (m []Mention) {
We can go further to parse Markdown in backend and extend markdown to include reference/mentions syntax.

2021-11-28 14:43 UTC, CreatCodeBuild commented on app/api/gqlv2/resolver/mention.go
> +	}
Thanks @magicoder10

2021-11-28 14:46 UTC, CreatCodeBuild commented on app/api/gqlv2/resolver/data.go
> +}
I am basically doing relational database manually. This looks crazy but the good side is that we move faster.

Let's think about database design when frontend & the whole system is fully useable.

2021-11-28 14:54 UTC, CreatCodeBuild commented on app/api/gqlv2/resolver/data.go
> +func (d *Data) FilterCreationRelation(f func(CreationRelation) bool) (rs []CreationRelation) {
`FilterX` functions will be hard to implement when we actually use databases. How can we implement arbitrary filterer interface if the data source is postgres?

We will effectively make backend service a query engine of the database. This is not 100% impossible but cost is big. 

We will have to change the interface here and that is OK for me.

2021-11-28 14:55 UTC, CreatCodeBuild reviewed
something for you to consider

2021-11-28 19:27 UTC, naturetime10 requested changes

2021-11-28 19:27 UTC, naturetime10 commented on app/api/gql/resolver/task.go
> +
```suggestion
```

2021-11-28 19:27 UTC, naturetime10 commented on app/api/gql/resolver/task.go
> +	return resolver.ParseMentions(*t.Context()), nil
Let's keep `goal` & `context` for now. The terms are designed for teamwork environment. We can revisit in the future.

2021-11-28 19:27 UTC, naturetime10 commented on app/api/gql/resolver/user.go
> +	ID graphql.ID
I think we have `ID` in `Entity`.

2021-11-28 19:27 UTC, naturetime10 commented on app/api/gqlv2/resolver/data.go
> +}
@CreatCodeBuild Sounds good for now.

2021-11-28 19:27 UTC, naturetime10 commented on app/api/gqlv2/resolver/mention.go
> +func ParseMentions(input string) (m []Mention) {
@CreatCodeBuild Let's get the basic functionalities working and consider Markdown support for later version.

2021-11-28 19:28 UTC, naturetime10 commented
Please run `goimports -w app` to format the code

2021-11-29 02:48 UTC, CreatCodeBuild commented on app/api/gql/resolver/task.go
> +
I used `go fmt`

2021-11-29 02:49 UTC, CreatCodeBuild commented on app/api/gql/resolver/user.go
> +	ID graphql.ID
yes, this is just to expose to graphql

2021-11-29 02:49 UTC, naturetime10 commented on app/api/gql/resolver/task.go
> +
How about `goimports -w ./app`?

2021-11-29 02:50 UTC, naturetime10 commented on app/api/gql/resolver/user.go
> +	ID graphql.ID
@CreatCodeBuild It is exposed to GraphQL. This is GraphQL entity.

2021-11-29 02:51 UTC, CreatCodeBuild commented on app/api/gql/resolver/task.go
> +
well, it did change this line.

2021-11-29 02:52 UTC, CreatCodeBuild commented on app/api/gql/resolver/user.go
> +	ID graphql.ID
What I meant is this `ID` is the field resolver for GraphQL fields.

2021-11-29 02:56 UTC, naturetime10 commented on app/api/gql/resolver/user.go
> +	ID graphql.ID
https://github.com/teamyapp/teamy-backend/blob/master/app/api/gql/resolver/entity.go

2021-11-29 03:57 UTC, naturetime10 approved these changes

2021-11-29 07:31 UTC, merged