Persist JSON data to Postgres
teamyapp/teamy-backend pull request #93
Opened 2021-12-03 14:23 UTC by CreatCodeBuild

Very bad performance is observed for normal queries
```
{
  task(id:25) {
    id
    goal
  }
}
```
even for something like this, it is very slow.

It could be that sending auth request from my local to staging identity service is slow.

2021-12-03 14:36 UTC, CreatCodeBuild reviewed
Should find out if identity service is slow or just my network. Please do a local test in US as well.

2021-12-03 14:36 UTC, CreatCodeBuild commented on app/repo/db/migration/20211201034924_json.up.sql
> +insert into json_persister (data, id) values('{}', 1);
this table should only have 1 row

2021-12-04 02:53 UTC, naturetime10 requested changes

2021-12-04 02:53 UTC, naturetime10 commented on app/api/gqlv2/resolver/data.go
> +		where id = 1
```suggestion
		UPDATE json_persister
		SET data = $1
		WHERE id = 1;
```

2021-12-04 02:53 UTC, naturetime10 commented on app/api/gqlv2/resolver/data.go
> +	`)
```suggestion
	row := p.db.QueryRow(`
	SELECT data FROM json_persister WHERE id = 1;
	`)
```

2021-12-04 02:53 UTC, naturetime10 commented on app/repo/db/migration/20211201034924_json.up.sql
> +insert into json_persister (data, id) values('{}', 1);
```suggestion
INSERT INTO json_persister (data, id) VALUES ('{}', 1);
```

2021-12-04 02:56 UTC, naturetime10 approved these changes

2021-12-04 03:05 UTC, merged