Update task & comment on task
teamyapp/teamy-backend pull request #94
Opened 2021-12-04 11:44 UTC by CreatCodeBuild

### Update Task
![image](https://user-images.githubusercontent.com/8919794/144708518-bb36a68c-0a93-4a82-a471-a2727916a242.png)

### Comment
![image](https://user-images.githubusercontent.com/8919794/144708527-5eb1644f-6bff-4c39-bf23-1258030e6605.png)

2021-12-04 11:44 UTC, CreatCodeBuild commented on app/api/gql/datastore/data.go
> +	Tasks             map[graphql.ID]entity.Task
refactored `Data` to use entities.

2021-12-04 11:45 UTC, CreatCodeBuild commented on app/api/gql/resolver/1_mutation.go
> -	prototypeDeps *resolver.Dependencies
remove `prototypeDeps` and add `DataStore` to `deps`

2021-12-04 11:45 UTC, CreatCodeBuild commented on app/api/gql/resolver/1_mutation.go
> +	task, err = m.deps.Data.CreateTask(toGraphQLID(userID), task)
Turns out not double committing works fine.

2021-12-04 11:50 UTC, CreatCodeBuild reviewed
With `PostgresPersister`, we persists all data on every write. This will become slow when we have 10,000+ objects. At that moment, we need to persist each field into their own rows.

![image](https://user-images.githubusercontent.com/8919794/144708336-17b4607b-d44e-40ca-bd97-a9a5e88af76c.png)
Currently all data are written to a single row of JSON.
Later, each map/slice will have their own row.
```
type Data struct {
	Tasks             map[graphql.ID]entity.Task
	Users             map[graphql.ID]entity.User
	Comments          []entity.Comment
	LifetimeEvents    []LifetimeEvent
	CreationRelations []CreationRelation
}
```

We effectively created a in-memory business-aware cache.

Pros:
1. No IO on reads! -> Faster than Redis
2. Super fast development

Cons:
1. Can only be used with a single instance.
2. Writes will be more expensive.
When writes become too slow (>= 10ms ), we can migrate to full SQL.

I wont' worry about memory consumption until this uses more than 1GB to just hold the data.

2021-12-04 16:35 UTC, naturetime10 requested changes
Do you think we can break down this PR to smaller ones and remove unused code? For example, changes to `data.go` can be one PR. And other changes can be the second one. Thanks!

2021-12-04 22:02 UTC, naturetime10 requested changes

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/datastore/data.go
> +	ownerID graphql.ID
```suggestion
	OwnerID graphql.ID
```

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	fmt.Printf("%+v\n", d.data.Tasks)
```suggestion
```

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	d.data.Tasks[id] = task
```suggestion
	task, ok := d.data.Tasks[id]
	if !ok {
	    return entity.Task{}, fmt.Errorf("task not found: id=%v", task.ID)
	}
```

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	comment.ID = graphql.ID(fmt.Sprint(len(d.data.Comments)))
Need to generate ID the same way as task

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	fmt.Printf("%+v\n", d.data.Comments)
```suggestion
```

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	// fmt.Printf("%+v", d.data.CreationRelations)
```suggestion
```

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +func (d *DataStore) FilterCreationRelation(f func(CreationRelation) bool) (rs []CreationRelation) {
```suggestion
func (d *DataStore) FilterCreationRelation(filter func(CreationRelation) bool) (rs []CreationRelation) {
```

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +		if f(r) {
```suggestion
		if filter(r) {
```

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/resolver/types.go
> +func ToGraphQLIDs(ids []oneEntity.ID) []graphql.ID {
```suggestion
func toGraphQLIDs(ids []oneEntity.ID) []graphql.ID {
```

2021-12-04 22:02 UTC, naturetime10 commented on app/api/gql/resolver/mention.go
> +	// dep  *Dependencies
Are we commenting this out temporarily?

2021-12-04 22:03 UTC, naturetime10 commented on app/api/gql/resolver/1_mutation.go
> +	task, err = m.deps.Data.CreateTask(toGraphQLID(userID), task)
I worry this may break our internal logic.

2021-12-05 02:24 UTC, CreatCodeBuild commented on app/api/gql/resolver/mention.go
> +	// dep  *Dependencies
yes

2021-12-05 02:35 UTC, CreatCodeBuild commented on app/api/gql/datastore/datastore.go
> +	d.data.Tasks[id] = task
Let's use a global unique ID generator. Can the package you wrote be reused here? In a separate PR.

2021-12-05 02:41 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	d.data.Tasks[id] = task
@CreatCodeBuild Yes

2021-12-05 02:50 UTC, naturetime10 requested changes

2021-12-05 02:50 UTC, naturetime10 commented on app/api/gql/resolver/1_mutation.go
> +	deps  *Dependencies
Can we name this file back to `mutation.go`?

2021-12-05 02:50 UTC, naturetime10 commented on app/api/gql/resolver/1_query.go
> +package resolver
Can we rename this file to `query.go`

2021-12-05 02:50 UTC, naturetime10 commented on app/api/gql/resolver/1_resolver.go
> +package resolver
Can we rename this file to `resolver.go`

2021-12-05 05:26 UTC, naturetime10 requested changes

2021-12-05 05:26 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	}
May I ask what's the difference between those 2 pieces of code?

2021-12-05 05:26 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	}
Can we just do the following for all cases?

```
ds.data.Teams = []entity.Team{
			{Entity: oneEntity.Entity{
				ID: 1,
			}},
		}
```

2021-12-05 05:26 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	}
This is business logic. Ideally it should be inside GraphQL resolver instead of data store.

2021-12-05 05:28 UTC, naturetime10 commented on app/api/gql/datastore/datastore.go
> +	}
We, human, `decided` to have this behavior business wise and data store shouldn't be responsible for it.

2021-12-05 05:40 UTC, CreatCodeBuild commented on app/api/gql/datastore/datastore.go
> +	}
this is a temporary hack to maintain data correctness so that teams are unique.

2021-12-05 05:52 UTC, naturetime10 approved these changes

2021-12-05 05:52 UTC, merged